### ISSUE TITLE
Tabs double onActive on page load

### ISSUE THREAD

**Issue by ktmn** [react-toolbox/react-toolbox#103]
```
        <Tabs>
          <Tab label="one" onActive={() => {console.log('tab one');}}>
            foo
          </Tab>
          <Tab label="two" onActive={() => {console.log('tab two');}}>
            qwe
          </Tab>
        </Tabs>
```

When I load the page I get

    tab one
    tab one

Can anyone reproduce it or is it just my problem somewhere?

Wanted to add tab-specific google analytics pageview trigger, but if it triggers twice it's kind of misleading.

**Comment by javivelasco** [comment]
Hi @ktmn thanks for reporting it!
We are fixing it ASAP. As we said in other issues, during the weekend we want to ship a lot of fixes and new features and hopefully this will be there too :)

**Comment by soyjavi** [comment]
onActive callback will dissapear in the new version of `<Tabs>` component... now we are moving to pure components (stateless). We think is better listen the `onChange` callback and then you choose what you wanna do ;)

best

**Comment by ktmn** [comment]
Does the onChange trigger before or after the change? When I tried I always got the index of the previous tab.

**Comment by javivelasco** [comment]
Hi @ktmn! Check [here](https://github.com/react-toolbox/react-toolbox/blob/pure-components/components/tabs/tabs.jsx) hows the new version going to look like. In this new version you can decide who's responsible from keeping the `index` since it has been extracted from the component state. In this new version you will get the callback as soon as a new tab is clicked so you can get the new index and set the proper state propagating the new index property to the tabs.

What do you think about this?

**Comment by ktmn** [comment]
Looking good, thanks!
