### ISSUE TITLE
Isomorphic?

### ISSUE THREAD

**Issue by liesislukas** [react-toolbox/react-toolbox#104]
Hi, guys your documentation is way better then material-ui, so thank you for your hard work! Docs are very important! While navigating in your page I've noticed, it's not isomorphic. 
Can your lib be rendered on server side?

I have demo code: 
https://github.com/liesislukas/ReactJs-ReactNative-examples/tree/master/examples/react-router-isomorphic

**Comment by javivelasco** [comment]
Hi @liesislukas, thank you so much for your words, we appreciate it!!

The page is currently deployed in Github pages and working as a static SPA, that's why it's not isomorphic. Maybe we can consider in a near future to create an server rendering app for the documentation. I think there would be no problem rendering in the server, maybe we would need to change some stuff but I've never tried before so I can't give you a straight answer.

I'll check on your demo as soon as I can, thanks! :)

**Comment by liesislukas** [comment]
I'm building isomorphic app, so i have to know, that your lib can be used for my project. 

Your docs are great, but it's not easy to navigate and go through your all elements to check what you have. I have enough screen space to open navigation and playground at once and i have to click click click click so many times to go through menu and check how does that item look like in playground. Just keep left navigation open and load playground automatically if client has enough space. 

![a](https://cloud.githubusercontent.com/assets/2733862/11166250/e43163ee-8b34-11e5-8ce3-d6d2c621fe9c.png)
![b](https://cloud.githubusercontent.com/assets/2733862/11166251/e4322220-8b34-11e5-9b18-9aeebdfe8a34.png)
![c](https://cloud.githubusercontent.com/assets/2733862/11166257/1eb84078-8b35-11e5-84cc-dc1af2d584fd.png)

**Comment by EnzoMartin** [comment]
You can render server side when using `react-toolbox` without issue, I'm currently using it that way

**Comment by javivelasco** [comment]
Amazing :)
