### ISSUE TITLE
Input field error option

### ISSUE THREAD

**Issue by coljung** [react-toolbox/react-toolbox#1051]
How can i implement the 'error' option from the Input component ?

On the documentation it simply says:

`
Give an error node to display under the field.
`

I tried setting a string as it is stated and the problem i get is that the error is shown all the time, how can i control its behaviour ( hide/ show), validate, etc ?

**Comment by joevbruno** [comment]
You need to store the error outside of the Input component either in a parent component's state, redux or some other option. If there is an error - either because the parent said there was or you determine there is via a helper method and the current input value, pass the error, otherwise pass null.

**Comment by masakij** [comment]
I wrote a sample code.
http://codepen.io/masakij/pen/rWQXyy/

**Comment by coljung** [comment]
great thx, will check it out!
