### ISSUE TITLE
how to change icon size on <FontIcon/>

### ISSUE THREAD

**Issue by rudot** [react-toolbox/react-toolbox#1076]
how to change icon size on  <FontIcon /> component

here's example how to change icon size on material ui docs.

    <IconButton  iconStyle={styles.largeIcon}  >
    </IconButton>

**Comment by javivelasco** [comment]
If you are using a `FontIcon` component you can pass a `className` and change its size:

```jsx
<FontIcon className="icon"} value="favorite" />
```

And then define the CSS to change its size. In case the `FontIcon` is rendered as a dependency of the component you are using (for example, in an `IconButton`) you have two options:
- Customize the main component modifying its CSS to target the icon. The component must have a key to style the Icon. For example, the `IconButton` has a `.icon` className that can be passed to style the icon.
- Instead of using the generation you can simple nest the component:

```jsx
<IconButton><FontIcon className="foo" value="favorite" /></IconButton>
```

And then define the styles. Remember this is CSS.
