### ISSUE TITLE
css variables, theming and old browser.

### ISSUE THREAD

**Issue by pavellob** [react-toolbox/react-toolbox#1080]
I try to override primary color for all my app, somesing like this:

`:root {
  --color-primary: var(--palette-blue-a200);
  --color-primary-dark: var(--palette-blue-a500);
}`

it's ok for chrome and firefox, but Edge and IE don't understand css variables, so I run in my webpack 
postcss-cssnext plugin:
`postcss: [ 
....
    require('postcss-cssnext')
 ],`
it work correctly, but in fact I have standard indigo colors in browser.
how I should override root variables from variables.css, for correct old-browser understending?

**Comment by benbarber** [comment]
I solved the issue of variable inheritance and overriding previously declared variables by having the "postcss-import" plugin declared **before** "postcss-cssnext" in the plugins. My postcss.config.js is below:

```
const webpack = require('webpack')

module.exports = {
  plugins: {
    'postcss-import': {
      addDependencyTo: webpack,
    },
    'postcss-cssnext': {
      browsers: ['last 2 versions', '> 5%'],
    },
    'postcss-reporter': {
      clearMessages: true
    }
  },
}
```

**Comment by javivelasco** [comment]
@pavellob Usually the overrides should be passed using the Javascript API. [Here](https://github.com/react-toolbox/react-toolbox/blob/dev/docs/webpack.config.development.js#L68) is an example. Also using `react-toolbox-themr` you can place them in a configuration file or the same `package.json`. 

Thanks for your answer @benbarber! Indeed it should be placed before. Otherwise at processing time you don't have resolved the original imports :)
