### ISSUE TITLE
Dropdown stopped working correctly when opened up 

### ISSUE THREAD

**Issue by znvPredatoR** [react-toolbox/react-toolbox#1086]
Here is how it currently behaves for me:
![dropdown-bug](https://cloud.githubusercontent.com/assets/473069/21487639/99ff3dc4-cbce-11e6-819c-71202cbd2cb0.gif)

The reason is this commit: https://github.com/react-toolbox/react-toolbox/commit/2f5e0f5f358db8119913204814596711fd62cefd

`onFocus` is called when I click on the dropdown which calls `open`.

Rolling back to 1.2.5 helped

**Comment by ToniIltanen** [comment]
I noticed the same today. also even when overriding the default onFocus to the dropdown, still open is called.

**Comment by Strainy** [comment]
This is still happening to me even after rolling back to 1.2.5.

Works mostly fine when the `auto` prop is set to false.

**Comment by javivelasco** [comment]
I can't reproduce it :S. Can anybody confirm this is still happening in `dev`? If so, steps or example to make it fail?

**Comment by javivelasco** [comment]
Please reopen with more instructions if it's still happening, I can't reproduce it so I cannot debug either :(

**Comment by znvPredatoR** [comment]
@javivelasco isn't dev is for v2.0 of react-toolbox that would be in development for some time?

**Comment by znvPredatoR** [comment]
@javivelasco could you try to reproduce with latest released version?

**Comment by javivelasco** [comment]
Yep, I've tried with the latest 2.0. It is true that will be on development for some time but personally I cannot dedicate time to both 1.x fixes and future 2.0. Take into account the intention is to release constant betas will change logs and to keep it usable and stable amap. 

Fixes for 1.x will be accepted and merged to master so if this is reproducible for 2.0 I'll be happy to work on it, otherwise it is not considered on my side

**Comment by jmar777** [comment]
Update: I'm ~90% sure I know the problem:

- Before the `onClick()` handler is invoked for the intended value item, the `handleFocus()` method is first invoked (for the entire Dropdown component itself).
- The `handleFocus()` method then calls `this.open(event)`.
- Normally this wouldn't be a problem, because `this.state.active` is already true, but at certain resolutions, it calculates a new value for `this.state.up` then previously.
- The end result is that the `onFocus()` event causes the item list to change positions _before_ the click event itself is dispatched, so instead of the item receiving the click event, it goes to whatever was previously behind the item container.

@javivelasco I'm preparing to confirm a fix for this in my fork; it looks like the most reasonable solution is to bail out of `open()` if `this.state.active === true` already. Alternatively we could do that check in `handleFocus()`. Any opinions on that before I submit a PR?

**Comment by jmar777** [comment]
@javivelasco The fix worked locally, and I couldn't seem to find any regressions in keyboard or mouse interactions to the Dropdown component. PR here: https://github.com/react-toolbox/react-toolbox/pull/1208

@znvPredatoR You might want to re-open the issue? I can't do that as I'm neither contributor nor OP.

**Comment by znvPredatoR** [comment]
@jmar777 I can't reopen as well, we have to rely on @javivelasco to do that
