### ISSUE TITLE
Slider range support

### ISSUE THREAD

**Issue by vsai** [react-toolbox/react-toolbox#1092]
Is there support for using a slider for a range of values?
I want a user to a select a range of values, but all the sliders only seem to support a single value, rather than a lower+upper range.

Is there support for this somewhere?

**Comment by landabaso** [comment]
There's a `min` and a `max` prop.
[Check it out](http://react-toolbox.com/#/components/slider)

**Comment by javivelasco** [comment]
I think it's not defined in [Material Design](https://material.io/guidelines/components/sliders.html#sliders-discrete-slider). If this is not included in the guidelines for some reason we might not implement it or at least we are to assigning too much priority. Otherwise please reopen and it will be considered :)
