### ISSUE TITLE
Adding classnames package for class name manipulation

### ISSUE THREAD

**Issue by bigardone** [react-toolbox/react-toolbox#11]
Hi!
First of all I wanted to say that this project looks very promising, great job done so far!
After taking a look to some of the code I've seen that it's handling class names like this:

```
className  = "#{localCSS.root} #{@props.className}"
className += " #{@props.type}"  if @props.type
className += ' focus'           if @state.focus
```

Is there a performance reason or something like that to do it this way instead of using something like [classnames](https://www.npmjs.com/package/classnames) so it would look something similar to:

```
className = classnames
  "#{localCSS.root} #{@props.className}": true
  "#{@props.type}": @props.type
  focus: @state.focus
```

Thanks in advance :)

**Comment by javivelasco** [comment]
Hi, thanks for your kind words, so glad you like it!

We are handling class names that way simply because we don't see enough return about using classnames plugin. The less dependencies we have, the better. I know that it's included in React as an add-on but apparently is going to be removed in the [next release](https://facebook.github.io/react/docs/class-name-manipulation.html). 

IMHO, using strings that is as we do now make the code more readable than using `classname` plugin. It's not really a matter of performance but anyway we are probably gaining some here since we are manipulating just strings without additional function calls or object manipulation.

Thanks for your feedback and please don't stop checking changes!

**Comment by soyjavi** [comment]
+1


—
Javi Jiménez Villar
@soyjavi
