### ISSUE TITLE
Icons not aligned with buttons

### ISSUE THREAD

**Issue by oxyno-zeta** [react-toolbox/react-toolbox#1112]
Hello,

I spend a lot of time on this bug but I didn't find the solution...
![selection_003](https://cloud.githubusercontent.com/assets/2989735/21662055/f8257a34-d2d7-11e6-8aaf-88b702d2e45b.jpg)
That is the bug... The icons are not aligned with the buttons.

Here is my SASS : 
```
@import "../../node_modules/react-toolbox/lib/commons";

body {
  font-family: 'Roboto', sans-serif;
  font-size: 13px;
  line-height: 1;
}

@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: local('Material Icons'), local('MaterialIcons-Regular'), url('./fonts/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2') format('woff2');
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}
```

My render : 
```
<div>
     <Button icon="add" label="Add this" flat primary />
     <Button icon='bookmark' label='Bookmark' accent />
     <Input type="email" icon="email" label="Email address" value={this.state.email}
                   onChange={this.handleChange} />
</div>
```

Can someone help me ??

Thanks,

Oxyno-zeta

**Comment by javivelasco** [comment]
Importing the buttons with css while just adding the fonts for material icons and roboto works nicely. Apparently the issue here is that you are assigning styles like font size to the items with material icons class. React Toolbox is doing it for you so if you remove those classes and just define the font it should work. Please check how it's done in the example repository, it should be helpful.
