### ISSUE TITLE
How to scroll to the top of the page?

### ISSUE THREAD

**Issue by alltom** [react-toolbox/react-toolbox#112]
I learned in #111 that I was supposed to wrap my page in `<ToolboxApp>`. If I do that, Ripples work, but now I can't use `window.scrollTo()` to scroll to different parts of the page. I also can't put a ref on `<ToolboxApp>` because it's stateless. Is there any way for me to scroll the page programmatically?

**Comment by javivelasco** [comment]
Good point @alltom. We've just changed the `App` component to allow to hold a reference. Remember you can also use a query like `document.querySelector('[data-react-toolbox="app"]') to get the node and modify the `scrollTop` of this element to scroll the document.

Whatever feels cleaner for you. Also you can use a vendor plugin or something to animate the scroll. At the end is just about using the element scroll API instead of the window which I think is bind to the body.

Does it work for you? If not, we can reopen and investigate a better approach!
Thanks :)

**Comment by alltom** [comment]
This works, thanks!
