### ISSUE TITLE
NavDrawer on pinned event 

### ISSUE THREAD

**Issue by grrseguin** [react-toolbox/react-toolbox#1126]
When the `NavDrawer` component is pinned / unpinned, the width of `Panel` change and a child component should be rerendered. 

But, in some case (example : children with absolute position), the rerender must be fired handly and the [component updating lifecycle](https://facebook.github.io/react/docs/react-component.html#updating) is executed before the DOM `offsetWidth` property is well updated.

To avoid to set a timeout, could you add a onPinned event on the `NavDrawer` component with a callback function ?

**Comment by javivelasco** [comment]
I guess this is happening with the 1.x implementation. 2.0.x has it rewritten and doesn't keep any state change, all should be passed via props. Since we are deprecating the old version we are no longer working on it. I'd suggest to move on to the latest version, it is perfectly usable. If you want you can also send a pr to the master branch which currently holds the last stable
