### ISSUE TITLE
A couple questions about Table component

### ISSUE THREAD

**Issue by matthewberkompas** [react-toolbox/react-toolbox#1149]
Hi guys. I have a couple questions about the `Table` component. 
- Is there a way to specify which cells can/can't be edited? I have a table where users will be inputting cost data for lead sources and, while I want to display each lead source's name on the table I don't want users to be able to change them there. 
- Secondly, is there a way to only allow a number to be entered in a given cell? Also, can cells be formatted as dollars or is there a way to put a $ icon in front of each one? Since users will be inputting cost data in my case, the $ sign is really important. 

Thanks in advance!

**Comment by javivelasco** [comment]
Hi @matthewberkompas!

Due to all of this issues and the lack or flexibility, the Table component has been completely rewritten with a different implementation. Now you can nest your own and build your table with whatever content you want instead of depending on a model or data source. If you still find it useful you can create your own wrapper doing the generation we were doing before.

It's available in the latest beta and the dev branch. I hope you like it!

**Comment by matthewberkompas** [comment]
So is this change available on version 1.3.4?

**Comment by matthewberkompas** [comment]
Actually, never mind about this. I've found a work-around for the time being until the next version is released. Thanks for the help!

**Comment by javivelasco** [comment]
This is released with the latest beta. 1.x will keep the previous implementation since it's being deprecated!
