### ISSUE TITLE
Embedding Video in Card

### ISSUE THREAD

**Issue by sushilk1991** [react-toolbox/react-toolbox#115]
Is there any way to embed videos in the card??

**Comment by javivelasco** [comment]
With the current implementation it's not possible because we have a limited amount of card types accepting only properties to build them. We are working in a new iteration that will allow you to compose complex Cards allowing the `Card` component to receive children. This means you will be able to include arbitrary content such as videos or anything else. Coming in next release! :)

**Comment by nathanmarks** [comment]
@javivelasco In my current card setup, the Media area can either accept an image URL for a background image, or you can pass children in with whatever you want. You can also force the area to be 16:9 or 1:1 with `aspectRatio="wide"` or `aspectRatio="square"`

**Comment by javivelasco** [comment]
Looks awesome!! :dancer:

**Comment by nathanmarks** [comment]
I'm also adding support for easy horizontal cards with the image to the side like you see on the spec page.

Also, I want to give users the option to use a background image OR proper image tags. Depending on the situation, an `<img>` element may be more semantic. So as well as a URL for the `<CardMedia image="....`, a user can pass an element or component in for the image to use an element instead of a background image.

**Comment by nathanmarks** [comment]
@javivelasco Just to add to that as well... technically the user could also pass in their video component as the "image" parameter, that would work too with the setup ;)

**Comment by javivelasco** [comment]
Wow that's sounds so cool. I'm going to check your branch during the afternoon!

**Comment by nathanmarks** [comment]
@javivelasco I'll push it tonight -- just got it local at the moment.

**Comment by javivelasco** [comment]
Ok!

**Comment by soyjavi** [comment]
great work @nathanmarks

**Comment by nathanmarks** [comment]
@javivelasco still working on a few things for this... had to end up making a new `<Avatar>` component so I could put together certain types of cards with re-usable code.

**Comment by javivelasco** [comment]
Ok, nice! :)

**Comment by nathanmarks** [comment]
The avatar accepts a string OR an element for the image source -- this is so people can use more semantic markup via `alt` tags and potentially use things like `srcset` for their images. We shouldn't pigeonhole people into only being able to provide an image URL. The UI library shouldn't necessarily make assumptions about how the specific images are served up.

The avatar component also supports icons and text. For eg.

```jsx
<Avatar accent icon="iconname" />
```

Would be an avatar, accent background color with a material design icon.

Other usage is like:

```jsx
<Avatar>T</Avatar> // text Icon
<Avatar image="something.jpg" />

// or...

const myImage = <img src="woof.jpg" alt="a doggy" />

<Avatar image={myImage} />
<Avatar>{myImage}</Avatar> // Same thing
```

Text icon can also be a fallback.

```jsx
// If `myImage` is null or undefined, the avatar will be a T letter
// Otherwise, it will use the image
<Avatar image={myImage}>T</Avatar>
```

**Comment by javivelasco** [comment]
Looks fucking awesome. Looking forward to see the implementation!

**Comment by soyjavi** [comment]
@nathanmarks awesome... really, great work.

**Comment by nathanmarks** [comment]
@soyjavi thanks!

I'm making sure that it is done properly -- so i'll probably need a few more days, my kid is sick right now so I'm tied up more than usual this week.

**Comment by javivelasco** [comment]
No problem, no hurry :)
