### ISSUE TITLE
Problems with rendering Dialog component

### ISSUE THREAD

**Issue by hedgehog34** [react-toolbox/react-toolbox#1157]
Hi guys,

I'm having trouble with using a Dialog component. The way I try to implement it is:

```
import { Dialog } from 'react-toolbox/lib/dialog'
import theme from './pages.styles.module.scss'

state = { active: true };

closeConfirmation = () => {
   this.setState({ active: !this.state.active });
};

actions = [
    { label: "OK", onClick: this.closeConfirmation }
];
...
<Dialog actions={this.actions}
              active={this.state.active}
              onEscKeyDown={this.closeConfirmation}
              onOverlayClick={this.closeConfirmation}
              title='Links Sent'
              theme={theme}>
              <p>An email with download links has been sent to your inbox</p>
</Dialog>
```

I noticed that it is in fact, being present in the DOM, but it doesn't generate relevant classes for 'overlay' element and 'backdrop'. Rest of its content seems to be just fine, with all respective CSS classes present in the DOM. What might be the cause?

I should also mention that other components like `<Button />` and `<Input />`, used in the same way, are rendered fine.

I am using version 1.3.4.

**Comment by javivelasco** [comment]
So what you say is that both onverlay and backdrop are present in the DOM but they have no classnames? 😕 Usually this is due to a Webpack misconfiguration or because you are importing the component raw. As you are doing it, the component should come with styles and, if other like Button are working, it is even stranger because there is nothing special about Dialog.

Can't reproduce the issue either. In any case I encourage you to update to the latest beta, but it looks like there is something wrong and not in the library though. Can you share screenshots anyway? Maybe you are overriding styles with that theme prop, can you try out removing it?

**Comment by hedgehog34** [comment]
Thanks for coming responding.

This one is to show rendering of other library components is fine:
![react-toolbox 1](https://cloud.githubusercontent.com/assets/3428656/22145433/3fd2fda2-def9-11e6-964a-1a3193554dd5.PNG)

This shows DOM as seen in the chrome devtools:
![react-toolbox 2](https://cloud.githubusercontent.com/assets/3428656/22145495/880c8c0a-def9-11e6-8965-387f68f6ecef.PNG)

And this one shows DOM nodes associated CSS rules:
![react-toolbox 3](https://cloud.githubusercontent.com/assets/3428656/22145544/bb120bb6-def9-11e6-954f-624d11cebcca.PNG)

I should probably mention that I use `react-toolbox` in a gatsbyjs based project, which is static sites generator. The starter I use is shipped with some default Webpack configuration, so maybe I'll need to dive in there. But really what baffles me most is the fact that part of that component is being generated just fine, while it's outer Overlay part is not

PS. Removing `theme={theme}` prop, removes all classes from all Dialog component.

**Comment by javivelasco** [comment]
It looks like there are no classnames from react-toolbox in any component. If you remove the theme and no classname shows up it's because the internal css require made by react toolbox does not have css modules enabled. It's an usual scenario. Gatsby probably configures webpack to enable css modules for any css require out of node modules. Thats why your custom css require resolves in a module while internal requires doesn't. To make work you can enable css modules for react toolbox by modifying webpack config shipped by default. As an alternative you can also use react toolbox themr or import original css files from your own css with css importa and then require them to inject theme props manually

**Comment by hedgehog34** [comment]
It makes some sense to me, (but it's a bit to digest), and it kinda looks like I already have it implemented, as you mention in your last sentence. Because in order to all my current stuff to work, I had to 

1. pull raw components
2. import original css files from within my own file, (that's why `import theme from './pages.styles.module.scss'`, since gatsby links my own css file, by reckognizing 'modules' in the name of the file
3. then inside of my own css file I have: 
 ```
@import '../node_modules/react-toolbox/lib/input/theme';
@import '../node_modules/react-toolbox/lib/dialog/theme';
@import '../node_modules/react-toolbox/lib/button/theme';
@import '../node_modules/react-toolbox/lib/overlay/theme';
```
... plus all the css overrides which I need to customize my react-toolbox components

Is it what you meant in your last suggestion? If I'm lost badly on this I'll try to play with gatsby default webpack config, and get back to you as soon as I solve this, as I'm little intrigued by this :)

**Comment by javivelasco** [comment]
Exactly, that's exactly it. I guess Gatsby configures (and it's perfectly ok) CSS imports to be resolved without modules enabled. It makes sense because if you require a plugin that bundles some css, the most common scenario is to require the CSS where classnames are the same as used in the Javascript. Take `Codemirror` as an example.

Your solution makes total sense if you import your components raw with the problem that you should import every component along with its dependencies. Being that the case I really encourage you to use [react-toolbox-themr](github.com/react-toolbox/react-toolbox-themr). Here is an usage video with CRA: https://twitter.com/javivelasco/status/810763888690163712

**Comment by ahfarmer** [comment]
For any others that had this issue, I solved it by modifying my Gatsby webpack configuration.

I added this to my `gatsby-node.js` file:

```
// Modify Webpack config to so that react-toolbox CSS files are treated as CSS modules
exports.modifyWebpackConfig = (config) => {
  // Configure CSS loader to NOT take effect for react-toolbox.
  const beforeExclude = get(config, '_loaders.css.config.exclude', []);
  const updatedExclude = flatten([/react-toolbox/].concat([beforeExclude]));
  config.loader('css', {
    exclude: updatedExclude,
  });

  // Add a new loader just for react-toolbox that runs it through CSS modules.
  // Use the same CSS modules configuration as provided by Gatsby for .module.css files.
  const cssModuleLoaders = get(config, '_loaders.cssModules.config.loaders');
  config.loader('cssModulesReactToolbox', {
    test: /react-toolbox.*\.css$/,
    loaders: cssModuleLoaders,
  });

  return config;
};
```

The docs on modifying Gatsby's default Webpack config are here:
https://github.com/gatsbyjs/gatsby#how-to-use-your-own-webpack-loaders

**Comment by livingmine** [comment]
Here is the @ahfarmer 's [solution](https://github.com/react-toolbox/react-toolbox/issues/1157#issuecomment-309308784) migrated for Gatsby v2.

```
/**
 * Implement Gatsby's Node APIs in this file.
 *
 * See: https://www.gatsbyjs.org/docs/node-apis/
 */

exports.onCreateWebpackConfig = ({ actions,  getConfig, rules }) => {
  const config = getConfig();
  
  // Configure CSS loader to NOT take effect for react-toolbox.
  config.module.rules = config.module.rules
    .map(rule => {
      if (rule.oneOf &&
        rule.oneOf.filter(oneOf => oneOf.test.toString().endsWith('.css$/')).length !== 0) {
          return {
            oneOf: rule.oneOf.map(oneOf => {
              const cssRegexString = new RegExp(/\.css$/).toString();
              if (oneOf.test.toString() === cssRegexString) {
                return {
                  ...oneOf,
                  exclude: [/react-toolbox/].concat(oneOf.exclude ? oneOf.exclude : []).reduce( (a, b) => a.concat(b), [])
                }
              }
              return oneOf;
            })
          }
        }
      return rule
    })
    // Add a new loader just for react-toolbox that runs it through CSS modules.
    // Use the same CSS modules configuration as provided by Gatsby for .module.css files.
    .concat({
      ...rules.cssModules(),
      test: /react-toolbox.*\.css$/,
    })
  
  actions.replaceWebpackConfig(config)
};
```
