### ISSUE TITLE
Support defaultValue as a prop for Inputs

### ISSUE THREAD

**Issue by rohannair** [react-toolbox/react-toolbox#1175]
If I set `defaultValue` into an input, the label doesn't properly move to the desired position until I focus on the input.
![Input bug](http://i.imgur.com/8vAiMLe.gif)

**Comment by javivelasco** [comment]
This is happening because the `Input` component does not store the value. You have to do it manually outside the component and pass it in the `value` property. This way the label will be placed at top. Probably the value is displayed because we spread props to the native `input` component.

Does it make sense?

**Comment by rohannair** [comment]
@javivelasco that's if I want to use controlled components. In this case, I do not as it breaks other functionality within my app. `defaultValue` is a prop that is part of React core techniques.

More reading: https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by javivelasco** [comment]
Makes sense. Let's do it
