### ISSUE TITLE
Autocomplete without automatic filtering

### ISSUE THREAD

**Issue by Tudmotu** [react-toolbox/react-toolbox#1176]
I want to disable the automatic filtering of the autocomplete. I tried doing so with inheritance but themr messes up the classes so it's impossible to override the ``.matches()`` function.

My search is performed on the server side, and I wanna use the autocomplete just for displaying the list and selections.

Is there a way to do that currently?
If not, a possible modification to the AC component could be allowing passing a function to the ``suggetionMatch`` prop.

**Comment by javivelasco** [comment]
@Tudmotu Right now it is not possible I think and that's why #1169 exists. The implementation that is coming will allow you to fully customize the autocomplete possibilities, children, and filtering function. If you want to PR the change meanwhile, I'll be happy to merge it!

Nonetheless I'm closing in favor of #1169 :)
