### ISSUE TITLE
Snackbar progress

### ISSUE THREAD

**Issue by olegstepura** [react-toolbox/react-toolbox#1179]
Hi!

I suggest adding a visually decreasing progress bar which allows user to see when snackbar will be closed.
Similar to http://phonon.quarkdev.com/docs/notifications 

![2017-01-26 14_55_21-documentation api _ notifications](https://cloud.githubusercontent.com/assets/534510/22332074/99e37960-e3d7-11e6-85a0-b443a676692b.png)

Not something to have in 2.0, but cool to have someday =)

**Comment by javivelasco** [comment]
I think this shouldn't be done by the library because ideally, the `Snackbar` should allow to place children inside and position them accordingly. This may be a composition or `Snackbar` + `ProgressBar`.

```jsx
<SnackBar>
  <ProgressBar />
</SnackBar>
```

**Comment by olegstepura** [comment]
@javivelasco Well, you are right and wrong. The issue is that we have some attributes in `SnackBar` component  that produce text and a button inside the visible area of `SnackBar` (and it's inside in DOM as well)

Initially my question was about why do we have some attributes like that in `SnackBar` and `AppBar` (maybe more components), not some custom components to be placed as children of those components.
So why do we do this:
```js
<Snackbar
  action='Nice'
  label='A new developer started using React Toolbox'
  onClick={this.handleSnackbarClick}
  ref='snackbar'
  type='accept'
/>
```
and not this:
```js
<Snackbar
  ref='snackbar'
>
  <Label>A new developer started using React Toolbox</Label>
  <ActionButton type='accept' onClick={this.handleSnackbarClick}>Nice</ActionButton>
</Snackbar>
```

Is this case it's composable and it's clear that progress bar must be a child of `SnackBar`

**Comment by javivelasco** [comment]
Basically because at first I wasn't sure about how to classify children. I think we should put children composition before props, but sometimes it's useful. Take the `Button` as an example. It is very common to attach an `icon` to the component so it's *handy* to pass a prop with the icon name. It should be possible to pass the icon as a child though. The Snackbar should behave the same. You can pass common options like an action and a text. But if you want to pass something completely custom, you can just skip those props and pass children. If it's not working like that atm, it should!

**Comment by olegstepura** [comment]
Good to hear! Detailed answer is in #1191
