### ISSUE TITLE
Floating button with href renders icon at the top

### ISSUE THREAD

**Issue by gustavohenke** [react-toolbox/react-toolbox#1192]
This is kinda the same issue as #643.
When a floating button has a href, its icon will render at the top.

Here's the code (tested in [the button docs playground](http://react-toolbox.com/#/components/button)):

```js
<Button icon='add' href='foo' floating />
<Button icon='add'  floating />
```

Here's how it looks like:
![](http://i.imgur.com/9mlKHvP.png)

**Comment by javivelasco** [comment]
The playground has this broken because it should be displayed as inline blocks if I remember well. It is fixed in the dev branch though. If you want you can compare styles for both `dev` and `master` and fix it, I'll be happy to accept a PR.

Anyway, since it's fixed in `dev` I'm going to close this issue!

**Comment by gustavohenke** [comment]
Okay, it's broken for me locally as well, but I assume `dev` means v2 beta :)

**Comment by javivelasco** [comment]
Yeah, latest release is `beta.6`. If you check the roadmap you'd see that *no active development will be done on 1.x on my side*. I'm trying to focus the development of the project to a different approach. That said, beta is usable. Just a beta because of the huge changes coming :)
