### ISSUE TITLE
I'm having problems to apply a custom css to a component

### ISSUE THREAD

**Issue by willianribeiro** [react-toolbox/react-toolbox#1197]
I'm trying to customize Avatar component, but my custom css it's not being applied to it.  It looks like that MyAvatarTheme is an empty object. 
I'm missing anything?

JSX File:
```
import React from 'react';
import Avatar from 'react-toolbox/lib/avatar/Avatar'
import MyAvatarTheme from 'sass/components/_MyAvatar.scss'

class MyAvatar extends React.Component {

    render() {
        let props = this.props;
        let avatarClasses = props.className;

        return (
            <Avatar image={props.imageUrl} icon={props.icon} className={avatarClasses} theme={MyAvatarTheme} />
        );
    }
}
```

SCSS File:
```
.image {
    height: 600px;
}
```

I think I should mention I used [react-toolbox-themr](https://github.com/react-toolbox/react-toolbox-themr)

**Comment by rubenmoya** [comment]
I think the import might be wrong:

`import MyAvatarTheme from 'sass/components/_MyAvatar.scss'`

This has to be a relative path, unless you have an alias in webpack.

**Comment by willianribeiro** [comment]
@rubenmoya, thank you for answer!

And yes, I have an alias for that. Webpack compiles with success, which is a signal it found the file

**Comment by javivelasco** [comment]
If your theme is an empty object the most likely scenario is that the css-loader configuration is wrong. Make sure you have modules enabled by passing the `modules` option to the loader. If you don't do it the CSS is included but the classNames will be global by default and the import resolves to nothing.

Also, for the theming you're applying to work, make sure the component is imported with styles (it is not in your example) as you are overriding just one single property in the css. You can do it by importing from index like `import Avatar from '/components/lib/avatar`;

If your css is still not applied check the selector priority in the devtools. For some cases you will need to assign an extra className to the root element to boost priority and override default styles. Feel free to discuss in the issue but I'm closing since it's not _an issue with the project!_

**Comment by willianribeiro** [comment]
Thank You @javivelasco !
In fact, it was a problem with my webpack config, I wasn't enabling CSS Modules.

I add a specific loader for the reacttoolbox customization css:

```
{
  test: /\.scss$/,
      include: 'src/components/reacttoolbox',
          loaders: [
              'style',
              'css?modules=true&localIdentName=[name]__[local]___[hash:base64:5]&importLoaders=1',
              'postcss',
              'sass'
      ]
}
```
