### ISSUE TITLE
Having problems in integrating react-toolbox

### ISSUE THREAD

**Issue by jsushankprdxn** [react-toolbox/react-toolbox#1198]
I'm trying to integrate react-toolbox but its giving an error for loaders. Am I missing anything?

Previously,
webpack.config.js File:
{
   'test': /\.css$/,
   'loader': ExtractTextPlugin.extract("style-loader", "css-loader?sourceMap")
}

I got an error:
 composition is only allowed when selector is single :local class name not in ".raised", ".raised" is weird.

So for this I made following changes in webpack.config.js File:
{
        'test': /\.css$/,
        'loader': ExtractTextPlugin.extract("style-loader", "style!css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss-loader")
}

But then I got an error like:
Module build failed: ReferenceError: window is not defined

I am new with webpack. Can anyone guide me with this?

Thanks in advance.

**Comment by javivelasco** [comment]
The problem in the first example here is that to integrate react-toolbox with css-modules you have to configure css-loader to use css-modules. This can be done by passing the option `modules` in the querystring which is what you did in the second example.

The configuration looks ok so it's pretty difficult to give you insights. It looks more like a configuration issue so this doesn't belong to the project, I have to close it to avoid noise. 

There are plenty of issues resolved and configuration examples in other closed issues because people usually have troubles making it work with webpack. If you have too much issues with configuration you can always use react-toolbox with [react-toolbox-themr](https://github.com/react-toolbox/react-toolbox-themr).

Good luck :)
