### ISSUE TITLE
ThemeExpander

### ISSUE THREAD

**Issue by alaindresse** [react-toolbox/react-toolbox#1237]
Hi,

I would like to specify a theme to be applied to all the (nested) children of a given component. For instance, a theme to be applied to a card and all the inputs inside that card.

I was thinking about something like 

```jsx
let ExpandedSortable = (props) => {
    let theme = { RTCard: { card: "themed-card" }, RTInput: { input: "themed-input" } };
    return (
        <ThemeExpander theme={theme}>
            <Sortable {...props} />
        </ThemeExpander>
    )
}
```

I tried a "naive" implementation in the [gist here](https://gist.github.com/alaindresse/fd2abc07c6becd35f5bafa72d588767b) which seems to work.

Is this a valid approach ? Is there a better way ?

Thanks,
Alain

**Comment by javivelasco** [comment]
Hi @alaindresse sorry so much for taking this long to answer :(

This scenario had happened multiple times and there is a feature in [react-css-themr](https://github.com/javivelasco/react-css-themr/issues/31) that is actually undocumented, with an open issue if somebody would help. I'm developing here a little bit how does it work:

The main problem is that usually, as in your case, you want to use a theme object to style a component that is nested, but since this component uses a theme object as well, you can't use the same keys. A solution is to just use different classNames for both components. It will work but if you go to the CSS classNames for both components are mixed, not cool.

The solution you are giving would work too and it looks good to me. This works because `ThemeExpander` keeps its own context but I usually want to avoid using context too much. Also, this issue exists inside react-toolbox itself when a component depends on another. An example might be `Autocomplete` where there is a dependency with `Input`.

For those cases, `themr` has a namespace feature. Basically you can pass a `themeNamespace` property to a component decorated with themr, and the function responsible from merging the objects will take only namespaced props prefixed with the value you gave to the property. An example can be found [here](https://github.com/react-toolbox/react-toolbox/blob/9d6ec1eedd320610a5b3fcfaf1ad308ba3d53196/components/layout/Layout.js#L80) and its css [here](https://github.com/react-toolbox/react-toolbox/blob/9d6ec1eedd320610a5b3fcfaf1ad308ba3d53196/components/layout/theme.css#L67). for example:

```css
.autocomplete { /* css code there */ }
.inputFocused { /* css code there */ }
```

Would only pass an object like `{ focused: 'hashedClassName' }` as `theme` property when themeNamespace="input" is used.

Hope it helps! Please feel free to comment, I will not take that longer to respond, sorry about it again
