### ISSUE TITLE
List avatar size

### ISSUE THREAD

**Issue by ideletemyself** [react-toolbox/react-toolbox#1270]
Sorry if this is the wrong place to ask but is it possible to change the avatar size in the list provided with react-toolbox? Would I have to theme or could I just apply some css? if css what would that look like? Any assistance would be appreciated, thanks!

**Comment by devarsh** [comment]
It can be totally done with `react-toolbox` since react-toolbox uses `react-css-themr` which helps you pass your own css to react-components.

Bascially `react-toolbox` exports a raw component with no inline theme, a theme is added much later, so you can import the raw component and then pass that component and your custom theme to the `react-css-themr` which will return a styled component.

**Comment by ideletemyself** [comment]
Awesome, I'm definitely going to give this a try! Thanks for the tips.

**Comment by javivelasco** [comment]
Thank for the answer @devarsh ! :)
