### ISSUE TITLE
Scrollbars showing up on Time Picker when switching between hour and minute view

### ISSUE THREAD

**Issue by danielberndt** [react-toolbox/react-toolbox#1301]
I'm on a Windows machine and Chrome 56. 
When opening the Time Picker and switching between Hour and Minute View, the fade out effect overflows the content of the modal, which leads to scrollbars showing up for a second. The scrollbars disappear as soon as the fade out effect is finished. I assume that some `overflow: hidden` at the correct place might help here!

**Comment by javivelasco** [comment]
I'm afraid this is not possible to do I think. The animation fade needs overflow to be visible around the wrapper in order to make it look like it should. If we add an overflow: hidden property it will not longer be visible. I don't know how does it work in Windows but for Mac there is an option to enable always scrollbars for accessibility reasons. Maybe there is an option there to control it? In any case it looks like it's not solvable by the library with the current state of CSS. If anybody finds a solution please open a PR or leave a comment
