### ISSUE TITLE
Question about the way you import

### ISSUE THREAD

**Issue by c0debreaker** [react-toolbox/react-toolbox#1322]
I'm in your install document now - http://react-toolbox.com/#/install

I'm wondering why your import is like this

```
import { Button } from 'react-toolbox/lib/button';
```

instead of
```
import Button from 'react-toolbox/lib/button';
```

The latter code is known to be more space/size friendly(smaller footprint).
Thank you. Any help would be greatly appreciated!

**Comment by FDiskas** [comment]
And webstorm IDE is suggesting the bad way to import them to. Then publishing to mpm package only the lib directory should be present

**Comment by javivelasco** [comment]
Basically there is a design decision on the library that wasn't very successful. At first react-toolbox worked only if you installed webpack and configure css modules to resolve css imports that were made internally. This was pretty handy but since a lot of people have trouble configuring the whole thing, we decided to extract css so you can inject it using [react-css-themr](http://github.com/javivelasco/react-css-themr). In order to do this we had to export components without requiring css but since we still wanted people with css modules installed to use it the same way we decided to export components:
- From index including styles
- From definition without including styles.

I know this is troublesome and weird and we are going to change it very soon. Meanwhile I'd suggest to use [react-toolbox-themr](http://github.com/react-toolbox/react-toolbox-themr) and to import always from the component itself instead of the index.
