### ISSUE TITLE
Need a way to change the default font of all the components...

### ISSUE THREAD

**Issue by ceres629** [react-toolbox/react-toolbox#1384]
I can figure out to change the font for each individual component, but the documentation does not mention if it is possible to change the default font (or other properties) of all the components.

**Comment by josemigg** [comment]
The website documentation just reference react toolbox V1.3.2. 

If you have V2.0.0 you can check how to do it from this link
https://github.com/react-toolbox/react-toolbox#settings-configuration-variables-in-javascript

If you're using v2 you should check Github documentation instead of the website one. If you're using v1.3.2 I can't help you

**Comment by ceres629** [comment]
Thanks I was looking at the wrong documentation!
