### ISSUE TITLE
Weird Ripple Effect Problem

### ISSUE THREAD

**Issue by Schinti95** [react-toolbox/react-toolbox#1385]
I am experiencing a rather strange problem. Does anyone have an idea how to fix this issue?

![error](https://cloud.githubusercontent.com/assets/8997333/24597029/79f83e6a-1843-11e7-8c81-04c63bc5cc76.gif)

**Comment by javivelasco** [comment]
This is happening because the event used to destroy the ripple is the transition opacity. If you don't apply the corresponding CSS to the ripple element, this event is never triggered and the ripple itself doesn't get removed. This is the issue for sure because as it's shown in your gif, the opacity is not affected at all. Make sure you're including the styles for the ripple component!

**Comment by MayorMonty** [comment]
@javivelasco Where would I include the ripple component? In the project head, or on each component where I want a ripple?

**Comment by javivelasco** [comment]
Styles should be present once if you are using any component that uses a ripple. The js dependency os auto bundled but if you are using components raw and passing the theme objects with themr you have to add the CSS yourself. React toolbox themr handles dependencies internally so if you say you want a button component the ripple css is automatically included. Once included it should work for every component using it :)
