### ISSUE TITLE
Possible conflict between the Table Component and the Input Component

### ISSUE THREAD

**Issue by Jhony-Reyes** [react-toolbox/react-toolbox#1401]
I have an Input component and a Dropdown component that render perfectly, but when I import a table component, it only renders the table component and not the Input and Dropdown components, this is my code:

![image](https://cloud.githubusercontent.com/assets/24459598/24767662/56edeb34-1ac5-11e7-8e21-d5befa800822.png)

Where am I making a mistake? Help me...

**Comment by aguilera51284** [comment]
i have the same problem :(

**Comment by priecint** [comment]
Hey,

seems like the problem is with generated CSS. I didn't look deeply into the PostCSS so I'm not sure how to fix it. But here are some insights I found that could help someone else fix it.

In the image below you can see there are two definitions (with the same name, underlined with blue) generated for the input.

The correct one comes from the [input](https://github.com/react-toolbox/react-toolbox/blob/dev/components/input/theme.css#L5) as expected but the *bad* one probably comes from the [checkbox](https://github.com/react-toolbox/react-toolbox/blob/dev/components/checkbox/theme.css#L31) (because [table imports the checkbox](https://github.com/react-toolbox/react-toolbox/blob/dev/components/table/index.js#L3) so you can make the rows selectable).

In the image you can see my `_collision_hack` class to overcome this (marked with red). This is applied to input like
```
<Input className="_collision_hack" />
```

![obrazek](https://cloud.githubusercontent.com/assets/5900808/25004684/d8dc6d38-2055-11e7-9e5f-ad2fc4c1d1fc.png)

**Comment by aguilera51284** [comment]
i resolve the problem with css-loader, change this in webpack:
```javascript
loader: "css-loader",
  options: {
  modules: true,
  sourceMap: true,
  importLoaders: 2,
  import: true,
  localIdentName: "[name]__[local]--[hash:base64:8]",
  getLocalIdent: (context, localIdentName, localName, options) => {
      return localName+'--'+hashids.encode(Date.now());
    }
  }
},
```
I think this should be changed in the next release :(!

**Comment by Jhony-Reyes** [comment]
Thanks, that solved my problem 👍
