### ISSUE TITLE
Problem with onChange method in Tabs component

### ISSUE THREAD

**Issue by marekrydlewski** [react-toolbox/react-toolbox#143]
Hi,
I have some problems with your Tabs and Tab components - onChange function passes as argument not a index of clicked tab but whole Tabs object.
See:
```
onTabChange(tabs) {
    console.log(tabs);
  }
```
and
```
 <Tabs index = {id} onChange={this.onTabChange.bind(this)}>
```
And I'm getting such a console output:
![image](https://cloud.githubusercontent.com/assets/8159135/11306399/ce15347e-8fb1-11e5-8d32-843ebe305859.png)

For example, when I copy-paste from playground from http://react-toolbox.com/#/components/tabs, it doesn't work because of that :(

Regards

**Comment by elliotatRetireup** [comment]
Have you tried without the binding? Haven't had the chance to look at this yet, but the example on their site doesn't bind the function.

**Comment by soyjavi** [comment]
Hi @marekrydlewski you are overwriting the `onChange`, the default definition is

```
handleHeaderClick = (idx) => {
    if (this.props.onChange) this.props.onChange(idx);
  };
```

Check the `arguments` in your `onTabChange` method.

**Comment by javivelasco** [comment]
@marekrydlewski You are probably using an outdated version of React Toolbox. In the previous implementation we had the state stored inside the component and in that case we used to bind the `Tabs` instance to the callback so you can get the currently selected tab using `instance.getActive()` or something like that.

A couple of weeks ago we deprecated this API and move to stateless components and the new version (the one you see deployed in the playground page) is not storing the currently selected index in the state anymore so the callback gets the `index` instead of the `instance`.

Please, update you Toolbox version to the latest available version, we can re-open if the problem persists.

Thanks!! :)
