### ISSUE TITLE
Table doesn't recognise TableRow child rendered as a separate component

### ISSUE THREAD

**Issue by PSilling** [react-toolbox/react-toolbox#1443]
For example, this doesn't do anything when I try to return cells array into a Table component. Only it's TableHead part get's visibly rendered, while no TableRow is created. Also, this runs without errors:
`var cells = [];
cells.push(<Row />);`

where Row is:
`class Row extends Component {
  render() {
    return(
      <TableRow><TableCell>Ahoj</TableCell></TableRow>
    );
  }
}`

However, this works normally:
`cells.push(<TableRow><TableCell>Ahoj</TableCell></TableRow>);`

**Comment by tobiasandersen** [comment]
That's because the [Table makes sure its rows have the correct typ](https://github.com/react-toolbox/react-toolbox/blob/dev/components/table/Table.js#L13), if not, they won't be rendered. You could create your own Row component, and pass that to the Table factory, basically the same as [this](https://github.com/react-toolbox/react-toolbox/blob/dev/components/table/Table.js#L105).

**Comment by PSilling** [comment]
Thank you for the help. So far I've managed to do this:
`import tableFactory from 'react-toolbox/lib/table/Table.js';
const Table = tableFactory(TableHead, Row);`


But if I do this and try to use <Table> later, I recieve an error: Cannot call a class as a function. So I've tried to use `const Table = new tableFactory(TableHead, Row);` but then I get this error: Cannot read property 'themr' of undefined.


Sorry for the trouble, I'm kinda new to JS so help would be much appreciated.

**Comment by tobiasandersen** [comment]
`const Table = tableFactory(TableHead, Row);` is the correct way to do it. Are `TableHead` and `Row` valid components in your example?

What is the behavior you want to change?

**Comment by baahrens** [comment]
Having the same issue. If I only want to use my own component for rows (which renders react-toolboxs ```TableRow``` as a root, so should be valid) and just the standard ```TableHead```, I should call the tableFactory with ```TableHead```and ```MyRowComponent```, right?

```const Table = tableFactory(TableHead, MyRowComponent)```

Because this also throws the 'Cannot call a class as a function' error. 
What am I missing? Thanks in advance

**Comment by PSilling** [comment]
@tobiasandersen I've tried a lot of things (what @baahrens tried included), but still get the 'Cannot call a class as a function' error.

Right now I'm sitting on this syntax, which is probably wrong doe:
```
const Table = tableFactory(UniversityHead, UniversityRow);

class ContentTable extends Component {
  render() {
    return(
      <Table>
        <UniversityHead />
        <UniversityRow />
      </Table>
    );
  }
}

class UniversityHead extends Component {
  render() {
    return(
      <TableHead>
        <TableCell>Head</TableCell>
      </TableHead>
    );
  }
}

class UniversityRow extends Component {
  render() {
    return(
      <TableRow>
        <TableCell>Row</TableCell>
      </TableRow>
    );
  }
}
```

**Comment by tobiasandersen** [comment]
Below is a minimal example. Note that the table components expect a theme property in order to work (I just passed an empty object now), you could use themr for this.

**Table.js**

```
import React, { Component } from 'react';
import { TableHead, TableRow, TableCell } from 'react-toolbox/lib/table'
import { tableFactory } from 'react-toolbox/lib/table/Table'

class Row extends Component {
  render () {
    const { children, ...props} = this.props
    
    return (
      <TableRow {...props}>{children}</TableRow>
    )
  }
}

const RTTable = tableFactory(TableHead, Row)

class Table extends Component {
  render () {
    const { children, ...props} = this.props
        
    return (
      <div>
        <RTTable {...props}>
          {children}
        </RTTable>
      </div>
    )
  }
}

export { Table, Row as TableRow, TableHead, TableCell }
```


Then use it like this:
```
import { Table, TableRow, TableHead, TableCell } from './Table'

const App = () => ( 
  <Table theme={{}}>
    <TableHead>
      <TableCell>Head Cell</TableCell>
    </TableHead>
    <TableRow>
      <TableCell>Row Cell</TableCell>
     </TableRow>
  </Table>
)

```

See live example here: https://codesandbox.io/s/PNgXBq6Rw

**Comment by baahrens** [comment]
@tobiasandersen Thank you very much, works like a charm! 👍

**Comment by PSilling** [comment]
Yeah, it's working as intended! Thanks, @tobiasandersen!

**Comment by tomchentw** [comment]
@rubenmoya @tobiasandersen I found a special case related to this issue (and #1483) today. In short, the `is-component-of-type` checking by the `tableFactory` won't work as expected under the `react-hot-loader@^3` environment. There's a related issue in the react-hot-loader repo: #304 .

To demonstrate this, simply put a debugger/console.log into the `defaultChecker` funciton in `is-component-of-type.js`:

```js
function defaultChecker(classType, reactElement) {
  console.log(reactElement, classType, reactElement.type === classType )
  console.log(reactElement.type.toString() === classType.toString())
  return reactElement && reactElement.type === classType;
}
```

You'll find out the references check fail but the `toString` checking pass. This is because `reactElement.type` is now a function instance created by `react-proxy` and it overrides `toString` to align with the source component.

A possible solution would change the matching algorithm to `type.name` and `type.toString()` during development. In a production environment, we could safely switch back to checking references. What do you think? I could help a PR of course.

Hope you will find this bug report helpful.

**Comment by tomchentw** [comment]
Because React Hot Loader creates proxied versions of your components, comparing reference types of elements won't work:

https://github.com/gaearon/react-hot-loader/blob/master/docs/Known%20Limitations.md#checking-element-types
