### ISSUE TITLE
Should the sass extends be turned into mixins?

### ISSUE THREAD

**Issue by nathanmarks** [react-toolbox/react-toolbox#150]
This is so that there are no issues making components responsive. Extending inside media queries does not work -- https://github.com/sass/sass/issues/1050

Most people try to stick to mixins because of this issue. They're nightmarish to work with when you want to do media queries.

**Comment by nathanmarks** [comment]
note, this would also mean more re-usable sass, right now the button styles file is not very DRY. The color specific code is repeated over and over, whereas a mixin with a few arguments could reduce the lines of code significantly.

**Comment by javivelasco** [comment]
Didn't knew about this. Spreading usage of mixings also means duplication since classes are not reused but content is dumped for each different class consuming the mixin. That's why I prefer to extend over include.

If there is an issue extending inside media queries, we can move those specific cases to mixins but I would not follow include over extend as a rule. You're right the colors may be extracted into a mixin in the  button component, that is a good use case, but mixin in general is dangerous!

**Comment by nathanmarks** [comment]
I would argue extend is dangerous to save some bytes given that it breaks with media queries. ;)

**Comment by javivelasco** [comment]
But do you think people is going to extend the classnames in react toolbox to write their own media queries? If we write our own being aware of the issue there shouldn't be any problem

**Comment by nathanmarks** [comment]
Good point... I've just had bad experiences myself debugging extend issues in responsive sites.

**Comment by nathanmarks** [comment]
Ok let's close this. We just have to be safe with extends:

www.smashingmagazine.com/2015/05/extending-in-sass-without-mess/

**Comment by javivelasco** [comment]
:+1: !

**Comment by vedran-milic** [comment]
@nathanmarks What happens if I have different color icons on different media queries? How would @extend work there?
