### ISSUE TITLE
checkbox problem 

### ISSUE THREAD

**Issue by taven-liu** [react-toolbox/react-toolbox#1503]
```
import React, {PropTypes} from 'react';

import { Button } from 'react-toolbox/lib/button';

import {Checkbox} from 'react-toolbox/lib/checkbox'
class Test extends React.Component {

  constructor(props){
    super(props)
    this.checkboxChange = this.checkboxChange.bind(this)
    this.state = {
      checked: false
    }
  }  

  oncClickP() {
    alert('div')
  }

  oncClickS(e) {
    alert('button')
    e.stopPropagation();
  }

  checkboxChange(value, e) {
    alert('check')
    this.setState({ checked: true})
  }

  render() {
    return <div>
      <div onClick={this.oncClickP}>
        <Button label="test" onClick={this.oncClickS} primary/>
        <Checkbox  onChange={(value, e) => this.checkboxChange(value, e )} checked={this.state.checked}/>
      </div>
    </div>
  }
}

export default Test;
```
when i click `Button` it can work normal, and when i click `checkbox` the `div`'s click event will be trigger at first.

**Comment by taven-liu** [comment]
the `checkbox` has used `ripple`， `ripple` component have the same problem

**Comment by tobiasandersen** [comment]
That's the expected behaviour (since events bubble upwards). The reason the button doesn't have that behaviour in your example is that you stop the propagation of the onClick event. You can work around it in a few different ways, e.g:

- Wrap your Checkbox in a container that listens for onClick and then just stops the propagation of it.
- In your div's onClick handler, check if the target node was the actual div or not.
