### ISSUE TITLE
Icon font should not be dependent on updating this package.

### ISSUE THREAD

**Issue by nathanmarks** [react-toolbox/react-toolbox#151]
I think this is a pretty important dependency to remove.

I was trying to use a couple of icons just now from the font (via the button component) and they wouldn't work. I realized that you guys are currently defining all of the icon classes manually for the icon props to map to.

This isn't a good idea IMO as it means that whenever google change their icon font, this package is immediately outdated without the user even knowing as it is even calling the google font.

**Comment by javivelasco** [comment]
I agree it's not the best solution because we need to sync changes with Google fonts. What would you suggest to do? The font source can be customized by using a SASS variable but the problem is that the consumer would be responsible for defining the CSS for the font icon. This means we can't bundle a `FontIcon` and also that it can't be used in our internal components.

I agree it can be changed for a better proposal but no one is coming to my mind. Suggestions?

**Comment by nathanmarks** [comment]
I can set it up.

Also, importing URLs from CSS is considered a bad practice.

**Comment by nathanmarks** [comment]
I'd suggest making including the fonts a requirement for the user to decide on how they want to implement (Google, self hosted, etc)

**Comment by javivelasco** [comment]
Ok, I'll wait for that PR :)

BTW check https://github.com/itsmepetrov/classnames-loader

**Comment by nathanmarks** [comment]
Nice, I rewrote everything without binding though already. In a way its nice since it decouples the style names from the component API as it stops you passing props directly into classnames as strings
