### ISSUE TITLE
composition is only allowed when selector is single

### ISSUE THREAD

**Issue by Edisoni** [react-toolbox/react-toolbox#1512]
./~/react-toolbox/lib/button/theme.css
Module build failed: Error: composition is only allowed when selector is single :local class name not in ".raised", ".raised" is weird
    at Array.map (native)

1)Create react app
2)Use react-toolbox

**Comment by sanfilippopablo** [comment]
That means you don't have css modules enabled in your webpack config. Of course, because you are using create-react-app and it doesn't currently support css-modules.

What you have to do is use [react-toolbox-themr](https://github.com/react-toolbox/react-toolbox-themr). Follow the README and you'll be able to use react-toolbox with create-react-app.

**Comment by akhnaz** [comment]
I think the problem is because of incompatible postcss version (css-loader 0.28.4 dependencies is postcss ver 5) and react-toolbox is postcss ver 6.

**Comment by akhnaz** [comment]
i fix my neutrino config to use css modules, and it works now (no need for react-toolbox-themr). 

```    
(neutrino) => neutrino.config.module
  .rule('style')
  .use('css')
  .options({ modules: true })
```
