### ISSUE TITLE
How about use es6 classes, and do not use mixin?

### ISSUE THREAD

**Issue by ustccjw** [react-toolbox/react-toolbox#16]
As https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750 said, we can use composition instead of mixin.

`react-addons-pure-render-mixin` is not necessary，i do not think we should add it to each component. May be we can use immutable.js.

**Comment by javivelasco** [comment]
First of all thanks for your contribution, you're the first one!

I agree about removing `createClass` and use classes instead but I also would like to keep components as functional as possible. At first we wanted to avoid classes and then I thought about moving to [factories](https://medium.com/javascript-scene/baby-s-first-reaction-2103348eccdd) to keep everything stateless and to use stores to hold data. Also DI is a plus... but we should be pragmatic.

In a component library like this, avoiding state may be not the best choice since you are forcing the consumers to implement stores for every data they want to keep in the application and in their components. This collides with the principle of keeping it simple and making as easy as possible to build something with react toolbox. So yes, we are moving to classes for components that keep state but trying to embrace stateless components from React `0.14` (I know you did in your PR!). What I don't want is to use ES7 notation, too experimental for now. Removing the `PureRenderMixin` is ok too, we were using it to be sure we were not messing up state.

If you remove the ES7 notation I'll be happy to accept the PR, great work!!

**Comment by ustccjw** [comment]
In my option, react-toolbox is forward  and experimental(such as  using `css-modules`). So `stage 0` is always ok.

This PR also use `es7.classProperties(stage 0)`, it is also  in React doc(https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html).

**Comment by javivelasco** [comment]
Property initializers are ok and I agree with you, it's highly experimental and maybe it fits. I don't like the double colon to bind the context though, and in many cases React is autobinding so it can be removed. The property initializers look quite elegant... Do you think it's possible to make eslint work with all this new features? It it's possible and @soyjavi agrees we can merge.

Also we need to solve conflicts before merging since we are working hard to release a stable version ASAP!

**Comment by ustccjw** [comment]
`babel-eslint` makes eslint work with all this new features. 
es6 classes bind is a know issue(https://github.com/facebook/react/issues/3509).

**Comment by ustccjw** [comment]
ok, i think we should use：

> ES7 will likely include class property initializers and you'll then be able to specify your method with an arrow function to autobind it:

class Foo extends React.Component {
  render() {
    // ...
  }
  handleChange = (e) => {
    // ...
  }
}

**Comment by javivelasco** [comment]
Ok, let's go with ES7 features. Since I was used to `createClass` I thought there was autobinding for classes notation too. Actually, I'd prefer double colon notation instead of including a new dependency. If also eslint is configurable with `babel-eslint` we can go for it.

I'm going to keep working in a few hours. You can either go back to double colon or just use `bind` and I will merge. +1

**Comment by ustccjw** [comment]
@javivelasco there is many event handler, it's difficult to turn all place to notation.
` autobind-decorator ` is well, do not reject dependency. We can replace it when there is a new solution.

**Comment by javivelasco** [comment]
I know it's a common pattern, I wanted to have as few dependencies as possible. It's acceptable since it's just a development dependency. I need @soyjavi to agree too.

**Comment by javivelasco** [comment]
@ustccjw I've tested you're branch https://github.com/react-toolbox/react-toolbox/tree/ideal-react-dev and fixed linter errors. There are some components that are not working, like the autocomplete. The reason is that `stage 0` includes new [ES7 comprehensions](http://babeljs.io/docs/advanced/transformers/other/comprehensions/). 

I've never used `stage 0` and although I like some of the proposals (like class properties) but I'm not sure about the return of jumping into cutting edge features. They may change soon forcing us to change the whole codebase. Also, we were using the stable proposal for comprehensions and probably it would be easier to find contributors if we use a more widespread accepted spec, don't you think so?

 For all of this, although I understand your point, I would like to avoid `stage 0` for now so we can be more focused on creating good components rather than being worried about cutting edge language features. Sure we are going to switch to classes and I wanna do it **now**, but let's keep stage 2 even being less pretty. We can either move from the branch I've created from yours or change your branch of avoid linter errors moving to `stage 2`. What do you prefer? Another option would be to add just decorators and/or class properties to stage 2 keeping the rest of experimental features out of the project. How does it sound?

**Comment by javivelasco** [comment]
We can discuss further if you reach me through discord

**Comment by soyjavi** [comment]
We need use ES6 (stable) ... IMHO is too soon for use ES7. I prefer improve our components, or create new ones.

**Comment by ustccjw** [comment]
.babelrc like this, is ok?

     {
      "stage": 2,
      "optional": ["es7.decorators", "es7.classProperties"],
      "loose": "all"
    }

**Comment by ustccjw** [comment]
@javivelasco @soyjavi 

I would like to prefer to merge the branch you have created.

I think ES7 can be used. Like you have found autocomplete do not work because of `ES7 comprehensions`. So we can avoid these(by open stage 0) when `ES7 comprehensions` will become standard. Improve components is important, good features can help us to improve components.
