### ISSUE TITLE
Using the toolbox without webpack

### ISSUE THREAD

**Issue by int13h** [react-toolbox/react-toolbox#168]
The install instructions on the website say: "If you want to still use CSS Modules but avoiding Babel and SASS you can require from react-toolbox/lib"

Is this process expanded on anywhere? Importing any of the components just throws a bunch of style errors.

**Comment by javivelasco** [comment]
Hi! We need to update the documentation because although that was the first approach, we are dumping into `lib` the `js` but along with `scss`. This means that to load the styles you need CSS Modules and SASS loader. Actually it makes not too much sense to use the library out of css modules. If you do, you'd need to get the whole CSS with a predefined theme and override constantly.

We plan to do some integration with browserify. Actually it *is* posible to use toolbox out of webpack but you need to clone the repo and generate your own distribution. 

Sorry :(

**Comment by int13h** [comment]
Thanks!

**Comment by int13h** [comment]
I am actually going to leave this open for now; easier to track.

**Comment by smazurov** [comment]
this is also a problem for testing with mocha (without karma/webpack). I'm trying to compile with `node-sass` and `css-modules-require-hook` but `@import` paths are wrong (since `sass-loader` uses `~` for `moduleDirectories`)

**Comment by smazurov** [comment]
I was able to fix it with a mocha loader that looks like this:

```js
// in app/tests/loader.js
import hook from 'css-modules-require-hook';
import sass from 'node-sass';
import path from 'path';

const nodeModules = path.resolve(__dirname, '../node_modules');

hook({
  extensions: ['.scss'],
  preprocessCss: (data, file) => sass.renderSync({file, data, includePaths: [nodeModules]}).css
});
```

I also modified `webpack.config.js` to allow me to import without `~` (this is better for my workflow anyway):

```js
module: {
  sassLoader: {
    includePaths: [path.resolve(__dirname, './node_modules')]
  }
}
```

Alternatively, you can modify the `preprocessCss` to remove `~` from `file` before passing it to `node-sass`

**Comment by javivelasco** [comment]
Great, thanks for the info @smazurov 
We should add this to the Readme, don't you think? Feel free to open a PR!

**Comment by smazurov** [comment]
since its only used to run automatic tests, I cannot vouch its working 100% correctly. I might have a chance to test class name generation and such in the next few days, but its probably ideal to throw it a project that does server rendering or something and I don't have one of those handy. More of starting point than a "here's the best practice"

**Comment by javivelasco** [comment]
Great, I would like to set up a boilerplate with server side rendering but I don't have too much time these days. I'll try to get something done during the weekend

**Comment by praneybehl** [comment]
@javivelasco any success with the boilerplate?

**Comment by javivelasco** [comment]
I've been quite busy these days and didn't have time to try yet. I hope to do it soon!

**Comment by acornejo** [comment]
I am curious about this too.

Given that the recommended workflow is to have sass/css loaders AND babel installed together with webpack, then wouldn't it make more sense to recommend to load the components out of `component//*` instead of `lib/*`?

That would allow more chances of compression/optimization. It seems to me that loading from `lib/*` will have the unfortunate side-effect of forcing webpack/babel to generate all the javascript boilerplate for EACH individual component, instead of just once for the bundle.js of the app.

Or am I missing something? Not sure if I should file this as a separate issue, wanted to ask first.

**Comment by cinic** [comment]
@javivelasco
Need i to clone this repo for using without Webpack, but with Browserify (react-rails + browserify-rails)?

**Comment by javivelasco** [comment]
It would be great if you can try a configuration @cinic I don't have too much experience with browserify but I suppose it's possible to get it working

**Comment by javivelasco** [comment]
Btw @praneybehl I have a boilerplate with server side rendering, just need to create the repo, I'll try to do it soon.

@acornejo I did not find an easy way to import avoiding the `lib`. Anyway it's the recommended way to do the imports because otherwise you are importing and bundling all the components

**Comment by praneybehl** [comment]
Thank mate :+1:

**Comment by wzup** [comment]
@javivelasco 
Have you created a repo server side rendering example? Could you pls provide a link?

**Comment by javivelasco** [comment]
There is no repository with a server side example but it shouldn't be any different than with other package that uses CSS Modules. Just make sure you included a register hook or similar to provide support when requiring a CSS file in the server.

**Comment by wzup** [comment]
@javivelasco Why do I need to require `css` file in the server? Could you please show some example code how you do it?

**Comment by ofzza** [comment]
Having hit this same problem with server-side rendering; and not wanting to use webpack on the server; and ```require(style)``` being a pain for gulp/babel - I ended up writing a module that takes react-toolbox as a dependency and compiles it so that it can be used on the server without any extra compilation steps:
https://github.com/ofzza/react-toolbox-build4server

There is also a really, really simple server-side rendering example for it available here:
https://github.com/ofzza/react-toolbox-build4server-example

You can just install the module and require pre-compiled components from it, which will work both on the server and the client, or you can integrate the module's gulpfile into your own and run it's tasks as part of your own build procedure (see readme.md for details) which gives some extra flexibility in choosing react-toolbox version you want to use and in overriding .scss configs for theming purposes.

This seems to work fine in my own isomorphic app and the hope is it ends up helping others as well ...

**Comment by javivelasco** [comment]
Actually it's pretty easy. If you want to SSR your app you need to required it and of course for react toolbox your app requires css. You need a way to require ES6 in the first place, a common approach is to use a require hook to do so. You just require the hook and from that point it's possible to require ES6. There is a [similar approach](https://github.com/css-modules/css-modules-require-hook) for CSS modules. With that it should be enough and your requires can be resolved in the server.

I recently had the problem that working in the backend was painful because a reload takes too long with all those requires. I solved it by using a proxy server for the frontend APP for development. I will try to upload an example with SSR as soon as I release a new version of react-toolbox with react-css-themr.

**Comment by dcousens** [comment]
Is this possible?  A preliminary test with `sassify`, `browserify` and `babel` didn't work out for me,  but perhaps I'm missing something?

**Comment by javivelasco** [comment]
Try #666 Getting rid of sass makes easier the setup since you only need postcss. Remember you need to use postcss-modules or something similar to enable css modules for react-toolbox requires. Apart from that, as long as you can require and resolve css files, it should work

**Comment by dcousens** [comment]
@javivelasco do you have any examples?
My attempt so far:

```
browserify -t [ browserify-postcss --plugin [ postcss-import --path './node_modules/react-toolbox/components' ] --plugin postcss-next ] -t babelify test.js
```

Any ideas?
At this point I'm running out of time and probably have to move on to using a different module,  too much time sunk.  Would love to be able to use the toolbox though :)

**Comment by javivelasco** [comment]
@dcousens Sorry I'm not familiar with Browserify and that's why there is no example yet. I see you've been trying out the CSS branch? It should work without a doubt but i don't know the internals to help, sorry :(

**Comment by javivelasco** [comment]
Now it's actually possible to do it by generating themed components with a script. We are bundling a npm script to help you out in #666 but it is indeed supported with scripting and react-css-themr

**Comment by janppires** [comment]
@smazurov do you have any clean way of support `@import '~react-toolbox/.....'` than doing something like bellow inside of `preprocessCss `?

```
data = data.replace('@import \'~', '@import \'');
```

thanks!
