### ISSUE TITLE
Use Tooltip component for truncated text

### ISSUE THREAD

**Issue by codecalypso** [react-toolbox/react-toolbox#1700]
Is there a way to render the tooltip solely for truncated text? Im interested in knowing if that is possible.

**Comment by sahilamoli** [comment]
There isn't a standard way to know if a rendered element is truncated and it really shouldn't be built into the tooltip component. You can do some calculations to figure out if a rendered element is truncated and only then render the Tooltip component or even just add a forced hidden class whenever the calculation suggests that the element isn't truncated.

I put up a quick gist to show you how you can do the calculation using JS (only tested out a simple case in chrome):
https://gist.github.com/sahilamoli/859d7853c137b905dc4dc950186d3a22
And here is a working jsfiddle to show you the calculation in action:
https://jsfiddle.net/Ld2pjabu/4/

Feel free to use that code if it helps but know that you probably want to recalculate on window.resize (debounced) as well since something that isn't truncated to start could become truncated.

Hope this helps. If you were asking something completely different, please provide a bit more context.

**Comment by guacamoli** [comment]
@codecalypso, did this solve your issue?
