### ISSUE TITLE
Touch ripple on Button prevents onClick handler

### ISSUE THREAD

**Issue by Karabur** [react-toolbox/react-toolbox#173]
if there is onClick handler, it will not be triggered anymore, since handleTouchStart blocking the event.
Now it is required to add both onClick and onTouchStart to make it work on mobile.

**Comment by javivelasco** [comment]
Wow, so sorry. Actually we are getting rid of the `handleTouchStart` for the next version. It's not giving too much value and it's creating problems. For example, you can't scroll on mobile since it stops the event propagation. For users focusing on mobile who need an immediate response from the ripple is no big deal to create a component wrapper to do so.

Fixing soon, thanks for reporting!

**Comment by alltom** [comment]
I just updated and noticed everything stopped working on mobile. Could you explain what you mean by "For users focusing on mobile who need an immediate response from the ripple is no big deal to create a component wrapper to do so."? Or not, if it's easier for me to wait for a fix. :)

**Comment by javivelasco** [comment]
Yeah. The `Ripple` component was stopping the events as they were used to track the position of the event. A first approach was to make the button able to respond with a ripple `onTouchStart` but since it was stopping the event, when you try to scroll on mobile with an initial tap in the button, this first tap is prevented and you can't scroll. That's why we removed it from now.

The solution from React Toolbox POV is to avoid stopping the event which we need to look into deeper. If you want to use the ripple `onTouchStart` you can still create a wrapper component for the `Button` and add `onTouchStart` callback starting the ripple yourself.

**Comment by Karabur** [comment]
Is it fixed in latest build, or just closed and anyone should create wrappers to implement that workaround? I suppose latter as there is commit attached. 

Why not just remove stop propagation, and handle double ripples(I see this is the only problem in this case) gracefully, disable mouse event for example in case of touch fired or any other way.

**Comment by alltom** [comment]
It may have been fixed by d0e4135d0b34e0e491cdbcb6fe01f7628e101dac, which went into the 0.13.0 release at the same time this issue was closed.

**Comment by alltom** [comment]
Yup, my site is fixed at 0.13.1.

**Comment by javivelasco** [comment]
Great!
