### ISSUE TITLE
OFFLINE www.react-toolbox.com

### ISSUE THREAD

**Issue by FDiskas** [react-toolbox/react-toolbox#1742]
![https://i.imgur.com/FlRAuBi.png](https://i.imgur.com/FlRAuBi.png)

**Comment by blakeperdue** [comment]
Yeah, the site being down and the lack of commits in October make me afraid this repo is losing momentum... I hope not because it's an awesome resource!!

**Comment by nirus** [comment]
Please don't make us move out of the framework. I am already in search of other solutions.

**Comment by oliviertassinari** [comment]
@chadfawcett host a temporary version on https://peddler-jam-26368.netlify.com.

**Comment by guacamoli** [comment]
Has anyone tried contacting @javivelasco directly via email/twitter? Wonder if he's still planning on maintaining this.

**Comment by pablolmiranda** [comment]
The react-toolbox.com domain is blocked inside Netflix and this is the feedback from our DNS team at Netflix:
"Our research team got back to us about the domain you sent us and stated that the domain is being blocked currently due to it's IP address (198.54.117[.]212).
Currently 198.54.117[.]212 is hosting more than 1000 malicious domains and will be remaining blocked for now.
If and when react-toolbox[.]com changes its hosting IP, it will no longer be blocked.
For more details on why we block these types of IP addresses, please check out our block entries regarding bad neighbours located at https://blog.opendns.com/2014/08/21/websites-and-bad-neighbors/."

Do you guys need any help with this?

**Comment by FDiskas** [comment]
why not to use the github pages for this? :meat_on_bone:

**Comment by kmannislands** [comment]
@pablolmiranda well the domain expired, so dns does actually point to a bad host. Seems like the only help they could use is with renewing the domain, which I'm guessing is financially constrained.

Until then everyone should just browse the cached version: https://web.archive.org/web/20171020084703/https://react-toolbox.com#/

**Comment by dan-kwiat** [comment]
I get the impression Javi is working on a big update, extracting style-agnostic components & HOCs separately and maybe removing css-modules in favour of styled-components.  He talks about it here: https://www.youtube.com/watch?v=uFkyn9cFkO8

**Comment by javivelasco** [comment]
Hi guys, an update:

Last two weeks were super crazy. I had a shit load of work to do not only for my current work but for some other side projects and currently running. I'm working on a different approach that I'm pushing very soon as @dan-kwiat told in the previous comment. 

The domain issue is not actually related. Currently @soyjavi owns `react-toolbox.com` and he has been completely unreachable to renew the domain. I didn't wanted to change the domain name at first but I have no other choice. From now own you can access www.react-toolbox.io.

Thank you for your patience guys
