### ISSUE TITLE
The domain http://www.react-toolbox.com/ has expired

### ISSUE THREAD

**Issue by tatethurston** [react-toolbox/react-toolbox#1746]
This has happened again.

https://github.com/react-toolbox/react-toolbox/issues/921

**Comment by mlcohen** [comment]
Same. I flushed my macOS's DNS cache just to make sure but no dice. <sad panda>

![screen shot 2017-11-06 at 3 02 38 pm](https://user-images.githubusercontent.com/100445/32468640-009f1432-c304-11e7-8eba-147f1b586a3c.png)

**Comment by jmar777** [comment]
In the meantime, if you're looking for some documentation, please note that you can browse the [`components`](https://github.com/react-toolbox/react-toolbox/tree/dev/components/input) source folder for individual components, and each component (that I've checked) is well documented with it's own Readme file (e.g., [`Input`](https://github.com/react-toolbox/react-toolbox/tree/dev/components/input).

**Comment by mkMoSs** [comment]
Is this react-toolbox being abandoned? I'm about to start a big project based on this and all I'm encountering is major bugs and components not working as they should. The repo hasn't been updated for months, the domain has expired for days now. I read good things about react-toolbox vs material-ui, however it seems stale. Any info?

**Comment by MrEfrem** [comment]
Yes, It's very weird situation. I also use it in the big project and I would not like rewrite all.

**Comment by miguel-orange** [comment]
https://github.com/react-toolbox/react-toolbox/issues/1742#issuecomment-342095270

**Comment by jasonmorita** [comment]
Why not just put up a GitHub page? It's freeeeee!

**Comment by luiz-simples** [comment]
Why not just put up a Heroku page? It's freeeeee!

**Comment by kmannislands** [comment]
^ everyone's talking about switching hosts (heroku, gh pages) but the issue is that the domain expired, so the host is actually irrelevant. Perhaps the domain has become expensive, it is very keyword-ey.

In fact, it was hosted on Github Pages already. DNS seems to have pointed to http://192.30.252.153/ until 9 days ago or so when it appears the domain expired.

Someone should just @javivelasco on twitter, seems he's still active there.

**Comment by jmar777** [comment]
I reached out to him on Twitter on the 8th, but haven't heard back yet. He's still active, so presumably he's at least ok. :)

**Comment by jasonmorita** [comment]
https://react-toolbox.github.io/ is what I was suggesting. No need for the domain.

**Comment by javivelasco** [comment]
Sorry guys. It's now going to happen again since I've just switched to www.react-toolbox.io and now I own it. @soyjavi owns react-toolbox.com and it was impossible to reach him/make him renew the domain. I didn't wanted to change it buy I had no other choice. From now on you can use www.react-toolbox.io.

Again, sorry for the trouble.

**Comment by mlcohen** [comment]
As an FYI for anyone who still curious about whether react-toolbox is still being worked on, the answer is yes. I reached out to @javivelasco over Twitter and he mentioned that he's been super busy with other stuff but he's hoping to get back to dedicating more time to working on react-toolbox. So that's good news 👍🏼

**Comment by mkMoSs** [comment]
Thats good news, but well unfortunatelly, even though react-toolbox looked promising, I had to choose the "other" most popular Material framework for React :/

**Comment by oliviertassinari** [comment]
@mlcohen Great! I hope this project will keep moving forward. Alternatives are good for the ecosystem. Competition drives us further and it's room for more experimentations.
