### ISSUE TITLE
I can't type into input-field on mobiles

### ISSUE THREAD

**Issue by markolofsen** [react-toolbox/react-toolbox#1754]
I can't type into input-field on mobiles. When I type nothing happens, but focus still set. Input-field is connected with the state and on PC everything ok.
I'm confused ) 

**template**
```
import Input from '../../../components/input';

const handleSearchInput = (value, ev) => {
		onSearchInput(value)
	};

<Input type="text" name="normal" value={stateSettings.navbar.searchValue} placeholder="Search" className={style.appSearchInput} onChange={handleSearchInput}/>

export default withRouter(connect((state, ownProps) => ({stateSettings: state.settings}), dispatch => ({
	onSearchInput: (payload) => {
		dispatch({type: 'NAVBAR_INPUT', payload})
	}
}))(SearchForm));
```

**Reducer:**
```
const initialState = {
	navbar: {
		searchValue: ''
	}
}
export default function settings(state = initialState, action) {
	if (action.type === 'NAVBAR_INPUT') {
		state.navbar.searchValue = action.payload
		return {
			...state
		}
	}
}
```

State `stateSettings.navbar.searchValue` are connected.

**Comment by rubenmoya** [comment]
The only thing I can see is that you're mutating the state in `state.navbar.searchValue = action.payload`, probably since you're mutating the state, when you return the new object it "doesn't change" so redux does nothing.

My advice is to debug it slowly, first see if `handleSearchInput` is called, then `onSearchInput`, and then debug the reducer to see if it's doing what you want it to do.

**Comment by markolofsen** [comment]
@rubenmoya I did it already, Thanks!
