### ISSUE TITLE
Customize a particular row in Table.

### ISSUE THREAD

**Issue by vikaskyadav** [react-toolbox/react-toolbox#1770]
I would like to customize just a single row based upon some conditions. How this can be done in this. I am using version 1.2.5

**Comment by 3af** [comment]
Hi,

what customization you have in mind?

Since this is open source you can check the source code of [Table in v1.2.5](https://github.com/react-toolbox/react-toolbox/tree/1.2.5/components/table) and see for yourself what customizations it allows. Documentation doesn't mention any sort of customization so let's dig into the source code.

If you check the [render method of Table component](https://github.com/react-toolbox/react-toolbox/blob/1.2.5/components/table/Table.js#L88) you can see that it iterates over `source` props and creates TableRow without any conditional logic.

When you check [render method of TableRow](https://github.com/react-toolbox/react-toolbox/blob/1.2.5/components/table/TableRow.js#L101) you can see that it provides some ways how to customize the rendered row.

Ultimate solution is to migrate to the latest version [2.0.0-beta.12](https://github.com/react-toolbox/react-toolbox/tree/dev/components/table) where you have more control of the rows and cells.
