### ISSUE TITLE
focus on first focusable element in dialog

### ISSUE THREAD

**Issue by jimmywarting** [react-toolbox/react-toolbox#1786]
like the native dialog element could you make the first focusable element in the dialog get the focus for better accessibility?

Bonus point if you restore focus to last focused element when dialog closes

**Comment by 3af** [comment]
Hi,

you can do the first part yourself with [autofocus attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autofocus).

This works for me in playground (notice the spelling - `autoFocus` - it's important):
```
<Dialog
  actions={this.actions}
  active={this.state.active}
  onEscKeyDown={this.handleToggle}
  onOverlayClick={this.handleToggle}
  title='My awesome dialog'
>
   <Input autoFocus />
   <p>Here you can add arbitrary content. Components like Pickers are using dialogs now.</p>
</Dialog>
```

I would say the second part is out of scope of this library because [you have to store previously focused element](https://stackoverflow.com/questions/3639908/retrieving-previously-focused-element) and RT doesn't have such storage. But that's just my opinion.

**Comment by jimmywarting** [comment]
> you can do the first part yourself with autofocus attribute.

I know, the point of this issue was not needing to do that and make it behave more like the native html dialog works

**Comment by rubenmoya** [comment]
Hi! There will be people who don't want to autofocus it, so making it by default will lead us to add some option to not to do autofocus it, I don't think it's that hard/painful to add an `autoFocus` and it's pretty flexible, we could revisit this in the future if more people ask for this feature.

**Comment by jimmywarting** [comment]
I doubt there is someone that wouldn't want that.
this feature would only applies to dialog that don't have any autofocus attribute in them
