### ISSUE TITLE
Icon sizing prop

### ISSUE THREAD

**Issue by wrench7** [react-toolbox/react-toolbox#181]
I'm wondering if a prop for components that use FontIcons (Button, IconButton, FontIcon, ListItem, MenuItem) can be added so that the sizing guidelines found here (http://google.github.io/material-design-icons/) can be used at the lower levels.

The prop could either take a string ('sm', 'md', 'lg', 'xl') or just allow the class that Google recommends to be passed through ('md-18', 'md-24', 'md-36', 'md-48') onto the span that has the 'material-icons' class on it.

Interested to see how this feature could be added :-)

**Comment by javivelasco** [comment]
Since we are using directly material design icons under the covers, you can give those classes directly [through the `className` property](https://github.com/react-toolbox/react-toolbox/blob/master/components/font_icon/FontIcon.jsx#L5).

So you can do: `<FontIcon className='md-36' value='favorite' />` and it should work as long as the styles mentioned in the document are present. I guess they are not present by default because the `class` output in the documentation using that code is the expected but there is no matching class.

Does this solve your issue?? 
Thanks! :)

**Comment by wrench7** [comment]
Wow, you're too quick with the responses! :D

Unfortunately your solution doesn't work in the instances I was mentioning. Because the FontIcon is buried within say the Button or ListItem components, the class isn't passed down to the correct level.

I've added the styles mentioned in the Google document, so they're ready to go - but for components that use a FontIcon under the hood we're not able to modify the size of the icon easily.

Hope that helps to explain a bit more.

**Comment by javivelasco** [comment]
If you are trying to apply classes in Icons that are used inside other components probably it is not working because the selector needs to me more specific. Anyway, the buttons we have have the sizes from the spec and you shouldn't change it.

There should be no problem about using them directly on the `FontIcon` component. Just make sure the final className in the DOM is the one you need. Toolbox adds the default for you. I've tried `<FontIcon className='md-36' value='favorite' />` and it worked with no issue. Maybe you are giving the class from a CSS Module which is generating a hashed class instead of the global one?

Thanks!

**Comment by wrench7** [comment]
My point was that if you needed to change icon sizes in sub-components, there currently is no ability to do so. If they're to spec, then I guess that's ok - but having seen some interesting UX in my time, having the ability to mutate the styles is a concern of mine.

As for the second point, I'm aware that the FontIcon is able to use the ```md-``` classes (provided they've been added to a stylesheet). So for now I'll have to use them in my own components I guess should I need to make the icons bigger (or smaller) than you've specified.

As an aside, the reason this came about is because the icon size in the IconButton is 2rem by default which overrides the default of 24px (which is actually what I was after in this instance).

**Comment by javivelasco** [comment]
@wrench7 If we would carry properties to give classNames to subcomponents, the API for a complex component would had too many properties. If you want to style a React Toolbox component you can also target in your css `.myItem [data-react-toolbox="component"]` being `myItem` a class given to the MenuItem component for example.

If you need more information you can reach me through Discord.
The `$unit` thing is already reported and we need to add the `!default` flag so you can override it with say `10px` for example

Thanks!

**Comment by wrench7** [comment]
Yeah, I figured things would start to get a bit complicated which is why I wasn't sure that this would be an approach worth taking.

There's definitely *lots* of CSS hacks around the problem, I guess I was just trying to avoid them and use a prescribed API to modify a components underlying style. I'll close for now.
