### ISSUE TITLE
What is the current status with react-toolbox?

### ISSUE THREAD

**Issue by mlcohen** [react-toolbox/react-toolbox#1813]
Hi --

I wanted to know what the current status of react-toolbox is simply because activity appears to have come to a complete stop. I certainly recognize that the core maintainers are very busy and keeping an open source project alive and up to date is a lot of hard work; however, many of us who have fully adopted react-toolbox v1 for big projects, like myself, are hitting a critical point about whether or not to stick with using react-toolbox.

Ideally I'd like to make use of React v16 (R16), but neither react-toolbox v1 or v2 are compatible with R16. Some in the community have offered PRs to help make v1 and v2 work with R16 but so far those PRs have not been merged. This is troubling. Even more, work on v2 appears to have been supplanted by work on react-toolbox v3 (https://github.com/react-toolbox/react-toolbox/pull/1698#issuecomment-332967868). This while v2 is still in beta.

It would be great if the someone on the core team could communicate honestly about the future of react-toolbox. If there is simply not enough time and energy to work on this, that's fine; at least those of us who are making extensive use of react-toolbox will know and can plan accordingly. If, however, there are still plans to keep this project going, communicating what is going on would very much be welcome.

Again, I do recognize how much time effort there is in maintaining an OS project. This is in no way a slam against the core maintainers. I'm just seeking honest, timely communication so that those of use who use react-toolbox can make plans about what to do next.

**Comment by rubenmoya** [comment]
Hi @mlcohen!

Right now there is no active development in `v1`, the only changes will be done by contributions, I know there is a PR open to update to React v16, but it has some changes related to `react-themr` and I don't really know what impact it could have, so I'm waiting for some feedback from Javi to merge it. I'll try to push him a little bit this week but since he just joined Zeit I'm guessing he is pretty busy.

About the `v2` it's true that it's still in beta, but we've realised we were doing the same mistakes as in `v1` with theming, it was really hard to override it, and there are a lot of issues related to that, so we won't be doing any new development in `v2` besides bug fixing, I've been merging a lot of PRs and labeling issues, but last couple of weeks I've been pretty busy, I hope I can get back to it this weekend. The update to React v16 is not done basically because we thought we were going to start using the `agnostic-typescript` branch (with lerna) sooner, but it didn't happen, so I'll try to have a look at the PR and merge it this week.

The `v3` is still in development, but, since 99% of the development is made by Javi and he's really busy it's hard to get work done, I'll try to get more involved on it, but I can't promise anything.

I hope this solves some of your doubts, my advice is to stick with whatever version you're using, and then migrate to `v3` as soon as it's ready, I'll try to give more information about when it will be ready as soon as I can :)

**Comment by mlcohen** [comment]
Thanks for the quick response, @rubenmoya! So `v3` is where things are heading. Okay, that's good to know. It would be helpful if, say, @javivelasco where able to chime in or writeup a communique about what his plans are regarding `v3` and when (roughly) it will be ready for use. I only found out about `v3` because I was searching around about `v2`.

Unfortunately I have to admit that things are still kind of murky for me. I'd really like to stick with react-toolbox since it is a great Material UI component library, but the longer the project remains seemingly stagnant the harder it is to stick with it. In any case, I'll keep a close eye on `v3` development and see how things play out over the next few weeks.

**Comment by rubenmoya** [comment]
I completely understand that it's hard to stick with it when the future is unclear.

I'll try to have both, `v1` and `v2` with React 16 this week, and also talk to Javi to push the `v3` development.

Thank you for your message and let's see how it goes :)

**Comment by jmar777** [comment]
Hmm. Well, I _just_ upgraded our codebase to v2. Am I better reverting back to v1 and waiting for v3, or what's the recommended version at this point?

**Comment by mlcohen** [comment]
@jmar777 Looks like @rubenmoya has a PR ready to go https://github.com/react-toolbox/react-toolbox/pull/1814 😃

**Comment by jmar777** [comment]
@mlcohen Ha, yeah - I'm excited about that one! I was more trying to determine which branch was considered more "stable" at this point, though.

I'm assuming that's `v2`, but seeing as it hasn't made it out of beta yet, I wasn't entirely sure where things stood now. I guess @rubenmoya indicated that `v2` would still get bug fixes, so that's probably good enough for my needs, at least.
