### ISSUE TITLE
Input pattern prop

### ISSUE THREAD

**Issue by darklilium** [react-toolbox/react-toolbox#1906]
Hello,

Im wondering how to use the pattern property from input in html to Input comp in this lib.
I setted up a pattern but seems like the pattern prop in the lib is not working.

I want to allow the user only type numbers and letters , not special chars like #,$,%,&,etc.
So i did this:
```<Input pattern="^[a-zA-Z0-9]*$" />```

Thanks

**Comment by theajr** [comment]
@darklilium 

#### This is not specific to this library.

`pattern` attribute won't restrict user while typing the value, it is used to validate the input filed value before submitting the `form`.
`type` attribute will restrict the user input. 
Example: if you mention `type=number`, user can only enter numbers. But for your use case you can't use `type` attribute. 

So you can write a custom wrapper input component like below so that user can only enter according to pattern.

>CustomInput.jsx
```javascript
import React from "react";
import Input from 'react-toolbox/lib/input';

class CustomInput extends React.PureComponent {
  constructor(props) {
    super(props);
    const { value, defaultValue } = this.props;
    this.state = {
      value: value || defaultValue || ""
    };
    this.onChange = this.onChange.bind(this);
  }
  
  onChange(value) {
    const { pattern, onChange } = this.props;
    if (pattern) {
      const reg = new RegExp(pattern);
      if (reg.test(value)) {
        this.setState({
          value
        });
      }
    }
    if (onChange) {
      onChange.call(arguments); // To call actual onChange passed CustomInput
    }
  }
  render() {
    const {
      props,
      state: { value }
    } = this;
    return <Input {...props} value={value} onChange={this.onChange}></Input>;
  }
}
```

>app.jsx

```javascript
<CustomInput pattern="^[a-zA-Z0-9]*$" />
```

**Comment by theajr** [comment]
@darklilium you can close this issue if you are happy with the provided explanation and code.
