### ISSUE TITLE
Improve global accessibility

### ISSUE THREAD

**Issue by jgoux** [react-toolbox/react-toolbox#193]
Hello,

I noticed a lot a components aren't accessible.
For example :  
- Unable to navigate within the `Dropdown` with the keyboard
- The `Checkbox` component cannot be checked by pressing enter or the space bar

It's a crucial point IMHO.

Also, adding semantics tags (WAI-ARIA) to all the components would be great too. :+1: 

We can take example on [angular-material](https://material.angularjs.org/latest/) or [material-design-lite](http://www.getmdl.io/components/) which are both fully accessible.

**Comment by nathanmarks** [comment]
Perhaps starting to write some tests and outlining these specifications that way is the next step.

Not sure what @javivelasco and @soyjavi have planned for adding tests, but I can certainly add some with the autocomplete to help verify these sorts of interactions.

**Comment by lycon2014** [comment]
I'll check these out

**Comment by javivelasco** [comment]
Hi guys! Of course we have to add some tests. In fact is crucial for me but I wanted to release a version ASAP. I spoke in Bratislava with Nik Graf, creator of Belle about component's accessibility. He gave me a resource with `aria` attributes for each component. We should should go reviewing each component and adding those attributes though.

@jgoux about Dropdown and Radios, I think `Dropdown` can't be navigated now with keyboard. It's not the same for the `Autocomplete` or `RadioGroup`. If you can't navigate through the `RadioGroup` it should be reported as a bug because I took it into consideration and tested it at implementation time. Other components like the `ProgressBar` have now accesible attributes but there is a lot remaining.

So yes, accessibility should be definitely improved!
Thanks

**Comment by javivelasco** [comment]
Closed in favour of #225
