### ISSUE TITLE
Any chance of TypeScript definitions support?

### ISSUE THREAD

**Issue by Karabur** [react-toolbox/react-toolbox#199]
It became very popular today, and may be already worth to create ones

**Comment by javivelasco** [comment]
Yeah, there are more people requesting it. I did not check on how it's done yet so contributions are very welcome for this.

Thanks!

**Comment by hsrobflavorus** [comment]
Here is a Gist that I forked from @xogeny which should hopefully work... https://gist.github.com/hsrobflavorus/925373f6224679302948

Note that I have not tested this yet, and I was not the original author, but I did take the time to clean it up, fixing some major and minor issues from the original version.

I'm not yet using react-toolbox much, but plan on it soon, if anyone wants to try this out and report back, we can use this issue to continue discussion and tweak it until it's perfect!

**Comment by javivelasco** [comment]
Awesome @hsrobflavorus!! Thanks :)

**Comment by hsrobflavorus** [comment]
Sure thing @javivelasco I have also updated it (same link https://gist.github.com/hsrobflavorus/925373f6224679302948) and added Appbar, Avatar, and refactored the Card (and its child components) to match the documentation.

I'll write up some tests so I can contribute this to DefinitelyTyped as soon as I get a chance, so everyone can easily get it via TSD or the TypeScript definition directory.

**Comment by javivelasco** [comment]
ACK! Thanks @hsrobflavorus

**Comment by hsrobflavorus** [comment]
Javi, I've tried this out and it doesn't work as-is, but never fear! I'm making tweaks now and it's coming together (it works now with the few components I've fixed, working on fixing the rest).

I've got a bit of work to do breaking it down into the 'react-toolbox/lib/{component}' format available as of 0.13.1, and my initial testing is promising. I've got this issue bookmarked and will post updates here.

I should be able to open a pull request with the fully working .d.ts in the next couple of days!

**Comment by hsrobflavorus** [comment]
It's working now, updated here: https://gist.github.com/hsrobflavorus/925373f6224679302948

*Except for one caveat mentioned below* that I'd appreciate anyone's help on. It isn't a showstopper, but it's not ideal because webpack to imports the entire library in the working case, not just the component(s) you want.

_Unfortunately importing them directly in that manner doesn't seem to work
        i.e. "import Input from 'react-toolbox/lib/input'" resolves to undefined, whereas "import { Input } from 'react-toolbox'" works fine!_
        ... Any ideas welcome!

**Comment by xogeny** [comment]
All,

  One comment.  It would be **much better** if these declarations were included in the `npm` package.  You can also include them on DefinitelyTyped as well.  But by including them in the `npm` package, you make it *much* easier for users to use them.  The issue with DefinitelyTyped is that it is very easy for the files there to get out of step with the `npm` module.  By storing them in the `npm` module they are a) easier to keep in date with the current `npm` version b) easier to download (no need for `tsd`) and c) they can be used "out-of-the-box" by users with just an `npm install ...`.

You might ask "well why does everybody else put their declaration files in DefinitelyTyped".  The reason is that until version 1.6 of TypeScript, it didn't have any functionality for extracting the type information from an `npm` module, so you had to manage them separately.  But as of version 1.6, you can add a `typings` field to `package.json` that tells the TypeScript compiler all about the types contained in a module.  As I said, this is a much better solution that avoids the need for a separate, parallel and potentially out-of-sync package management system.

As a TypeScript user, I'd much rather have the types in the `npm` modules.  Of course, I have no objection if you want to support both.

One note: the `.d.ts` file requires for the `typings` field is slightly different from the one required on DefinitelyTyped.  If you have any questions about what these files should look like let me know.

**Comment by xogeny** [comment]
@hsrobflavorus I'm pretty sure if you want to be able to import these as submodules, you need to actually define distinct submodules in the `.d.ts` file.  Something like this (untested):

```
declare module 'react-toolbox' {
    import AppBar from 'react-toolbox/lib/app_bar';
    import Autocomplete from 'react-toolbox/lib/autocomplete';
    ...
}

declare module 'react-toolbox/lib/AppBar' {
    import AppBar from 'react-toolbox/lib/app_bar';
}

declare module 'react-toolbox/lib/autocomplete' {
    import Autocomplete from 'react-toolbox/lib/autocomplete';
}
...
```

**Comment by hsrobflavorus** [comment]
@xogeny Thanks for the tip on the npm typings, I wasn't aware of that and I agree it's vastly preferable to DefinitelyTyped/tsd, I will certainly try and get that set up when I open a PR.

Meanwhile, I believe I've fixed the submodule ("import * as Input from 'react-toolbox/lib/input'") style imports, but you have to use **import * as {Component Name}** for it to work. It does correctly import only the necessary parts though, so big improvement.

Only things left to do at this point, I believe, are add in the Ripple Higher Order Component, and add/test the .d.ts file to package.json _typings_ field as suggested.

https://gist.github.com/hsrobflavorus/925373f6224679302948
