### ISSUE TITLE
I made something for phone numbers...

### ISSUE THREAD

**Issue by uiuxguy** [react-toolbox/react-toolbox#202]
I'm also working on a UX toolkit, as well as a view model architecture for assembling apps quickly (I work for a firm that make a lot of one-off solutions) can you use something like this?

It takes any phone number, with any arbitrary separator characters, or spaces, or no characters, and parses it into a smart object instantly.

https://www.youtube.com/watch?v=mUjaduusDQM&feature=youtu.be

**Comment by javivelasco** [comment]
Hi @uiuxguy 

It looks nice! It material design spec specifies something like that I would be happy to accept a pull request to add that behavior. Unfortunately, I think it would be best to include it in the library instead of adding dependencies. Please open a PR if you want to add it! Closing to avoid noise

Great work BTW!
Cheers!
