### ISSUE TITLE
Create repository for react-toolbox-example-server

### ISSUE THREAD

**Issue by carloscuatin** [react-toolbox/react-toolbox#215]
create repository for make fork and create example of react toolbox in server side rendering

**Comment by evollu** [comment]
I'm adding following code but babel still complains
```
var hook = require('css-modules-require-hook');
var sass = require('node-sass');

hook({
    generateScopedName: '[name]__[local]___[hash:base64:5]',
    extensions: ['.sass'],
    preprocessCss: function(data, filename) {
        var result;
        result = sass.renderSync({
            data: data,
            file: filename
        }).css;
        return result.toString('utf8');
    },
});
```
error is
```
SyntaxError: Unexpected token ILLEGAL
patient-4     at exports.runInThisContext (vm.js:53:16)
patient-4     at Module._compile (module.js:387:25)
patient-4     at Module._extensions..js (module.js:422:10)
patient-4     at Object.require.extensions.(anonymous function) [as .js] (/Users/LLu/Code/Patient/server/node_modules/babel-register/lib/node.js:154:7)
patient-4     at Module.load (module.js:357:32)
patient-4     at Function.Module._load (module.js:314:12)
patient-4     at Function._load (/Users/LLu/Code/Patient/server/node_modules/pmx/lib/transaction.js:62:21)
patient-4     at Module.require (module.js:367:17)
patient-4     at require (internal/module.js:20:19)
patient-4     at Object.<anonymous> (/Users/LLu/Code/Patient/server/node_modules/react-toolbox/lib/ripple/index.js:13:14)
```
can you help me with this?

**Comment by javivelasco** [comment]
Hi! My first thought is that probably the paths are not properly configured. Try checking with this snippet:

```js
var hook = require('css-modules-require-hook')
var sass = require('node-sass')
var path = require('path')

hook({
  rootDir: path.join(__dirname, '../'),
  extensions: [ '.scss' ],
  generateScopedName: process.env.NODE_ENV === 'development'
    ? '[name]__[local]___[hash:base64:5]'
    : '[hash:base64:5]',
  preprocessCss: function (data, filename) {
    return sass.renderSync({
      data: data,
      file: filename,
      includePaths: [
        path.join(__dirname, './app/components'),
        path.join(__dirname, './node_modules')
      ]
     }).css
  }
})
```

**Comment by evollu** [comment]
i found the issue is a typo in extension property. thanks for the help, it is working now.
do you think adding a step guide in readme is helpful?

**Comment by evollu** [comment]
why name and local are removed in production in your example?

**Comment by javivelasco** [comment]
Just to make classnames shorter. Since you would not need to know where are those classnames coming from, there is no need to include name and local in the scoped name. So just convenience, it's not anything important.

About including this in the Readme or documentation I would not say no. Anything that takes you some time to figure out clearly is missing in the docs so it would be nice to add a section. Check #666 because the intention is to rewrite documentation considering PostCSS for the next major.

What I particularly don't like about this setup is that, although it's a working SSR flow, you are missing some goodies from webpack like requiring images, svg sprites and stuff like that. It would be better to use webpack in both sides but that's something completely opinionated. If the library works in "any" setup that's good enough
