### ISSUE TITLE
Datepicker disabledDates prop

### ISSUE THREAD

**Issue by anthony-nardi** [react-toolbox/react-toolbox#242]
How do you feel about adding another prop to the `<Datepicker />` for disabling dates?  The `minDate` and `maxDate` are great, but an array of Date objects would allow for greater flexibility.

**Comment by javivelasco** [comment]
It sounds nice but from an UX point of view it would be difficult to discover available dates with more than one month distance from each other. They wouldn't be displayed until you move through the picker. More opinions on this?

**Comment by patrick-jones** [comment]
I can see a use for this -- say you want to disable weekends and holidays?

**Comment by javivelasco** [comment]
Yeah, it makes sense

**Comment by patrick-jones** [comment]
In fact, it might be good to support a callback function for this. Each time the month changes, the component passes the date to the callback function, which returns a list of disabled dates. That way you can express "never on a weekend" as a function instead of passing all weekends in at the front.

**Comment by javivelasco** [comment]
Done
