### ISSUE TITLE
Font weight

### ISSUE THREAD

**Issue by ktmn** [react-toolbox/react-toolbox#247]
In _react-toolbox/components/tooltip/style.scss_ for example, there is

```
.tooltip {
    font-weight: $font-weight-bold;
}
```

How come it's different than other attributes like _font-size: $tooltip-font-size_ which I can override easily? If I don't want bold tooltip I would have to either override $font-weight-bold to not actually be bold, or add my own class to every tooltip instance.

I think it would be more consistent and convenient if it was

```
font-weight: $tooltip-font-weight;
```

and defined in the __config.scss_

Same for font-weight everywhere, in my opinion it's as important as color or font-size, so I don't know why it's excluded.

Just a suggestion, thanks.

**Comment by javivelasco** [comment]
Hi @ktmn ! It's not included in some places because if you want to follow Material Design guidelines you shouldn't change it in most places. But I agree with you, it costs nothing to move font weight to a variable to allow overriding through themes. Let's keep it as an enhancement for future releases.

**Comment by javivelasco** [comment]
Closing to reduce noise. It's not that important and with theming you can easily achieve this. In future releases we are going to focus customization via variables only for theming stuff and this kind of customization should be done with custom modules.
