### ISSUE TITLE
Help with NPM - Ayuda con npm

### ISSUE THREAD

**Issue by V3ct0r** [react-toolbox/react-toolbox#25]
You could place a manual on how to install the dependencies and so to implement the project 100% and I would like to contribute more but work in Linux and gives me some errors when installing the package, thank you very much.

-
Podría colocar un manual de como poder instalar las dependencias y asi poder ejecutar el proyecto al 100% ya que me gustaría aportar mas pero trabajo en Linux y me da algunos errores al instalar los paquetes, muchas gracias.

**Comment by javivelasco** [comment]
I'm currently working on the documentation and the installation process is going to be there. To run the project for development just clone the repo and `npm install`. You need *node 4.2.1*! If your node system version is older check `nvm` to have multiple node versions along your system. Then `npm start`. You can check the components @ `localhost:8080/spec`.

To use the components in a different project I can tell you for now that the best way is to integrate it with [webpack](http://webpack.github.io/). We are using css modules, es6 and sass so you can include the project as an npm dependency in your own project and then require just the modules you need. With css modules the css will be automatically resolved. [react-webpack-boilerplate](https://github.com/srn/react-webpack-boilerplate) is a good starting point for webpack projects. For now I recommend using directly the github project instead of the npm package (we didn't release yet).

Good luck! :grimacing:
