### ISSUE TITLE
CardMedia is not getting shown in Firefox

### ISSUE THREAD

**Issue by YoYuUm** [react-toolbox/react-toolbox#253]
Sometimes a CardMedia component with an image in a Card component doesn't show the image at all in Firefox, some other times it shows only the image partially. 

The problem is related with the "padding-top" rule set using percentages. But I didn't figure out what's exactly the problem. You can use as example the component in react-toolbox documentation: http://react-toolbox.com/#/components/card.

I'm using Firefox 43.0.4 under os X.

**Comment by javivelasco** [comment]
Thanks, I'll investigate it

**Comment by nathanmarks** [comment]
@YoYuUm @javivelasco 

I think I know the fix for this -- we may need an additional container. The `padding-top` media area property is a css-only "hack" for forcing the aspect ratio.

Check out the answer on this SO question: http://stackoverflow.com/questions/23717953/padding-bottom-top-in-flexbox-layout

**Comment by derekstavis** [comment]
I was about to report the same issue here, which I noticed when playing with playground. In my code, adding an additional container worked for me too. Thanks @nathanmarks :)

**Comment by javivelasco** [comment]
Alright!

**Comment by nathanmarks** [comment]
@javivelasco the container should be added to the lib IMO

**Comment by javivelasco** [comment]
mmmm ok

**Comment by nathanmarks** [comment]
Yeah, FF has a huge % of browser share still, can't ignore it :)

**Comment by derekstavis** [comment]
At office most people have recently migrated from Chrome to Firefox because of resource usage. Some of my friends and even costumers also reported the same trend. Although most browser historical data shows firefox usage declining, the [press reports different behviours](http://gizmodo.com/fuck-it-im-going-back-to-firefox-1685425815).

**Comment by javivelasco** [comment]
Of course, we have to provide fully support
