### ISSUE TITLE
Ability to add buttons to a Table

### ISSUE THREAD

**Issue by delaneyj** [react-toolbox/react-toolbox#268]
I have a table of games which I want players to be able to join or create a new one.  Normally I'd add an extra `<th><Button>create</Button></th>` and in each row add a `<td><Button>join</Button></td>` at the end.  For a lot of table like data this workflow makes a lot of sense but with the current data driven approach in `<Table/>` it appears its not possible (or not documented).

Was hoping something way to include arbitrary components in `td` or `th` elements.

As a stop gap I'm using a normal table and extend the sass in `~react-toolbox/lib/table/style.scss`.  but lose out on the other features of the included `<Table/>`

**Comment by delaneyj** [comment]
As a stop gap I'm using a normal table and extend the sass in `~react-toolbox/lib/table/style.scss`.  but lose out on the other features of the included `<Table/>`

**Comment by javivelasco** [comment]
Yes, it's happening with other components as well. The ability to provide arbitrary content is very important and I think it is specially for components such as the `Table` Although sometimes is very handy to be able to generate a table from a data set, you are also losing flexibility if you want to provide arbitrary content. It's possible anyway.

I'm going to label as an enhancement. I appreciate help from the community with this features, because they actually appear with usage and I'm not enjoying too much spare time lately.

**Comment by delaneyj** [comment]
I actually think Dropdown is the perfect example for this, were the default data is handled fine but can provide a custom `th` & `td` templates.  Would be happy to provide some jist as I use it more, right now using the styling is enough for my use case but we can discuss further in a few weeks.

**Comment by javivelasco** [comment]
Great, thanks!

**Comment by joehua87** [comment]
Thank you for your awesome library.
@javivelasco, @delaneyj I've implemented this feature at https://github.com/joehua87/react-toolbox/commit/86ce8cce2547fdbb00674264963ff959cdc5d308. Please take a look at :smile: I'm very happy to make a PR
Live demo here: http://45.79.94.169:8080

**Comment by delaneyj** [comment]
looking good, can you version also support buttons in the <th/>'s of the header @joehua87 ?

**Comment by kagux** [comment]
Nice work @joehua87 ! 
However, I feel like proposed implementation is introducing quite complicated templating instead of using React components. For now you wanted to customize single cell, but imagine adding custom logic to header or specific rows (colspans, highlighting, etc).
Wouldn't it be better to allow using components that follow original html table markup? Here's an advanced example from [material-ui](http://www.material-ui.com/#/components/table)
```
<Table
          height={this.state.height}
          fixedHeader={this.state.fixedHeader}
          fixedFooter={this.state.fixedFooter}
          selectable={this.state.selectable}
          multiSelectable={this.state.multiSelectable}
          onRowSelection={this._onRowSelection}
        >
          <TableHeader enableSelectAll={this.state.enableSelectAll}>
            <TableRow>
              <TableHeaderColumn colSpan="3" tooltip="Super Header" style={{textAlign: 'center'}}>
                Super Header
              </TableHeaderColumn>
            </TableRow>
            <TableRow>
              <TableHeaderColumn tooltip="The ID">ID</TableHeaderColumn>
              <TableHeaderColumn tooltip="The Name">Name</TableHeaderColumn>
              <TableHeaderColumn tooltip="The Status">Status</TableHeaderColumn>
            </TableRow>
          </TableHeader>
          <TableBody
            deselectOnClickaway={this.state.deselectOnClickaway}
            showRowHover={this.state.showRowHover}
            stripedRows={this.state.stripedRows}
          >
            {tableData.map( row => (
              <TableRow selected={row.selected}>
                <TableRowColumn>{row.index}</TableRowColumn>
                <TableRowColumn>{row.name}</TableRowColumn>
                <TableRowColumn>{row.status}</TableRowColumn>
              </TableRow>
              ))}
          </TableBody>
          <TableFooter>
            <TableRow>
              <TableRowColumn>ID</TableRowColumn>
              <TableRowColumn>Name</TableRowColumn>
              <TableRowColumn>Status</TableRowColumn>
            </TableRow>
            <TableRow>
              <TableRowColumn colSpan="3" style={{textAlign: 'center'}}>
                Super Footer
              </TableRowColumn>
            </TableRow>
          </TableFooter>
        </Table>
```

While you probably don't want to use such noisy component for simple table like the one in react-toolbox example, if I were to build custom table layout I'd rather have full control of elements.

Current implementation already has `TableRaw` and `TableHead`, it would just be a matter of allowing children to `Table` if you want to take over default layout.


P.S. @joehua87, I noticed that your commit updates formatting of files. You should check if your editor is using jshint config coming with this repo. Or you can use `npm test` to make sure your changes are passing jshint and other tests.

**Comment by joehua87** [comment]
Hi @delaneyj, I've update in the Example, just need to change to model from
```js
dogs: {
      header: 'Dogs',
    },
```
to
```js
dogs: {
      header: <Button label="Dogs" raised primary />,
    },
```

**Comment by joehua87** [comment]
Hi @kagux, thank you for your feedback
I've make a new commit in a new branch (lint)
I see that the material-ui is great library & highly customized. I used to use it. But I scare of duplicated code :cry: 
Allowing children to Table is great (in case we want to add custom TableHeader, TableFooter). @kagux, Did you have any ideas on this? I'm please to do this
I currently just want to enhance the current Table. That can help:
  * Backward compatibility (if don't provide the render method, it will use the default as now)
  * Able to render Nested Item
  * Provide Button to manipulate data
  * Easy to choose the Component that fit our purpose (like Dropdown, Autocomplete). Like this
Change from 
```js
const model = {
favoriteRepository: {  type: String }
}
```
to
```js
const model = {
favoriteRepository: {
       header: 'Fav Repo', // If ignore, it will use the default case: favoriteRepository
       width: 300, // Able to ignore
       render: (entity) => (<Dropdown auto source={allRepos}
                                      onChange={(value) => this.handleFavRepoChange(entity, value)}/>)
     }
}
```
Not a lot of code :smile: 
Like in https://github.com/react-toolbox/react-toolbox/blob/dev/components/utils/utils.js#L46
  * I suggest that we should enhance this to select the right **Default Component** (avoiding write render method for every column)
   - Date => use DatePicker or TimePicker

**Comment by dlebedynskyi** [comment]
Guys, is there any news on this ? 
we would like to use toolbox but for some components we do need enchanted tables

**Comment by javivelasco** [comment]
Gotta review today

**Comment by gharwood1** [comment]
+1

**Comment by q3452** [comment]
Did this enhancement get dropped or merged in with another?
