### ISSUE TITLE
inset has no effect for the ListDivider

### ISSUE THREAD

**Issue by emirotin** [react-toolbox/react-toolbox#270]
The default rule has higher specificity than the inset rule:

![](https://monosnap.com/file/N74fGce29zkzbFdlUywxchm4C2KNco.png)

**Comment by javivelasco** [comment]
Thanks for reporting @emirotin !

**Comment by emirotin** [comment]
Actually, I wanted to thank you for the great library but also report a general issue I have with customizing the styles. Please don't consider it as a rant, I'd rather want to give as much info and thinking as I can.

The issue is related to this one, but is two-fold:

1. the usage of complex selectors (`~` in this case, `:not` in others) that set high specificity and are hard / brittle to override with cssModules
2. absence of "hooks" (like `data-react-toolbox`) together with "non-guessable" classes (because of CSS modules).

Recent example: the icon button (icon menu trigger) in the toolbar has to have contrast color.
Here's what I had to do to apply it:

```
.userMenu {
  margin-left: auto;
  [data-react-toolbox="button"] :global(.material-icons) {
    color: $appbar-contrast;
  }
}
```

I see several problems here:
a) I have to use implementation detail (`.material-icons`) that makes it error-prone should you decide to switch the implementation
b) I have to artificially build the high specificity rule which makes it error-prone, implementation-dependent, hard to override in other places and cluttered (the code doesn't clearly explain the intent)
c) I have to ditch the idea of CSS modules and use the `:global` selector

(1) complex selectors (`:not` in this case as far as I remember) contribute to issue b), and (2) absence of the hook contributes to a) and c).

I think CSS modules by nature are very close to [BEM](http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/) (component is module is file, element is class, modifiers are not strictly defined by can be implemented in different ways), so some ideas can be borrowed. If you always used the plain class selectors (with modifiers where necessary) and added hooks (`data-` attributes or "public" classnames) everywhere it would make fine-tuning the UI much easier. BTW AFAIK attribute selectors are much slower so that maybe the case for using "public" (fixed, without the hash part) CSS classes as hooks.
I understand that the initial idea is to provide ready-made UI framework customizable through SASS variables, but as you see with the button in the appbar example there are valid cases to override the styles in CSS.

Please let me know if I can give more details or help in a different way.

---
P.S. I often find small issues in docs when browsing the docs site (for example many examples import from the lib itself which doesn't work when `core-js` is not importable). If you added a "Fix this docs" button that'll be a shortcut to GH PR (similar to [this](http://docs.resin.io/#/pages/introduction/introduction.md)) I would submit them as I see the issues. Otherwise I instantly forget them :(

**Comment by javivelasco** [comment]
Hi @emirotin , thanks for your feedback and your kind words.

As you guessed, the initial idea is to provide some components ready for material design specification and to make them as close as possible to the original native implementation. The styling/theming issue is a big one since I don't see an easy way to do it. The best approach I've found at the time was to provide well-defined variables and to give some general selectors like the `[data-react-toolbox]`.

You are right, not every component or layer has a custom general class to be easily selected and they should. A first step would be to provide those general clases since they are frictionless. The only requirement would be have a predefined way to do so for the sake of simplicity. I don't particularly mind to use classes or data attributes. Maybe higher priority is better since they are going to be used to override default styles.

About the pseudo selectors I know they are more specific but we tried to avoid them when possible. Sometimes I think they are needed to provide some styles but if anybody founds and lower priority rule to get the same effect I would be happy to accept a PR about it.

Overriding some styles is just fine. You don't have to follow religiously the Material spec and you may want to change some stuff. The library should provide an easy way to do it without manually boosting priority across selectors. If we can rewrite some styles to get lower priority great, if we can't, although it's not beautiful client code, it still works.

Finally, I think it's a great idea to add a link to edit the markdown document in Github. We should include it without a doubt.

Thanks for the feedback, we are releasing a new version really soon :)

**Comment by emirotin** [comment]
Thanks for your prompt response. I'm new to React et. al., and very short
of time recently, but if I stick to the React infrastructure I'll try to
give more thinking and propose / PR some improvements to this library. It's
great, comprehencive and I found it much more sane in terms of styling
compared to other popular React MD implementations :)

**Comment by javivelasco** [comment]
Sounds great, thanks @emirotin , I appreciate it!
