### ISSUE TITLE
Drawer component insufficient requirements for Material Design

### ISSUE THREAD

**Issue by gabrielenosso** [react-toolbox/react-toolbox#283]
In the Material Design guidelines, it says that the Drawer could be permanent:
https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-behavior

In this case, the "dark overlay" should not be shown.
As it is right now, the overlay is always shown.
Moreover, there's no possibility to specify CSS classes for the overlay itself.

The best solution would be a way to disable the overlay.
A simple prop "overlay" (boolean) could do the trick.
<Drawer>Content</Drawer> --> Drawer with overlay
<Drawer overlay={false}>Content</Drawer> --> Drawer without overlay

**Comment by javivelasco** [comment]
Hi @gabrielenosso , you are right, the Drawer is very basic now. That would be a good starting point. The main reason we are not implementing a more complete solution for the component right now is because we still don't have full responsive design support. At the time of introducing responsive components the Drawer should behave accordingly.

I'll be happy to accept a PR supporting fixed drawer (consider the content should be moved too)

**Comment by patrick-jones** [comment]
I think I could contribute a PR for this. Before I get too deep into it, I wanted to run my idea by you.

As you mention, you have to coordinate the width of the content drawer with the pinned content. You also need to coordinate the appearance of the overlay. I was thinking something like this:

```xml
<Frame leftPermanentAt='lg' leftWidth='lg'>
    <Drawer active={props.leftActive}>
        <p>Whatever...</p>
    </Drawer>
    <Pane>
        <p>Main content goes here</p>
    </Pane>
    <Drawer active={props.rightActive}>
        <p>Whatever...</p>
    </Drawer>
</Frame>
```
`lg` would refer to one of the [predefined breakpoints](https://www.google.com/design/spec/layout/responsive-ui.html#responsive-ui-breakpoints), and the left drawer widths would be std or lg (320, 400) based on [specs](https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-specs) and this comment about [max width of 400px on desktop](https://www.google.com/design/spec/layout/structure.html#structure-side-nav).

It's possible to make the drawer and content area be free-standing, but it creates a much greater burden on the developer to keep things in sync. Also it exposes implementation details (such as, _make sure that you put the pane next to the drawer in a div with display: flex and zero margin and padding..._).  The `Frame` container component makes it easier to use and lets us keep the implementation hidden away. It also opens up the possibility of drawers that are not scoped to the entire screen, such as [the angular material sidenav](https://material.angularjs.org/latest/demo/sidenav).

What do you think?

**Comment by javivelasco** [comment]
I think it's a very nice idea. The only thing is that maybe instead of frame it makes sense to consider a `Layout`? Maybe even the `App` component can be considered to implement this

**Comment by patrick-jones** [comment]
`Layout` is probably a better name.  `Pane` isn't the best name either.

I thought about implementing it on `App`, but I lean against it for a couple of reasons. First, just to keep it separate so that people don't have to bother with it if they don't want to use drawers.  Second, I think I'd want to be able to allow something like this:

```xml
<Layout>
    <Drawer>
        (site navigation here)
    </Drawer>
    <Pane>        
        <Layout>
            <Pane>
                (grid of, say, images)
            </Pane>
            <Drawer>
                 (details about the currently selected image)
            </Drawer>
        </Layout>
    </Pane>
</Layout>
```

where the outer `Layout` is for overall site structure, and everything within the outer `Pane` is controlled by react-router or something like that.

Also, it speaks to the fact that left and right drawers are really very different things in the spec, despite sharing the name.  Left is typically for navigation, right for extra details about what's in the main content area. They also have very different [rules for how they are displayed and their sizes](https://www.google.com/design/spec/layout/structure.html#structure-side-nav). In fact, it might be worth giving them separate components.

**Comment by javivelasco** [comment]
Lovely. If you can contribute with this it would be awesome

**Comment by patrick-jones** [comment]
I'll send a PR when ready.

**Comment by javivelasco** [comment]
:+1:

**Comment by z-ax** [comment]
Would be awesome as proposed.
Also, option to shift content on open would be cool.
