### ISSUE TITLE
Predictable Release Cycle?

### ISSUE THREAD

**Issue by joevbruno** [react-toolbox/react-toolbox#285]
Are you working within a predictable release cycle with regard to publishing updates to the NPM repo? In other words, do you publish NPM versions simply as enhancements, bug fixes, etc, come in or do you push changes to the NPM repo on a set time-table or recurring interval (like weekly, every 6 weeks, etc).

**Comment by javivelasco** [comment]
Actually we never thought about it. I think commitment for release cycles involves recruiting a bunch of developers to work on the project together and plan next steps. For now, we are releasing fixes and small enhancements as they come.

**Comment by joevbruno** [comment]
That is certainly one approach; however, even on a smaller scale this could be achieved. The dates could be fairly relative and somewhat flexible, but would indicate clear points of enhancements or upgrades. This would make it significantly easier for larger teams to utilize React Toolbox, who don't have the luxury of frequent or immediate upgrades due to QA and other development requirements or dependencies.  Am I missing a change log or release notes somewhere?

**Comment by javivelasco** [comment]
Sorry, I've forgot to answer here. Yes, I think maybe with small changes it can be done but I'd need some commitment from people interested in helping out with the project since I'm lacking of spare time to face a more or less strict scheduled.

I agree with you, though. Big changes are documented in the release, the rest are small fixes and improvements :)
