### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by sars** [react-toolbox/react-toolbox#299]
Hi,
I'm wandering is there any plan to implement theming?
Something like https://github.com/css-modules/css-modules/blob/master/examples/theming.md?
It's really difficult to customize components now...

**Comment by javivelasco** [comment]
Hi @sars I think it would be a good option to be able to inject the styles as a dependency in a prop. Being that the case, since this is a Material Design component set, some styles should be fixed. Probably in the future we can split CSS files in two different theme files: with with basic styles and other for colors or something similar so you can provide a style object via props.

For now what you can do to provide a theme is to override some theme variables. But this is just for a theme, there are variables that are not likely to be changed. If you want to override you can do it too generally.

Why do you find difficult customization? Not enough config variables? Webpack coupling? Selector priority?

**Comment by sars** [comment]
@javivelasco , We developed project and client decided to use material design for it. Finally, client changed his mind and we have to redesign a lot of components significantly. 
Variables are not enough. 
And it's difficult to override some styles, coz it's difficult to define styles with higher sector priority.

**Comment by javivelasco** [comment]
I know... I understand what you say but truth is that this is supposed to be a Material Design lib. As soon as you want to get ride of Material... it doesn't make to much sense to use it. Anyway, I think it can be good to have the ability to inyect the theme optionally to the components. Something like react themeable from Mark Dalgleish. We can try to do something like that without breaking the API, what do you think?

**Comment by sars** [comment]
To be honest I thing the most simple way that wouldn't take lots of changes, just to accept theme property with styles map.
Something like: https://github.com/sars/appetini-front/blob/appetini/src/components/Input/Input.js#L18
https://github.com/sars/appetini-front/blob/appetini/src/components/Input/Input.js#L41

and style overrides:
https://github.com/sars/appetini-front/blob/appetini/src/components/Dropdown/Dropdown.js#L17
https://github.com/sars/appetini-front/blob/appetini/src/components/Dropdown/Dropdown.js#L20

However it doesn't solve problem of theming components that uses in current styling component:
If you'd like to override styles for dropdown, you will not be able to override styles for Input inside Dropdown
Otherwise, we can accept 2 prop - one for dropdown styling and another for input or even in the same styling option accept styles for input....

**Comment by javivelasco** [comment]
Uf it's a difficult topic indeed... I'd like to help you to make components more customizable but honestly I did not thought at any point a full override would be needed...

**Comment by sars** [comment]
@javivelasco , ok, i'm not sure if my idea make sense for this project honestly
