### ISSUE TITLE
Ripple effect

### ISSUE THREAD

**Issue by equinusocio** [react-toolbox/react-toolbox#305]
There is a small issue with the ripple effect. The ripple animation shouldn't restart each click, but the ripple should continue his expansion. This is the correct behavior:

![correct](https://cloud.githubusercontent.com/assets/10454741/12892159/1721e9a6-ce8b-11e5-8e9b-d024e81e5607.gif)

**Comment by javivelasco** [comment]
It may not be an easy change, we'll take look

**Comment by equinusocio** [comment]
Any update?

**Comment by javivelasco** [comment]
Not actually, I'm prioritizing other tasks but it's still in my mind :)

**Comment by wtgtybhertgeghgtwtg** [comment]
It seems a `Ripple` only has [one `span`](https://github.com/react-toolbox/react-toolbox/blob/dev/components/ripple/Ripple.js#L137-L139) that animates and resets.  What you could do, and I think this is kind of like [what `Polymer` does](https://github.com/PolymerElements/paper-ripple/blob/master/paper-ripple.html#L618-L631), is create a `span` each time the material is clicked, and have that `span` be removed after the animation is complete.  This might also solve #670 in a way; rather than making non-animating ripples invisible, they just won't exist.
