### ISSUE TITLE
Sortable Column for Table

### ISSUE THREAD

**Issue by kodermax** [react-toolbox/react-toolbox#322]
Could you please add Sortable Column for Table.

**Comment by Kikobeats** [comment]
Like that?

![](https://i.ytimg.com/vi/asEuFvWGJDs/maxresdefault.jpg)

**Comment by javivelasco** [comment]
What can be done for this is to provide a custom element for a Table heading and then add a callback function to sort data out of the table component. I'll try an example during the afternoon and leave this open meanwhile

**Comment by kodermax** [comment]
like this https://www.google.com/design/spec/components/data-tables.html#data-tables-interaction
![image](https://cloud.githubusercontent.com/assets/590985/15806889/1a961ed0-2b57-11e6-9879-2cbc6f4d2b86.png)

**Comment by kodermax** [comment]
and pagination 
![image](https://cloud.githubusercontent.com/assets/590985/15807157/b8d52698-2b5e-11e6-8079-3c35a7c1f3dc.png)

**Comment by UniIsland** [comment]
Why is this issue closed?
Is sortable column still in the plan?

**Comment by kodermax** [comment]
+1

**Comment by javivelasco** [comment]
I think it can be achieved out of react toolbox. You can sort the source!

**Comment by UniIsland** [comment]
> I think it can be achieved out of react toolbox. You can sort the source!

This is not interactive. One still need to implement the interface that tell the parent component (or backend, when paginated) to sort the source data.
If I want the table header to be clickable, I have to modify the code of react-toolbox's `Table` component directly.

**Comment by javivelasco** [comment]
So the proper solution would be to modify the API so the `Table` accepts `onClick` handlers

**Comment by vmsoftware** [comment]
Currently, I'm working on a DATATABLE based on RT table lógic and follow the MD spec. 

I'm making it in a responsive wrapper with horizontal scroll for content and I'll happy to share if @javivelasco agree...

This is a preview with header selected items,  filters, pagination and rows per page.. 
I'm working on sortable column right now.

![screenshot_20160717-214924](https://cloud.githubusercontent.com/assets/16278865/16916654/91af32b2-4cc3-11e6-856f-39dadadd621b.png)

And filter like this:

![screenshot_20160718-084451](https://cloud.githubusercontent.com/assets/16278865/16916756/2c7f14c4-4cc4-11e6-8bbd-2476e9490124.png)

**Comment by javivelasco** [comment]
Nice! Did you change the code for the `Table` component we provide? Maybe we can include useful changes to make it more flexible so you can easily write this kind of wrappers and customize as you want

**Comment by vmsoftware** [comment]
@javivelasco 

yes I have modified 3 files but not directly. I copied the table directory from RT, created a DataTable.js for manage the state (filters, rows per page and other), add the header and footer and modified a little the Table.js and TableRow.js files to include a callback for tableHeadercolumnClick, assing the event for select rows and some small changes in your handleSelect function because the current versión don't work with the multiselectable and unselect features.

I'll try to finish during this week and upload it at the weekend. I think that RT Table can be merge some features that I did, like "headerColumnClick callback", "width of columns" in model prop and the possibility of select a row in any place of the row(not only at checkbox.

When I finish obviously I'm going to share with you for test and add all you think is good.

**Comment by joshua1** [comment]
@vmsoftware when are you making this available on Github. would be nice to have, please

**Comment by joshua1** [comment]
@vmsoftware  When are you doing a PR for this , or making it a component that can be added to a project.

**Comment by devarsh** [comment]
@vmsoftware are you planning on sending a PR for this.

@javivelasco Why was this issue closed

**Comment by javivelasco** [comment]
Because that's too much for a single component and [it can be easily done](https://github.com/react-toolbox/react-toolbox/tree/dev/components/table) with composition and the latest `Table` version.
