### ISSUE TITLE
IconButton text-transform uppercase, breaks font icons

### ISSUE THREAD

**Issue by omerts** [react-toolbox/react-toolbox#360]
Hello,

All buttons have a text-transform: uppercase, css attribute. When using an IconButton, with a custom font icons, this behavior breaks our icons, since it transforms all text to uppercase, and thus changing the wanted icon.

**Comment by KerenChandran** [comment]
According to Google's Material Design docs (linked below), the button text needs to be uppercase so the text-transform: uppercase is necessary. 

https://www.google.com/design/spec/components/buttons.html#buttons-style (Under Typography)

**Suggestion**

I'm getting a hunch that you placed your custom icon inside the icon attribute of IconButton. If that is the case, do not do this. This has the style hard-coded in the source code and you will not be able to overwrite it. You can try these options and hopefully one of them works:

```jsx
<IconButton className={cx(style.x)}><span className='ICON_NAME_HERE'></span></IconButton>
```

OR

```jsx
<IconButton className={cx(style.x)}>customIconHere</IconButton>
```

The style object is the stylesheet that was imported and x is a class that is found in that stylesheet (see below):

```css
.x {
  text-transform: none;
}
```

If you need this behaviour in multiple views, I suggest you create the lines above as another component. Then you can easily import that component instead of the icon button and apply your custom icon. 

If this helped you out, please leave a comment and close the ticket. Otherwise, if you are still stuck with this issue or think I misunderstood what you said, please reply back and I'll be happy to help. Also, it would be great if you can send me a snippet of code, so I can get a better understanding of what your issue is.

**Comment by omerts** [comment]
@KerenChandran thank you very much :)
