### ISSUE TITLE
Error: Cannot resolve module with react-hot-boilerplate

### ISSUE THREAD

**Issue by nvcken** [react-toolbox/react-toolbox#37]
I made simple sample with react-hot-boilerplate
I pass below code into src/index.js of react-hot-boilerplate
```
import Button from 'react-toolbox/Button';

const CustomButton = () => (
  <Button label="Hello world" kind="raised" accent />
);
```
I get this error 
```
ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'react-toolbox/Button' in /Users/nvcken/x.Sample/learn_react_webpack/react-hot-boilerplate/src
 @ ./src/index.js 19:26-57
```
Help, I am new of React

**Comment by soyjavi** [comment]
Hi @nvcken here you have a complete example using react-toolbox and webpack

**Comment by noyobo** [comment]
I also have this error

**Comment by javivelasco** [comment]
I'm gonna try in a couple of days to clone react hot boilerplate to get a working example with react toolbox. For now you have the repository with a webpack example (not the boilerplate though)

**Comment by noyobo** [comment]
`lib` directory should be compiled files,   when I try to use react-toolbox,  need compile `sass` and install `redbox-react` `react-transform-hmr` .... ,  very troublesome :anguished:

**Comment by javivelasco** [comment]
Yes, you need to compile `SASS` because of the theming. If we want to provide a flexible and easy way of theming without needing to rewrite the whole style codebase, the best solution that came to my mind was to use SASS variables.

Being that the case, if you want to change the primary color for example consuming the library from the `npm` repository, you would need to prepend the new variables to each sass compile. Of course you will need to have the original sass files and include them in your build process. Otherwise we would be distributing a raw CSS stylesheet which is not directly configurable without overwriting.

That's why the build includes the javascript already transformed by Babel but keeps a copy of sass files so you can build your own. I will be happy to keep researching other approaches because it's a quite controversial topic with a lot of work to be done.
