### ISSUE TITLE
Dumb question about theming inputs

### ISSUE THREAD

**Issue by dbismut** [react-toolbox/react-toolbox#390]
Hey - I come from material-ui. I was interested in styling the input with the error text slightly bigger and aligned on the right. What's the recommended way to do this? That will help me styling the rest.

Thank you very much!

**Comment by felipeleusin** [comment]
It's actually not a dumb question.... I've been struggling with this for a while a now. I see two options, either add a bunch of attributes like data-react-toolbox='input-error' and then all you need is to pass a className to the input component like 

```
.inputWithBigError {
    > [data-react-toolbox='input-error'] {
        font-size: 16px;
    }
}
```
or we need to add a bunch of props like errorClassName, hintClassName, labelClassName.

What do you guys think? @javivelasco I'd be glad to take a shot at this. I'm pending to the first option because one of the strong selling points of react-toolbox is the separation of css

**Comment by KerenChandran** [comment]
So I looked at the source code for input and the Input Error actually does accept a Node instead of a string. I'm not too sure what a node type is, but from a google search it sounds like it can accept a React Element.

Have you tried inserting a component into the error field and apply styles to that component? I'm curious what the behaviour might be. If not, I can look into it on Thursday.

Also I'll work on updating the docs for the components in the next few days. Noticed that some things are missing or somewhat incorrect.

**Comment by dbismut** [comment]
Hey, thanks for your answers.

@felipeleusin how do you actually add the data-attributes? Is that using a node as the value for error (so like `error={ <span data-react-toolbox='input-error'>my error</span> }`)? But in that case I would create a child node that would inherit from the CSS class applied to the error by react-toolbox.

I think what you suggest about adding an errorClassName, hintClassName makes more sense, to me at least. It's actually more inline with what material-ui is doing (with errorStyle, hintStyle, etc...).

**Comment by felipeleusin** [comment]
Yeah, my solution was for a pull request to fix this. That was exactly my point, to chose between errorClassName or theming via CSS.

Both are fine by me. For now you can just use your custom node as error

**Comment by javivelasco** [comment]
I guess we can add props to give classnames to inner elements if you find it useful. My first approach was to use selectors to avoid having too many props but it's true sometimes it's tricky to override styling.

**Comment by dbismut** [comment]
@javivelasco for inputs I don't see any selectors for the error. Am I missing something? Great work btw.

**Comment by javivelasco** [comment]
Thanks @dbismut! actually I did not use the components in a big project and probably there are missing generic selectors for customization. If you want to add some following the established pattern I'll be happy to merge :)

**Comment by dbismut** [comment]
Ok! I'll try to initiate a move to react-toolbox and will PR along the way then! Cheers :)

**Comment by javivelasco** [comment]
Great, thanks!!

**Comment by javivelasco** [comment]
Please check #498
