### ISSUE TITLE
Going Native with ReactNative?

### ISSUE THREAD

**Issue by tomkur** [react-toolbox/react-toolbox#40]
Are there plans to provide native components for best mobile experience?

**Comment by javivelasco** [comment]
That would be awesome but for now I think it's quite difficult to port all of this to React Native. Since we are using CSS modules we are also using features that cannot be directly ported to native components. For the javascript maybe we can create factories to inject native or web elements but the styling approach is way more difficult. So for now we are going to make styles fully responsive so we can mobile friendly web apps and let's see in the future what can be figure out with native!

**Comment by tomkur** [comment]
I see, thanks for the answer
