### ISSUE TITLE
please allow DatePicker to parse keyboard input

### ISSUE THREAD

**Issue by jeffreywescott** [react-toolbox/react-toolbox#403]
Instead of making the input `readonly` and disallowing keyboard input, it would be good if the dialog would open in such a way as to not obscure the field, the user could type in a date string, and DatePicker would parse it ([see here for how](https://stackoverflow.com/questions/1003326/is-there-a-natural-language-parser-for-date-times-in-javascript)) and update the dialog selection in real time.

This would be good for accessibility reasons as well as just user-friendliness.

**Comment by renato** [comment]
This would be awesome. Just imagine someone selecting a birthdate in the current dialog...

I was thinking about it with a simple masked input, like most date choosers out there, but using something like SugarJS date parsing is even nicer.

I think this can be achieved currently using a custom Input with the undocumented DatePickerDialog. So, as an alternative option, a better DatePickerDialog documentation could be used to show it with a custom Input.

**Comment by jeffreywescott** [comment]
@renato -- can you elaborate on how it could be accomplished today? A workaround would be amazing!

**Comment by jeffreywescott** [comment]
WRT selecting a birth date, see also: #402

**Comment by renato** [comment]
Sorry @jeffreywescott, DatePickerDialog needs to be changed before a workaround is possible.

It currently sets its `state.date` from `props.value` only one time, so my test didn't work out of the box.

After mounting, `DatePickerDialog.state.date` keeps the selected date, even if you dismiss the dialog. On reopening, the selected date is the same, no matter what is the `DatePickerDialog.props.value`.

I tried something just to show what I thought was possible, without any validation, just dirty JSON.stringify/parse. Looking at DatePicker.jsx, we needed to handle the dialog opening/dismissing and date selection.

```javascript
export default class DirtyTest extends React.Component {
  state = {active: false}

  handleDismiss = () => this.setState({active: false})
  handleClick = () => this.setState({active: true})
  handleSelect = (value) => this.setState({active: false, date: value})
  handleChange = (value) => this.setState({date: new Date(JSON.parse(value))})

  render() {
    return (
      <div>
        <Input
          icon='date_range'
          label='Birthdate'
          value={JSON.stringify(this.state.date)}
          onChange={this.handleChange.bind(this)} />
        <IconButton icon='arrow_drop_down' onClick={this.handleClick} />
        <DatePickerDialog
          active={this.state.active}
          onDismiss={this.handleDismiss}
          onSelect={this.handleSelect}
          value={this.state.date}
          />
      </div>
    );
  }
}
```

When the date is selected in the dialog, the Input gets the JSON.stringified date. When we change the date in the input, our `this.state.date` is changed as well but it doesn't match the selected date in the dialog when you open it.

So, finally, in order to DatePickerDialog to use the date we set in the Input, I think the best solution would be to get rid of its date state, using only props.value/props.onChange to handle the selected date.

For my little test, it worked with a simple addition to DatePickerDialog.jsx:
```javascript
  componentWillReceiveProps = (newProps) => {
  	this.setState({date: newProps.value})
  }
```
Again, this is just a test, it's **not** how I think it should be done.

And, of course, the Input being editable, we need to validate minDate/maxDate and the date format, which can be a 'MM-DD-YYYY'-like mask set by the user or, as you suggested, SugarJS dates.

**Comment by colshacol** [comment]
I've begun working on this feature, but it is my first open source contribution, so bear with me if it isn't the most efficient fix, haha. 

### Currently, my solution adds the following features:

- Opens date picker dialog on focus, so you can tab from one input field to a date picker and it automatically bring the calendar up.

- Once calendar is active, an 'on-board' input box is auto-focused and ready to parse user input. As soon as the user provides a valid date (`/(\d{1,2})(?:\/?|\s*)(\d{1,2})(?:\/?|\s*)(\d{4})/`) then the year, day, and month on the calendar will update to match.

- In the case that the user clicks a different day/month or changes the year, the input field is changed to reflect the new date picked.

- The new date input field listens for the enter key to submit the calendar and return the date to the original date picker.


### A few issues I am still battling with are:

- My algorithm for changing the month to match the input sometimes misses by.. **a year**, haha.

- I could not get any custom styles to apply to my new input box. I feel like it could use some adjustments because it currently looks very out of place.

- Figuring out how to return focus back to the date picker (when the user presses enter to close the calendar) without re-firing the `onFocus` event on the date picker, causing the calendar to automatically pop back up. I need to return focus to the date picker so that the user can tab to the next one.


I am also working to figure out how to allow input in the date picker input, itself.

Like I said, this is my first open source contribution, and although I have used it a bit, I am not the most well versed in React, either. My current work is available [here](https://github.com/colshacol/react-toolbox). Feel free to give me advice or constructive criticism!

**Comment by javivelasco** [comment]
Some thoughts (maybe I'm missing something you guys commented up there): 

This is even more complicated if we add localization support. Also, providing feedback to the user is not easy because if you open a Dialog to show the picker and then start typing, the input would be hidden. You should be able to see some kind of feedback of what you are actually typing but this is not possible without violating the MD visual guidelines.

You can always keep like an "in-memory" input but without giving visual feedback it would be quite obscure. I agree it would be nice but I don't see a way to do this without *breaking the rules*

**Comment by jeffreywescott** [comment]
@javivelasco I see your point with localization, but we could just have different date parse functions for each locale. We could even add an attribute that would allow users to pass-in their own date parsing function.

WRT user input, I think it should just behave like a plain text field, and when the input loses focus, it calls the date parse function, updates the UI (if the parse succeeds), and highlights the mistake otherwise. Would that be a violation of the visual guidelines? Which one, specifically?

**Comment by colshacol** [comment]
I don't know if it will help, but here is a short demonstration of what I had accomplished at the time of my post above. I'd love to take this requested feature and make it a reality, so any guidance or support would be greatly appreciated.

https://drive.google.com/file/d/0B4YUcg2HBSIvTXpmRC0yaHJHZ2c/view?pref=2&pli=1

**Comment by javivelasco** [comment]
@colshacol I think it's very nice and also it's useful. I'm sure we can make the parsing work out of the Calendar component allowing to compose some smaller components to create the Picker with parsing options.

My only concern with this is that I've never saw before this kind of component in Material Design but it will definitively fit into a complements repository/submodule for react-toolbox. Great work!

**Comment by javivelasco** [comment]
Closed in favor of #626

**Comment by ro-savage** [comment]
PR #704 and PR #705 allow keyboard to be used with the date picker. Both to enter dates and to navigate the calendar.

Not sure if they will get merged in but our project needed something and this covers us for that need. Anyone feel free to use/copy the changes.

**Comment by javivelasco** [comment]
I think those PRs are a good start. I would give a deeper thought at the code but I think they could be merged without a problem :)
