### ISSUE TITLE
Reason for lots of _config.scss values not to have !default?

### ISSUE THREAD

**Issue by emiloberg** [react-toolbox/react-toolbox#424]
Hi,

Is there a reason that a lot of the values in the different _config.scss files don't have the `!default` flag?

E.g. `$dialog-content-padding` in the [dialog/_config.scss](https://github.com/react-toolbox/react-toolbox/blob/dev/components/dialog/_config.scss) don't have the `!default` flag which, as far as I understand it, makes it impossible to change the padding.

**Comment by lucaas** [comment]
I recently added `!default` flags to all color variables (in #398), since those where the ones I where in need to overwrite. I thought about adding the flag to the rest as well but decided against it.

Happy to submit another pull request adding it for the rest unless there are any reasons not to (ping @javivelasco).

**Comment by javivelasco** [comment]
Hi! I just wanted to let you know that there is no special reason about it. At first I thought not everything should be configurable so I added default to the variables that potentially can be part of a theme. But I think that in any case it can be useful to be able to override just any variable.

I'm ok with setting the default flag for all of them :+1:
