### ISSUE TITLE
Issues with Installing react-toolbox

### ISSUE THREAD

**Issue by namuthan** [react-toolbox/react-toolbox#437]
I am  a bit new to react so bare with me, I installed react-toolbox using npm and when I start my server again with webpack I get the following errors
```

 ERROR in ./~/react-toolbox/lib/card/style.scss
Module parse failed: /Users/nabil/Desktop/seng513-master/node_modules/react-toolbox/lib/card/style.scss Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| @import "../base";
| @import "./config";
| 
 @ ./~/react-toolbox/lib/card/Card.js 17:13-36

ERROR in ./~/react-toolbox/lib/avatar/Avatar.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./style in /Users/nabil/Desktop/seng513-master/node_modules/react-toolbox/lib/avatar
 @ ./~/react-toolbox/lib/avatar/Avatar.js 17:13-31
```

This is my webpack.config file

```
var path = require('path');
var webpack = require('webpack');

module.exports = {
  devtool: 'eval-source-map',

  entry: {
    main: [
      './src/app'
    ]
  },
  output: {
    path: __dirname,
    filename: 'app.js',
    publicPath: '/js/'
  },
  module: {
    loaders: [{
      test: /\.jsx?$/,
      exclude: /node_modules/,
      loaders: ['babel'],
      include: path.join(__dirname, 'src')
    },

    {
      test: /\.scss$/,
      include: path.join(__dirname, 'src'),
      loader: 'style!css!sass'
    }
  ]}
};

```

Any idea of how I can fix this so I can start using this amazing react module?

**Comment by lucaas** [comment]
You will need add configurations to resolve the appropriate extensions ([resolve.extensions](https://webpack.github.io/docs/configuration.html#resolve-extensions)) and handle [CSS Modules](https://github.com/css-modules/css-modules) by adding the loader. Take a look at the [config](https://github.com/react-toolbox/react-toolbox-example/blob/master/webpack.config.js) in the [react-toolbox-example](https://github.com/react-toolbox/react-toolbox-example/blob/master/webpack.config.js).

Configuring webpack is a bit tricky and it would be awesome if it was easier to get up to speed with this project. I struggled with it a bit as well.

**Comment by namuthan** [comment]
I added the CSS modules and can u elaborate of how to fix the resolve.extensions part?
Setting webpack is a bit confusing for me at the moment.

**Comment by oscar-g** [comment]
Definitely take a look at the example @lucaas linked...you can basically copy-pase from the webpack.config.

In `resolve.extensions`, you'll want at least the following (straight from the example): `['', '.jsx', '.scss', '.js', '.json']`

**Comment by sampeka** [comment]
Having the same issue, will resolve it with the above. Wouldn't it be better to bundle up the scss and distribute it as css? It's a little undesirable to have to bring in a `node-sass`  and `sass-loader` as extra dependencies when I'm using `postcss`.

**Comment by javivelasco** [comment]
We need to provide SCSS in order to make stylesheets configurable by variables @sampeka

**Comment by genyded** [comment]
I know this is closed... but the whole CSS modules thing is not compatible with some frameworks (like Meteor) without hacking and seems like a pain to configure in almost any environment. Plus forcing Webpack. All that seems like it may make it a bit hard to adopt this library or get buy in from others to adopt it.I just spent 3 days trying to get it working with a Mantra JS app (still haven't) and am forced to pursue other options now just because of the time this is taking - sad since it looks otherwise very well developed.

**Comment by oscar-g** [comment]
CSS Modules is great for those who want to use it, but there should be a compiled stylesheet, for those who don't want to use the webpack workflow.

**Comment by sampeka** [comment]
@javivelasco do you think any of the points raised above are reasonable? Reducing dependencies on things like webpack and sass seem like they'll be really positive for this library long term, since who knows what 90% of people will be using in 5 years (or even 2 or less).  In any case, even if the vision for this library is just to focus on websites, it's good to have an open dialog about these things so positive ideas and contributions can make there way into the library.

**Comment by ofzza** [comment]
Originally I did this to get rid of CSS modules for server-side use, but if you want to get CSS modules out of react-toolbox components for any reason, you can do what I did here:
https://github.com/react-toolbox/react-toolbox/issues/168#issuecomment-218342084

Basically, what this does is:
- Builds react-toolbox components in such a way that you don't need to worry about CSS modules or webpack
- Provides you with pre-build CSS stylesheets, if you want to use those just out-of-the-box
- Provides you with a Gulp task that you can include in your own build which will allow you to build CSS stylesheets with first customizing all those SCSS variables

**Comment by javivelasco** [comment]
Please guys, your feedback is important for this. Check #498. I recently wrote an small module [react-css-themr](http://github.com/javivelasco/react-css-themr) that I'm using to give a new focus on how components are styled. You have in the README some of my thoughts about styling components with CSS. With this approach, every component implements a `theme` property that allows to provide an object with `class-interface: class-final-value`. This means multiple things:

- You can easily compose and override styles
- You don't need to use webpack because toolbox no longer needs to require SASS.
- You don't even need to use CSS modules because you can provide a dummy object mapping the classname interface to global classes.
- You can grab react toolbox SASS and compile your theme out of the box and them inject it to the components via context.

I think this is way more flexible than it is now and allows to keep benefits from CSS Modules. Also you would be able to use the components in just any application, no need for webpack, css modules or whatever. Please leave your thoughts in #498 !
