### ISSUE TITLE
How are you verifying expectations?

### ISSUE THREAD

**Issue by volkanunsal** [react-toolbox/react-toolbox#44]
I noticed that your tests don't have any assertions. You only seem to be rendering the tested component at a Root component. I'm curious about the rationale for writing the tests for this way rather than using assertions.

**Comment by javivelasco** [comment]
I get it. Maybe you can write a little approach testing the slider with assertions? We need to do a lot of testing BTW but I wanted to release the components soon so that's why there are only a couple of components with the testing approach. My first approach is, as you said:

- Render the component
- Test object methods
- Test rendering (not in an exhaustive way)
- Test events callbacks

I think all of this can be done with the rendered component. Maybe you can through some light in the topic so we can improve the testing approach before developing the whole thing?

Thanks!

**Comment by javivelasco** [comment]
Closing since we are getting no answer. Better approach for testing can be included in this same issue.
Thanks!
