### ISSUE TITLE
Website does not work because `Object.assign is not a function`

### ISSUE THREAD

**Issue by azproduction** [react-toolbox/react-toolbox#45]

**Comment by soyjavi** [comment]
I think you can give more information about your problem.

**Comment by azproduction** [comment]
So I am using a browser which does not support `Object.assign` yet. It should be polyfilled.

**Comment by javivelasco** [comment]
You´re right. Doing it asap, I've been quite busy these 2 days with Reactive Conf

**Comment by azproduction** [comment]
Good luck with `react-toolbox`, looks promising!

**Comment by javivelasco** [comment]
Thanks for your kind words :)!

**Comment by mcpDESIGNS** [comment]
+1 for Chrome, same issue

**Comment by javivelasco** [comment]
More details on Chrome version, OS, etc?

**Comment by mcpDESIGNS** [comment]
Latest Chrome on iPad Air 2

**Comment by guerrero** [comment]
It seems that @azproduction is using Chrome on a version older than iOS 9. In iOS, Chrome uses the same engine as Safari and Safari for iOS only supports `Object.assign()` in >iOS 9. I've also tried to run [react-toolbox.com](http://react-toolbox.com) on my iPad with iOS 8 and it crashes, but if I open the same page on my iPhone, which is running 9.1, it works as expected.

Anyway, the bug is there and, as @azproduction has said, `Object.assign` should be polyfilled. So there are two ways to solve this problem:

1. Add [`babel-plugin-transform-object-assign`](https://www.npmjs.com/package/babel-plugin-transform-object-assign) following the next steps:
    1. Run `npm install --save-dev babel-plugin-transform-object-assign`
    2. Add the following lines to your webkit config:
    ```js
    loaders: [
      {
        test: /(\.js|\.jsx)$/,
        exclude: /(node_modules)/,
        loader: 'babel'
        query: {
          plugins: ['transform-object-assign']
        }
      }, {
    ```

2. Use an npm module like [`object-assign`](https://www.npmjs.com/package/object-assign):
    1. Run `npm install --save object-assign`
    2. Import and use `object-assign` instead of `Object.assign`

I think that the first option is better because it enables a way to use the standard method and you shouldn't import an npm package each time you want to use `Object.assign`, but I wanted to enumerate all possible ways to solve this problem.

I'm commenting on this issue instead of open a PR because this has a wontfix label and I don't know if you're currently working on solve it or if you are waiting to something but, if you want, I can elaborate the PR.

**Comment by javivelasco** [comment]
Thanks for your comment @guerrero. I think the label was there by mistake. Instead of using a polyfill or a transform and since we were using `Object.assign` only in the prefixer code, I think it can be better avoid. I've just uploaded the update.

Thank you so much for your comment :)
