### ISSUE TITLE
ButtonMenu component missing

### ISSUE THREAD

**Issue by gabrielenosso** [react-toolbox/react-toolbox#493]
Hi,
I would really like to have a ButtonMenu component, which should work exactly like the IconMenu but with a button.

It is part of the Material Design guide: https://www.google.com/design/spec/components/menus.html#menus-usage

What do you think about it?

**Comment by javivelasco** [comment]
I think this is the `IconButton` :)

**Comment by gabrielenosso** [comment]
The icon button is for the Icon... what about a normal button (with text and without an icon) that shows a menu? :)
(It's in the same link)

**Comment by javivelasco** [comment]
Oh! Do you mean `IconButton`?

```jsx
import {IconMenu, MenuItem, MenuDivider } from 'react-toolbox/lib/menu';

const MenuTest = () => (
  <IconMenu icon='more_vert' position='top-left' menuRipple>
    <MenuItem value='download' icon='get_app' caption='Download' />
    <MenuItem value='help' icon='favorite' caption='Favorite' />
    <MenuItem value='settings' icon='open_in_browser' caption='Open in app' />
    <MenuDivider />
    <MenuItem value='signout' icon='delete' caption='Delete' disabled />
  </IconMenu>
);
```

**Comment by gvandyk-r7** [comment]
Can you show an example?  I am not seeing how to put text beside the icon itself.

**Comment by javivelasco** [comment]
If you look at the [IconMenu](https://github.com/react-toolbox/react-toolbox/blob/dev/components/menu/IconMenu.js#L55-L80) `render` method you'd see that it consists just on a wrapper `div` to position the `Menu`. You can create a custom component using the `Button` instead of an `Icon` in the same fancy. `IconButton` is there for convenience and because I saw it in the spec but you can also use it as a template to create your own :)

**Comment by kossel** [comment]
I also would like to see menus with text label and specially with cascade menu functionality

**Comment by javivelasco** [comment]
Yeah, menus can be improved. Maybe it's a good idea to gather information about what should the menu exactly implement and open an issue to track the progress and release it in a future version
