### ISSUE TITLE
Checkbox  - effect issue IE11 / EDGE

### ISSUE THREAD

**Issue by dariuszpaluch** [react-toolbox/react-toolbox#501]
When I click on  checkbox  in edge **browser/ ie11** show some gray circle.

[screenshot](https://scr.hu/R44YPm)

**Comment by javivelasco** [comment]
Maybe this is because it keeps the active after clicking?

**Comment by javivelasco** [comment]
May you check if this is still happening with 1.1?

**Comment by jslegendre** [comment]
Can confirm this is still an issue in version 1.1.1.

**Comment by javivelasco** [comment]
@jslegendre @dariuszpaluch I'm quite sure this is happening because of [this](http://stackoverflow.com/questions/34350581/mouse-event-properties-are-undefined-on-ie-11). When you click a checkbox the browser tries to keep the focus on the element. We are preventing it [here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/checkbox/Checkbox.js#L35). I can't debug because I only have mac. What needs to be done is to make sure the event is coming from mouse and not keyboard. Do you know a cross-browser way of doing this?

**Comment by jslegendre** [comment]
@javivelasco You can run IE11 on your Mac by following [this guide](http://osxdaily.com/2015/10/19/use-internet-explorer-11-mac-os-x-easy/).  Might not be useful to you now but perhaps in the future

**Comment by javivelasco** [comment]
Can somebody confirm this is still happening for the latest beta?
