### ISSUE TITLE
TypeScript implementation / definitions

### ISSUE THREAD

**Issue by malekpour** [react-toolbox/react-toolbox#51]
I think new typescript react support is cool. Much easier to to build type safe components and maintain the project for long term as well as great IDE support and intelligence. This will also helps generating typescript definitions automatically.

Considering the way this project has developed (ES2015), you can add typescript support by only renaming .jsx files to .tsx and a little web pack setting modifications.

Any plan or thoughts on this?

**Comment by TheDeveloperXYZ** [comment]
While TypeScript provides excellent type checking, I think many do not know TS well and frankly do not have resources to spend learning that either.

Since this is a ReactJS project, I think people except it to be in JSX rather than other syntax sugars like CoffeeScript or TS. This will keep things nice and simple.

Also, ReactJS provides type checking via PropType which does not solve everything but still better than nothing.

**Comment by NogsMPLS** [comment]
possible alternative could be Flow.

**Comment by soyjavi** [comment]
Hi,

I'm so sorry but we wanna write all the components using JavaScript (JSX). In the previous version of React-Toolbox (june-jul) was written in CoffeeScript (because I am in love with .coffee syntax) but was a bad decision. We need write using *standards* for invite developers to help us.

Best,

**Comment by wagnermoschini** [comment]
you will start the es2015 version in a separate branch?

**Comment by soyjavi** [comment]
@wagnermoschini we already using ES6 (with babel)

**Comment by javivelasco** [comment]
I would like to keep using Babel and reduce dependencies in that sense. Components should be as little and easy as possible so I don't have clear thoughts about the return Typescript can provide. If the discussion take us to a big amount of people requesting this kind of support we can consider it but for now I think it's ok.

Closing to reduce noise, thanks for the feedback!

**Comment by xogeny** [comment]
For anybody who is interested, I made [an initial cut](https://gist.github.com/xogeny/3d360d13d54a97642bfa) at creating a `react-toolbox.d.ts` file.

@javivelasco would you accept a PR where this file was just bundled with `react-toolbox`?  That way, people wanting to use you library from TypeScript would be able to do so and it wouldn't change anything else about your project.

**Comment by javivelasco** [comment]
@xogeny as long as it's not adding too much stuff and contributors can update the lib without being worried too much about it, I would be very happy to accept your PR. As you can see, you're not the first one requesting it!

Thanks :)

**Comment by wrench7** [comment]
@xogeny did you end up making that PR for the TS definition file? I'm starting to spike TS with react-toolbox so having that as part of the codebase would be very useful :-)

**Comment by xogeny** [comment]
@wrench7 I'm not really using `react-toolbox`.  I created the definition file just to get started with it but then put `react-toolbox` to the side.  So I haven't really tested it too much.  I'm a little nervous to submit a PR and then have it not get any support.  Feel free to use it and/or submit your own PR though.  It should be pretty close in most regards since the documentation was quite clear.
