### ISSUE TITLE
Cannot call .focus() or .blur() on Input element (broke in 1.0)

### ISSUE THREAD

**Issue by Klathmon** [react-toolbox/react-toolbox#547]
Previous to 1.0, i could hang a ref on an `<Input>` element and would be able to call .focus() or .blur() on it and that would propagate to the underlying input element "somehow"...

Now with 1.0 a "Themed" element is returned as the ref, and .focus() and .blur() do not exist on this element so i'm getting "this.inputField.focus is not a function" errors in my project.

**Comment by Klathmon** [comment]
Just in case anyone else is having this issue, the only workaround i've found for the moment (which is really ugly) is to attach a unique className to the `<Input>` element and do a `document.querySelector(`.${inputElementClassname} input`).focus()` when i need to...

A possible fix would have the `<Input>` element hang a reference to the underlying element on it's props.

**Comment by felipeleusin** [comment]
I think the themed elements should handle setRef to the child automatically.

Em qua, 8 de jun de 2016 às 10:28, Gregory Benner <notifications@github.com>
escreveu:

> Just in case anyone else is having this issue, the only workaround i've
> found for the moment (which is really ugly) is to attach a unique className
> to the <Input> element and do a document.querySelector(.${inputElementClassname}
> input).focus() when i need to...
>
> A possible fix would have the <Input> element hang a reference to the
> underlying element on it's props.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/react-toolbox/react-toolbox/issues/547#issuecomment-224588453>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAKP8UM_1LbXzYNJyIyBAmZ_b1SP9evJks5qJsNygaJpZM4Iv-iI>
> .
>
-- 

Felipe Amorim

(21) 98121-0804

**Comment by ro-savage** [comment]
Having exactly the same issue. As usual, happy to do a PR if you'd like @javivelasco

**Comment by javivelasco** [comment]
Hi guys! Of course this is a side effect of using HOC for our components. They no longer have any methods (which I think is fine since you are not supposed to use them). Fortunately there are many workarounds.

Usually we want to use these methods when we want to communicate with the browser native `input` element of something similar. For those cases you can do something like this:

```js
ReactDOM.findDOMNode(this).querySelector('input').focus();
```

It will still work even if you add more HOC but you need to have just one `input` under the context element. I'm open to other solutions but I don't see as a good practice providing methods for components anymore.

**Comment by javivelasco** [comment]
I understand this is a valid solution so I'm closing. If you think we should do something to make it work better, please reopen!

**Comment by Klathmon** [comment]
This is a great solution, but I would just ask if a note can be added to the documentation somewhere?

**Comment by javivelasco** [comment]
Yeah, where do you think it fits?

**Comment by Klathmon** [comment]
I'm honestly not sure,  I *think* the only place it would really be needed is in the input element. I can't off the top of my head think of any of the other elements needing this, but i could be wrong.

Still, I think a small note there would have helped me save about an hour.

Thanks again for everything on this.

**Comment by javivelasco** [comment]
I'm going to leave this open as a reminder to add a note in the `Input` documentation. Thanks for your words :)

**Comment by AleksandrZhukov** [comment]
Faced with the same problem but with `Themed Menu`. Is possible to call `.show(), .hide()` etc on it?

**Comment by javivelasco** [comment]
Probably you can follow the same approach. You still can retrieve the instance using getDOMNode. In my opinion we should try to avoid as much as possible the usage of instance methods. For example the menu should be updated to track the active props even if it's keeping an internal state for rendering purposes. I'm not sure now if it's implemented, but try to change the active prop in the menu and see if it works. If it doesn't we should create an issue to fix it.

**Comment by javivelasco** [comment]
Since this is a common problem that appeared in more places, I've released a new version of [react-css-themr](http://github.com/javivelasco/react-css-themr) that implements the same approach as [react-redux](https://github.com/reactjs/react-redux) to deal with decorated component references.

You can see the details [here](https://github.com/javivelasco/react-css-themr/pull/10). Every component in react-toolbox with imperative methods such as the `Input` component should be decorated with `withProps` enabled. This allows you to retrieve the decorated instance with a ref and then the component instance with `getWrappedInstance` method. For now the `Input` is the one with methods but we should do the same for others bypassing methods to native elements.
