### ISSUE TITLE
It's not possible to config menu item vertical padding

### ISSUE THREAD

**Issue by paulocmoreno** [react-toolbox/react-toolbox#553]
Before anything else, thanks for your work! React Toolbox is a great UI library.

In my project I need to customize the react toolbox menu and I noticed that it's not possible to customize the vertical menu item padding. I can use the variable `$menu-padding` to config both the vertical and horizontal padding but I can't do the same with `$menu-item-padding` because the `_config.sass` of this component sets top padding as zero. Bellow the relevant SASS code:

```
.menuInner {
  padding: $menu-padding;
}
.menuItem {
  padding: 0 $menu-item-padding;
}  
```

Is this behavior correct? Shouldn't `$menu-padding` and `$menu-item-padding` have the same syntax?

If you agree I can open a pull request to change `$menu-item-padding` to set both the vertical and horizontal padding.

**Comment by javivelasco** [comment]
Thanks for your kind words! Well, I think it's like that because usually you don't have any padding following the spec. Anyway, I agree it's more flexible if it's customizable via variable. Feel free to PR that variable set to 0 as default, but it can't be the same variable for both horizontal and vertical though for obvious reasons :)

**Comment by paulocmoreno** [comment]
@javivelasco, I am sorry for the late response. I will await the cssnext version to be finished before opening a pull request. This configuration can be done via CSS therefore it doesn't worth the merge effort now. Thanks!
