### ISSUE TITLE
Slider component's knob initital position (component mount) and on drag

### ISSUE THREAD

**Issue by InSuperposition** [react-toolbox/react-toolbox#560]
I am using version 1.0 of react-toolbox. The initial position of the knob is not in the correct position when the Slider Component mounts. In addition, when attempting to drag the slider's knob the CSS transform does not update and remains in place, however the Slider's value does update correctly. I am seeing this behavior in the basic example below, no other CSS or JS dependencies are imported. 

```javascript
import React from 'react';
import { render } from 'react-dom';

import Slider from 'react-toolbox/lib/slider';

render(
  <Slider min={0} max={10} step={1} value={5} pinned snaps onChange={ x => console.log('value:', x)}/>,
  document.getElementById('app-root')
);
```

Thanks for the great work!

**Comment by javivelasco** [comment]
Thanks!

This is happening because the component does not hold the state for you. Since you are hardcoding the 5 value it will always have that value. The proper way to do this is to set a wrapper component or external store and subscribe to changes updating the value via props.

Check the documentation to see a working example, thanks! :)
