### ISSUE TITLE
Module build failed: ModuleNotFoundError ~normalize.css

### ISSUE THREAD

**Issue by mistre83** [react-toolbox/react-toolbox#564]
I'm trying to install react-toolbox on my project. 

All works fine but if i include:
`import 'react-toolbox/lib/commons.scss';`

I get the error:

```
ERROR in ./~/react-toolbox/lib/commons.scss
Module build failed: ModuleNotFoundError: Module not found: Error: Cannot resolve module '~normalize.css' in /Users/XXX/BitBucket/ProbeWebApp_1/node_modules/react-toolbox/lib
```

In my package.json i have this module:

`"normalize.css": "^4.0.0",`

**Comment by javivelasco** [comment]
Probably is because your configuration is not able to index the entry point of the package. Try adding to your webpack configuration `packageMains` with the values listed [here](https://github.com/react-toolbox/react-toolbox/blob/dev/webpack.config.development.js#L21) one of them refers to how normalize is indexed!

**Comment by barbalex** [comment]
@mistre83 did you manage to get this work? Or did you give up as I am about to?

**Comment by cementito** [comment]
The proposed solution worked for me.
I've update the resolve section of webpack.config.js as follows:

```
   resolve: {
    extensions: ['', '.scss', '.css', '.js', '.json'],
    modulesDirectories: [
      'node_modules',
      path.resolve(__dirname, './node_modules')
    ],
    packageMains: ['browser', 'web', 'browserify', 'main', 'style'],
  },
```
