### ISSUE TITLE
from Sass to CSS Next

### ISSUE THREAD

**Issue by nktssh** [react-toolbox/react-toolbox#565]
From notes on Release 1.0

> Anybody wants to port to CSS Next? 🙄

It will be really cool! I would like to take part in it.

Could you please describe this migration with more details?
E.g. it will be full migration to PostCSS or we can leave SASS? What plugins do you want to use? etc.

**Comment by javivelasco** [comment]
Yeah, I think we need to think about it. I migrate a project from `sass` to `cssnext` the last couple of days and it works great and it's clearly a sass killer. The only think to figure out is how to keep the customization via variables. With SASS it's possible to do so easily because of the `default` flat, but I'm not sure yet how does it work with postcss.

The plugins I used during the migration I've just commented were just `postcss-include` and `cssnext`. I'll try to give a deep thought during the weekend, leave your thoughts!

**Comment by wtgtybhertgeghgtwtg** [comment]
Would this be a Release 2.0 thing?  It seems like a pretty big undertaking with breaking changes.

**Comment by javivelasco** [comment]
Yep, totally

**Comment by ekosz** [comment]
@javivelasco I would take a look at how [Basecss](https://github.com/basscss/basscss/) [does it](https://github.com/basscss/basscss/blob/master/modules/margin/index.css#L52-L57). Basically they define all of their custom css properties at the bottom of every file. Then [you can override them](https://github.com/basscss/basscss/blob/master/docs/guides/FutureCSSSyntax.md#customizing-basscss) after importing the library.

**Comment by ekosz** [comment]
@javivelasco BTW if you would like help with this I'd be happy to take a swing at it on a branch.

**Comment by javivelasco** [comment]
This is great! I'd been thinking last week about this and I'm up to it. I'm going to work on this during the week. I my work project we moved to CSSNext without too much problems. The mixins thing can be achieved using [postcss-mixins](https://github.com/postcss/postcss-mixins). Apart from that there should be no problem, there are plugins to define and include variables and even to preserve the imported variable values and mimic default variables in sass.

During the week I'll create a new branch for the migration along with the setup. From there you can PR migrations :)

**Comment by lucasljj** [comment]
Now that #666 has been completed, can we close this?

**Comment by javivelasco** [comment]
Thanks for noticing!! 😬
