### ISSUE TITLE
Styles not being applied correctly

### ISSUE THREAD

**Issue by aubford** [react-toolbox/react-toolbox#567]
Brand new to React and React-toolbox.  I am trying to get the simplest version of the demo of the dropdown to work, but the styles aren't being loaded.  A "class" attribute is being applied, but it has no value.  I'm guessing it's something I'm missing in my webpack setup which I've supplied at the bottom.

![screenshot](https://cloud.githubusercontent.com/assets/14239952/16064715/e572ca8a-3260-11e6-92f2-e681856bb700.png)

![screenshot](https://cloud.githubusercontent.com/assets/14239952/16064632/212e2d54-3260-11e6-83fc-16413034cd9c.png)

![screenshot](https://cloud.githubusercontent.com/assets/14239952/16064638/2b788462-3260-11e6-8e7e-93db90a0ed00.png)

Result:
![screenshot](https://cloud.githubusercontent.com/assets/14239952/16064693/b1f96cd6-3260-11e6-8b72-f149e92a4a08.png)

**Comment by thearrow** [comment]
Try enabling modules for the css loader and see if that helps:

```js
{ test: /\.scss?$/, loaders: [ 'style', 'css?modules', 'sass' ] },
```

https://github.com/webpack/css-loader#css-modules

**Comment by aubford** [comment]
Thanks for the reply.  Unfortunately it didn't change anything.

**Comment by javivelasco** [comment]
Hey @aubford ! The problem is that your styles are not being loaded probably because of your `webpack` configuration. The weird thing is that you are not getting require errors but of course it is not getting any styles since the `class` attribute is empty. Please give a try to the [react-toolbox-example](https://github.com/react-toolbox/react-toolbox-example) repository. It has a working configuration for webpack.
