### ISSUE TITLE
Installation instructions and dependency instalation

### ISSUE THREAD

**Issue by tgwozdzik** [react-toolbox/react-toolbox#58]
Hi, you wrote a great library, but I had some issues installing it:

I installed react-toolbox via npm and had some trouble running some sample code like buttons or appbar (we are using webpack and sass in our project). I had to install react-transform-hmr, react-transform-catch-errors, redbox-react, extract-text-webpack-plugin, and I also needed to copy your sass configuration from your projects webpack config (the one with ExtractTextPlugin). After those steps, the library started to work properly but the steps to do that felt a bit awkward and unnecessary.

Maybe I missed something in the installation process (I read all about getting the right webpack config), or is it the right way to install the library? If it is, it would be awesome to have some more info about it in the README :)

Anyway, thx for some awesome piece of code! :)

**Comment by javivelasco** [comment]
Hi, thank you so much for your kind words and your feedback, I really appreciate it!

[Here](https://github.com/react-toolbox/react-toolbox-example) you have an example repository with setup. Actually you don't need HMR, nor redbox but they are nice for your development workflow. The minimal setup would include just webpack + css-loader + sass-loader. If you want to customize toolbox you should add [toolbox-loader](https://github.com/react-toolbox/toolbox-loader) too. I also recommend ExtractTextPlugin because some components need to check their position in the page at rendering time to work properly. Without the plugin the styles are injected in the DOM and when the load is big it's going to need some miliseconds to apply the styles... just enough to get wrong dimensions.

Most people would want to customize and the best way I found so far is to provide a SASS variables that will override the default ones. This means that you need to include in your build process the sass source instead of the final css build and what `toolbox-loader` does is to inject your variables just before every sass build in the project.

I know it could be kind of weird to install all of those dependencies to make the project work but to use css-modules webpack is a good choice. So there is no problem adding sass loader too and to get customization toolbox-loader. Sure it can be better explained in the `README`, we will update it.

Hope you find useful the example. Thanks for the feedback! :)

**Comment by javivelasco** [comment]
I'm considering a README update during the weekend and also I have a couple of things to fix. 
Closing, thanks!
