### ISSUE TITLE
<Avatar /> Issue with many different image dimensions.

### ISSUE THREAD

**Issue by gregegan** [react-toolbox/react-toolbox#585]
It looks like the `<Avatar/>` component is struggling with many different image dimensions. 

You'll also need to apply different styles based on portrait & landscape images.

![image](https://cloud.githubusercontent.com/assets/6665100/16282539/07a05528-387e-11e6-8c68-3ad65aa3b936.png)

```
const AvatarTest = () => (
  <div>
    <Avatar title="Javier" image="https://placeimg.com/1280/853/animals"/>
    <Avatar title="Javier" image="http://vignette2.wikia.nocookie.net/gameofthrones/images/9/95/Jon_Snow_(S05E05).jpg/revision/latest?cb=20150512181258"/>
    <Avatar title="Javier" image="https://upload.wikimedia.org/wikipedia/en/5/50/Tyrion_Lannister-Peter_Dinklage.jpg"/>
    <Avatar title="Javier" image="https://s-media-cache-ak0.pinimg.com/564x/68/05/93/68059311268ffab3d353714dab25d089.jpg"/>
  </div>
);

return <AvatarTest />

```

**Comment by nastiatikk** [comment]
Also it seems like portrait pictures are not aligned vertically:
![image](https://cloud.githubusercontent.com/assets/4110509/16281729/ab5f5398-3893-11e6-9902-3796960ddb8a.png)

**Comment by gregegan** [comment]
`<Avatar title="Javier" image="http://vignette2.wikia.nocookie.net/gameofthrones/images/9/95/Jon_Snow_(S05E05).jpg/revision/latest?cb=20150512181258"/>`
![image](https://cloud.githubusercontent.com/assets/6665100/16282092/1458b4f6-387c-11e6-8cd9-f6fa3c15a2be.png)

**Comment by javivelasco** [comment]
Yep. We wanted at first to add those images as background images to allow to be covering the whole space. The problem is that semantically this is not correct in HTML so we assume you will provide cropped images with the correct size.

**Comment by nastiatikk** [comment]
@javivelasco Sorry, but what exacly do you mean by "semantically not correct in HTML"? I can see how it can be semantically incorrect to put image to CSS background property if image has a "value". But in this case image will need to have "alt" attr to provide this value. But I don't see this attr implemented to this component, so I'm confused

**Comment by javivelasco** [comment]
Well, in my mind, an image that is part of the design and it's not important for the content should be definitively a background image. Otherwise, an image that is part of the content should be an `img` tag in the HTML regardless of providing an `alt` attribute for screen readers and image load failing.

ATM of implementing this I was assuming everybody would give cropped images as avatars since it's a common practice. I've just added a `cover` prop so if your image is not a square you cant set it to `true` and it will be displayed as a background image with cover sizing.

**Comment by nastiatikk** [comment]
Thank you Javi!

Regarding 'semantically correct' comment I wanted to add that `alt` should be there not just for screen-readers but also to cover cases when image link is broken (because if image is important for content users must be able to see what is there if image is not displayed). But this is an off-top :-)

Thank you again for this fix! 🙇

**Comment by javivelasco** [comment]
No problem @nastiatikk! Remember you can provide the full image tag as well. It can include alt too. Actually a first implementation included even a fallback but it was too crazy 😱
