### ISSUE TITLE
Confused on how to import theme and customize it

### ISSUE THREAD

**Issue by mistre83** [react-toolbox/react-toolbox#595]
I've spent many days to try understand how to setup theme correctly, without a good result...

I've read the documentation about react-toolbox and react-css-themr without luck...

So, i have wrote this:

```
const contextTheme = {
    RTCard: require('react-toolbox/lib/card/style.scss')
};

const content = (
    <ThemeProvider theme={contextTheme}>
        <Index />
    </ThemeProvider>
)

ReactDOM.render(content, document.getElementById('content'));
```

In this file (where i render the entire application) i will have to include all the themes my application use? For example, my application in its "life" use Card, List, ListItem and so on. **I have to include all the RT* in this file ?**

For example, documentation for Card say:

_This component and all of its subcomponent are themeable by context using the key RTCard._

But, how i can use this "keyword"?

Even in the Card documentation Theme are: large, small, subtitle and title -> but, how i use it ?

I've tried to take a look to react-toolbox-example but is very very basic and there are just two button on it...

**Comment by javivelasco** [comment]
Hi! What you did in the code you've attached is to set a context theme for the component with the key `RTCard`. If you render a RAW Card component with any of its subcomponents, it will know how to apply the className properties yo gave via context. This allows you to avoid using CSS Modules if you want because you can import React Toolbox components without any CSS import and customize the context with global classNames or whatever you need.

So importing RAW components means that you need to provide themes manually and it can be done via props or context. If you include, for example, the raw `Dropdown` component you have to add to the context the `RTDropdown` theme if you want it to be styled.

Anyway if you are using CSS modules and don't need to customize a lot of stuff, you can import themed components and forget about providing themes. You just need to do it in case you want to customize stuff

**Comment by mistre83** [comment]
Hi thanks for your reply.

I can say that i want to use basic theme and just customize something, so for now i think is good to import "all theme" and just make some customization.

But, i did tried to do it since this morning and right now i'm not able to supply my custom style.

In my webpack i have configured all right (i think...) because i can load components (Card, and so on) and they are "basic" styled.

Now, what i want to do is for example change the color title to a card, and this is my code:

```
import theme from './CardStatus.scss';
import icons from '../../constants/icons';

const CardStatus = ({ children, ...other}) => (
    <Card {...other} style={{width: '270px', marginBottom: '1rem'}} theme={theme}>
        <CardTitle
            {...other}
            avatar={<Avatar
                        icon={other.status == '0' ? icons.check_circle :
                              other.status == '1' ? icons.warning : icons.error}
                        theme={theme.avatar} />}
            theme={theme}
        />
        <CardText>{other.value}</CardText>
    </Card>
);

CardStatus.propTypes = {
    children: PropTypes.node
};
export default CardStatus;
```

In CardStatus.scss i have this css:

```
.title {
  color: yellow;
}
```

Reading the documentation the title CSS class is used to customize the CardTitle component, but.... my CardTitle text appear even black.... 

I did tried with many other components and the result is even the same: no style applied.

If you want, i can provide my webpack configuration, but i have "copied" it from react-toolbox-example and as i did said, all components are basic "styled", constant and colors works properly....

I'm sorry, i know this is not the place to ask question but..... i'm desperate ... :D

**Comment by lwhorton** [comment]
hey @javivelasco really great job on this library. I have a similar question, but regarding "global" themes such as global colors, global padding, and others defined [here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/_globals.scss). Is there an equivalent `RT*` namespace I can use to theme these? My build process does not easily afford scss, and if possible I would like to avoid that dependency.

**Comment by mistre83** [comment]
I close this issue too, the problem related to original question was about an older version of react-toolbox. Updated to 1.0.1 all works.

**Comment by javivelasco** [comment]
Great @mistre83! @lwhorton you can totally avoid using sass in your workflow but we don't have an example now, I can give you insights thought.

A way to provide styles as you can see in the README is to define a `theme` object as pass it down with the context using `ThemeProvider`. Each key of the theme corresponds to a component and the value is an object as well. This object has to implement the component theme API and the values of each className is the string that finally corresponds in the final CSS. If you define a theme this way, you can require components **without** styles which means that no scss will be required. They will get the classnames they should use from the context thought.

What you need to do to use the styles is to compile the SASS code into plain CSS customizing variables to fit your needs. The classname mappings implementing the API of each component should correspond to this final build. It may look complicated but it's all about compiling SASS and tell the components what are the classes. Still you might find a problem when your sass is compiled because some components have the same classnames. This is because using css modules allows you to do so...

I'd like to hear your feedback working this way :)
