### ISSUE TITLE
Custom Styles Not Overriding

### ISSUE THREAD

**Issue by adrianmc** [react-toolbox/react-toolbox#613]
I am doing the official Customizing Components example with the AppBar. I've copied it word for word (except for the colour) but my styles are getting overwritten by the defaults for some reason.

![screen shot 2016-07-06 at 6 06 55 pm](https://cloud.githubusercontent.com/assets/943555/16615996/7ade7caa-43a4-11e6-99f7-a7c644e6caa2.png)

Notice how my `background-color: tomato` is crossed out because the default `background` property supersedes it.

I'm using [React Storybook](https://github.com/kadirahq/react-storybook), which is just a Webpack app that renders React components in a sandbox.

This is my Webpack config:

```
module.exports = {
  module: {
    loaders: [
      {
        test: /\.scss?$/,
        loader: 'style!css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!sass',
        include: path.resolve(__dirname, '../'),
      },
    ],
  },
};
```

What am I doing wrong?

**Comment by javivelasco** [comment]
I think the issue here is that you are providing the same priority to both selectors and the style injecting appears first for your style and later for react-toolbox's. This means that react toolbox styles are being declared later with the same priority as yours and that's why they get overridden. To solve this issue you can go with two options:

1 - Make sure your style is dumped *after* react-toolbox's. Maybe changing your import order is enough.
2 - Boost priority providing a className. For example you can give `tomatoAppBar` classname and write your selector as `tomatoAppBar.appBar`

Close if it's solved!

**Comment by adrianmc** [comment]
Good call! Thanks :)

**Comment by gregegan** [comment]
@adrianmcli can you share your full storybook webpack config? I am having trouble getting the styles 

```
ERROR in ./~/react-toolbox/lib/button/theme.css
Module parse failed: /node_modules/react-toolbox/lib/button/theme.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
```

`import { Button } from 'react-toolbox/lib/button';`

**Comment by adrianmcli** [comment]
@gregegan That project was a long time ago.

It sounds like you need to install a CSS loader: https://github.com/webpack-contrib/css-loader

**Comment by kuka-radovan** [comment]
@adrianmcli  I have the same problem as @gregegan also with installed css-loader. My storybooks webpack.config file looks like this:

```
module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              modules: true,
              importLoaders: 1,
              sourceMap: true,
              localIdentName: '[name]--[local]--[hash:base64:8]'
            }
          },
          {
            loader: 'postcss-loader'
          }
        ]
      }
    ]
  }
}
```
