### ISSUE TITLE
Bundle size.

### ISSUE THREAD

**Issue by Stalso** [react-toolbox/react-toolbox#620]
Hello. It is cool set of components, but I have some misunderstanding. When I include your components in clear application (I am using  [react-bolierplate](https://github.com/mxstbr/react-boilerplate) )  my `300 kb` bundle turns into `1,7 mb` bundle. Is not it too big? I am new in react, but I think, that set of components should not be so large. At first, it was 3 mb, but I replaced such imports:

    import { Card, CardMedia, CardTitle, CardText, CardActions } from 'react-toolbox';

On this

    import { Card, CardMedia, CardTitle, CardText, CardActions } from 'react-toolbox/lib/card';

Bundle became smaller (`1.7 mb` from `3 mb`), but it is still too big

**Comment by javivelasco** [comment]
Hi! I didn't measure the final bundle size but you should always import as in your second example. In the first ase you'd be importing the whole library with every single component and every style, that's why the final build get's that big. I'm not sure why it's that big... the only dependencies we keep are `classnames`, `core-js` and `react-css-themr`. Maybe you are bundling two Reacts of something?

**Comment by developit** [comment]
@Stalso If you're concerned about bundle size, react-toolbox works well with Preact. There's a full example [here](https://github.com/developit/preact-compat-example) - bundle size for the entire app is only 60kb (14kb gzipped).  Generally, @javivelasco's work is portable to alternative implementations because it's well-written idiomatic React 🙇

**Comment by wtgtybhertgeghgtwtg** [comment]
I'm not sure about `1.7 mb`, but the library does usually end up larger than it has to be.
Even when you `import` from `react-toolbox/lib/Component`, you still end up importing a bit more than you need (i.e. all of `identifiers.js`).
`PropTypes` also seem to not want to come off.  I had thought that it was just an issue with my build, but about a thousand of them are present on [the demo site](http://react-toolbox.com/docs.js), as well.

**Comment by developit** [comment]
@wtgtybhertgeghgtwtg @Stalso - you can profile your webpack build and drop the JSON output into [webpack-visualizer](https://chrisbateman.github.io/webpack-visualizer/). That will tell you exactly where the weight is.  CSS Modules have a cost, the various libs/utils all have cost - the list goes on.  Tree Shaking helps, though I'm not sure it's yet possible to get a perfect tree shake of react-toolbox since it likely wouldn't be supported via Rollup.

**Comment by wtgtybhertgeghgtwtg** [comment]
Tree Shaking would help, but currently the only way I see to do that with `react-toolbox` as is, at least as far as `webpack@2` is concerned, to `import` from `react-toolbox/components/Component` with `babel-loader`.  Since transpiling `node_modules` isn't a particularly elegant solution, a `jsnext:main` might not be a bad idea.

**Comment by developit** [comment]
The issue with jsnext:main is that preact-toolbox is more than just js - it contains sass, jsx, etc. It also relies on CSS Modules.

**Comment by wtgtybhertgeghgtwtg** [comment]
`jsnext:main` might be a somewhat misleading name, but it shouldn't cause any issues with non-Javascript assets.  It just points to a build that uses ES6 `import`, instead of the build `main` points to, which uses `require()`.

**Comment by developit** [comment]
It just assumes a lot about the bundle (like that a bundler is being used at all). I agree though, we are doing recursive module bundling at Synacor to apply client branding/config to all modules in a single build.

**Comment by wtgtybhertgeghgtwtg** [comment]
It assumes that, if the user has set up their bundler to use `jsnext:main`, that they want to use `jsnext:main`.  Nothing changes unless the user opts in to use it.

**Comment by developit** [comment]
I will say though - doing this really increases the likelihood of breaking changes when updating dependencies. For example, react-toolbox changed their build process a bit to get rid of `toolbox-loader`, and I had to update a few of my own projects' Webpack configs since they had to be tightly coupled in order to know how to properly build the library.

**Comment by wtgtybhertgeghgtwtg** [comment]
If you don't add `jsnext:main` to your `packageMains`, it shouldn't affect your build process.  If you're running `webpack@2` and want to see if it'll affect your build, `redux` and `react-router` have `jsnext:main` defined.

**Comment by developit** [comment]
I know that, I've been using Webpack this way since late 2015 😋

It's just a very indirect means of achieving a smaller bundle size.

**Comment by wtgtybhertgeghgtwtg** [comment]
Indirect or not, it's an effective way to allow the user to achieve a smaller bundle size.

**Comment by Stalso** [comment]
Thanks,  I will try all of your proposals,  and write about result.  By the way,  I am trying to use react-toolbox in this boilerplate https://github.com/mxstbr/react-boilerplate

**Comment by wtgtybhertgeghgtwtg** [comment]
Speaking of `PropTypes`, the new version of `[babel-plugin-transform-react-remove-prop-types](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types)` wraps `PropTypes` in a `NODE_ENV` check, so they'll be removed in production.  I haven't checked exact numbers, but it should shave off a handful of kilobytes.

**Comment by javivelasco** [comment]
Great discussion! Since apparently there no actual issue I'm going to close. If some of you find useful to add a section in the docs with information about optimizing the bundle size, please refer to a new issue or open a PR, I'd really appreciate it! 😬
