### ISSUE TITLE
webpack without ExtractTextPlugin

### ISSUE THREAD

**Issue by InfernoZeus** [react-toolbox/react-toolbox#636]
In [this comment](https://github.com/react-toolbox/react-toolbox-example/issues/13#issuecomment-218249219), @javivelasco suggested that it should be possible to configure webpack without `ExtractTextPlugin`. I've been trying to set that up without much success. The CSS is succesfully injected into a style tag using the sass/css/style loaders, but the button doesn't have any classes, and consequently doesn't receive any of the styling.

index.jsx
```
import React from 'react';
import {render} from 'react-dom';
import { Button } from 'react-toolbox/lib/button';
render(<Button label="Hello World!" />, document.getElementById('app'));
```
webpack.config.js snip
```
...
  resolve: {
    extensions: ['', '.scss', '.css', '.js', '.jsx', '.json'],
  },
  module : {
    loaders : [
       ...
      {
        test: /\.scss$/,
        loaders: ["style", "css", "sass"]
      }
      ...
    ]
  }
...
```

Result:
![screenshot from 2016-07-12 11-49-51](https://cloud.githubusercontent.com/assets/283676/16762902/d4771098-4826-11e6-9dde-70b000878e69.png)

**Comment by javivelasco** [comment]
You need to configure webpack to use css modules by default with the `modules` option in the loader. Otherwise the imported object does not have the classes to put them into the nodes. The only issue you'd have without the extract plugin is with components that need to read their dimensions from the DOM once mounted because sometimes by the time they are mounted in the first load, styles are not applied yet so the dimensions are wrong

**Comment by InfernoZeus** [comment]
@javivelasco Aha! That worked perfectly. I've also noticed that react-toolbox-example uses the postcss loader between sass and css loaders, but that's not mentioned in the installation any where. Is this still recommended?

**Comment by javivelasco** [comment]
Yeah, it's used to add vendor prefixes with the `autoprefixer` so I'd recommend it. Since it's useful to postcss styles, we are making the switch from SASS to CSSNext. I think it's going to be more flexible and easier to customize, I'm currently making some changes and also there is a WIP PR migrating some styles. Coming soon.... 💃

**Comment by InfernoZeus** [comment]
Ok, thanks for your help! :)

**Comment by landabaso** [comment]
@InfernoZeus, could you please elaborate?

In a `target: node` environment using style-collector-loader:

This **does NOT** set the class name:
```{ test: /(\.scss|\.css)$/, loader : 'style-collector!css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass', include: /react-toolbox/ }```

while this sets the class name:

```{ test: /(\.scss|\.css)$/, loader : ExtractTextPlugin.extract('style-collector', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass'), include: /react-toolbox/ }```

I'm interested in NOT using `ExtractTextPlugin` but I'm not sure how to make SSR to work without it.

**Comment by InfernoZeus** [comment]
I haven't verified that my configuration works with SSR, as I wasn't interested in that setup. For me, the key to getting the class names applied was `css?modules`, but it looks like you've already got that. Perhaps @javivelasco knows how to help? Sorry!

**Comment by javivelasco** [comment]
I've never used webpack in the backend. To make SSR work with toolbox I've used a css-modules hook.

**Comment by landabaso** [comment]
Thanks @InfernoZeus, @javivelasco. Can css-modules hook be used to avoid the FOUC (Flash Of Unestyled Content) problem? In other words, can react-toolbox be used with SSR and without FOUC?

**Comment by javivelasco** [comment]
Well the FOUC happens because the page is rendered without styles and then they are inyected once the page is loaded. If you want to avoid the `ExtractTextPlugin` I think it's not possible to skip the FOUC. My advice is you generate a build with all CSS extracted and to allow SSR with either webpack or the require hook.

Also, beware some components may don't work because of the same FOUC because as I said up there, some of them need to take the displayed space once they are rendered and without styles the read value would be wrong

**Comment by landabaso** [comment]
FYI @javivelasco , @InfernoZeus and other people that find this thread in the futur.

It is possible to achieve:

1) Server rendering
2) No need to use ExtractTextPlugin
3) No FOUC

I managed to make it work using [isomorphic-style-loader](https://github.com/kriasoft/isomorphic-style-loader).

In case someone else needs to make it work in a normal react-router scenario I suggest to read this [thread](https://github.com/kriasoft/isomorphic-style-loader/issues/15).

One might still find the issues that @javivelasco mentioned above.

Thanks

**Comment by javivelasco** [comment]
Oh nice, I didn't knew about it! Anyway I'm curious about why do you want to avoid extracting the CSS in production. IMO is a good benefic

**Comment by landabaso** [comment]
Because of the FOUC...

**Comment by javivelasco** [comment]
But you avoid FOUC extracting CSS :S

**Comment by landabaso** [comment]
To be honest, there are so many technologies and stuff to learn and to make them work together...  webpack+react+SSR+No FOUC+react-router+express+react-toolbox+isomorphic-style-loader+...

@javivelasco I managed to make react-toolbox work using isomorphic-style-loader mentioned above.

I don't know exactly what you mean with extract CSS. Do you mean to extract the whole CSS (taking into account CSS-modules) of react-toolbox and embed it all in html?

What is the difference compared to isomorphic-style-loader? Even worse. What is the point in  isomorphic-style-loader?

There's no clear documentation since I'm navigating through so many different libs and projects which most of them are constantly changing / beta soft. I'm not complaining because you are delivering great soft for free but trying to make everything work together is a bit frustrating.

Con una cerveza fría a lo mejor lo veo más claro.
