### ISSUE TITLE
Ref to ListCheckbox is null

### ISSUE THREAD

**Issue by ktmn** [react-toolbox/react-toolbox#64]
```
<ListCheckbox 
    ...
    ref={(checkbox) => console.log(checkbox)}
/>
```
Output:

    null

[React docs](https://facebook.github.io/react/docs/more-about-refs.html#the-ref-callback-attribute):

The ref attribute can be a callback function, and this callback will be executed immediately after the component is mounted. The **referenced component will be passed in as a parameter**, and the callback function may use the component immediately

Tried non ES approach too in case it was Babel's fault or something

```
ref={function(checkbox){console.log(checkbox);}}
```

still null...

Is there any other way I can keep track of the checkbox statuses in my list? The SyntheticEvent I get when using onChange doesn't seem to give me a simple way to get the checked status either. 

With mui I was able to do isChecked() on the ref, and SyntheticEvent.target.isChecked() also if I recall correctly.

**Comment by javivelasco** [comment]
Ok, we are experimenting with pure components in a new branch. As soon as we get it done I think you're gonna have callbacks to track the status from a higher order component instead of using methods. I would like to dedicate more time to it than supporting refs and stuff but it's definitely a bug. Let's label like it and try to get it done asap.

Thanks!

**Comment by javivelasco** [comment]
Hi @ktmn!

As you can see [here](https://github.com/react-toolbox/react-toolbox/blob/pure-components/components/checkbox/index.jsx), the new checkbox implementation has no state. This means that you will be responsible of storing the checked value somewhere else and subscribe to the changes by using `onChange`. In this scenario you'd be responsible from handling the value change.

Does it work for you?

**Comment by ktmn** [comment]
Looking good, thanks!

**Comment by yves-s** [comment]
As I try to use an input with the `ref`-attribute I don't get the value out of the element, I only get the components settings:

```
<Col xs={12} sm={5}>
    <Input type='text' label='Name' name='name' ref={(node) => (console.log(node))}/>
</Col>
```  

Output:
```
Themed: {
	_reactInternalInstance: ReactCompositeComponentWrapper,
	context: Object,
	isMounted:(...),
	props: Object,
	refs: Object,
	replaceState:(...),
	state: null,
	theme_: Object,
	updater: Object,
	__proto__: ReactComponent,
}
```
That probably makes sense, because I'm referencing the component instead of a native input element but shouldn't it be possible to get the inputs value out of the reference as well? As a workaround I'm handling the value change with a method as you suggested.

```
<Input type='text' label='Name' name='name' onChange={handleChange.bind(this, 'name')} />
```

**Comment by javivelasco** [comment]
You can still access the reference of the component using `refs` inside the `themr` decorator. The `onChange` callback should be passing the `event` anyway so you have access to the name!
