### ISSUE TITLE
How to replace Toolbox App.jsx using the newer Toolbox version

### ISSUE THREAD

**Issue by jramon** [react-toolbox/react-toolbox#656]
I replaced it with a plain div but it seems that that scrolling the viewport is broken now. Is there anything we should do to setup the app without App.jsx wrapper?

**Comment by javivelasco** [comment]
Hi! You don't need to do anything special. As long as I can remember, the `App.jsx` was used to:

- Add resets and common styles that react-toolbox needs.
- Allow to easily block the viewport without losing scroll position.

This was creating some issues IMO. For example, the browser cannot scroll down after a reload until where it was before reloading because the actual scroll was always 0. I think is not the best way to do it so we've changed the `Overlay` to block the body.

Just removing the wrapper it should be enough. [This](https://github.com/react-toolbox/react-toolbox/blob/f16934c95ec251e8893c81d7291efe4c1c9ac8d9/docs/app/index.jsx#L15-L22) is how it was used. Now the wrapper is just not present as you can see [here](https://github.com/react-toolbox/react-toolbox/blob/dev/docs/app/index.js).

Probably you have some extra `div` hiding the overflow or something similar. I'm going to close this issue for now because I don't think it's an actual issue in the project. Let me know if you can fix it.
