### ISSUE TITLE
Conditional display of button

### ISSUE THREAD

**Issue by Stalso** [react-toolbox/react-toolbox#671]
Hello. I have such code to display button conditionally

            {currentUser ?
              <Button onMouseUp={this.props.onLogOff} label = 'LogOff'></Button>
              : null}

 If `currentUser `is not false, `LogOff ` button appears. When I press `LogOff`, `currentUser` is setted to false, and button disappears. Everything seems to work, but I also get such error in console:

    Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.
        warning @ warning.js:44
        getInternalInstanceReadyForUpdate @ ReactUpdateQueue.js:45
        enqueueSetState @ ReactUpdateQueue.js:192
        ReactComponent.setState @ ReactComponent.js:67
        RippledComponent._this.handleEnd @ Ripple.js?2101:89

What I am doing wrong?

**Comment by javivelasco** [comment]
You are doing it right. The problem here is that the `Ripple` component performs a `setState` which corresponds to deactivation `onMouseUp` of the `document`. This allows to keep the ripple until that moment.

You are calling `onMouseUp` and unmounting the component **before** the `document` mouseup happens so when the callback function that set the state is executed, the component was already unmounted causing the error.

This is a bug. The proper behavior would be to retire document event listeners related to the ripple if there are some still active in `componentWillUnmount`.
