### ISSUE TITLE
More detailed documentation on how to get setup with webpack

### ISSUE THREAD

**Issue by dalexander01** [react-toolbox/react-toolbox#673]
I'm currently struggling getting react-toolbox to work following the directions included on the install page:
http://react-toolbox.com/#/install

The documentation around webpack, scss, sass-loader, etc. on that page is very vague. I'm currently getting a bunch of Error: Cannot resolve module 'style' errors, and it seems that this is a common occurrence for new users. I'm not really sure what exactly I need to do to get things working. It would be helpful to include step by step directions on getting something simple setup and running.

**Comment by javivelasco** [comment]
Well, I think it would be an error to focus too much on how to configure webpack in the documentation. To show how a setup example can be we already have a [repository](https://github.com/react-toolbox/react-toolbox-example) in the organization Github.

Anyway, for the next major we are moving to PostCSS and both the documentation and playground needs to be updated. The plan is to include more detailed pages about configuration, theming, etc instead of just one huge page with all the information.

In any case, creating a page with detailed webpack configuration should not be done in the current version but in the future one with PostCSS. I'm editing #666 to checkbox that. Hope you get it working.
