### ISSUE TITLE
Custom theme does not get applied to components.

### ISSUE THREAD

**Issue by alexanderharm** [react-toolbox/react-toolbox#688]
I'm having issues with theming of components. I followed directions in the installation guide but styles do not get applied. I found someone with the exact same problem on SO: https://stackoverflow.com/questions/38026782/react-toolbox-how-to-apply-theme

My theme reads like this
    
    // auth.component.css
    .cardTitle {
      background-color: rgb(103,58,183);
    }
    .subtitle {
      outline-color: rgb(238,238,238);
    }
    .title {
      outline-color: rgb(250,250,250);
    }

My component
    
    // auth.component.tsx
    const theme = require('./auth.component.css')

    class Auth extends React.Component {

      render () {
        return (
          <Card style={{width: '350px'}} theme={theme}>
            <CardTitle
              title="Sign in"
              subtitle="Please enter your credentials"
              className={theme.cardTitle}
            />
            <CardText>
              Bla
            </CardText>
            <CardActions>
              <Button label="Sign in" primary={true} raised={true} />
            </CardActions>
          </Card>
        )
      }
    }

What are we missing?

**Comment by javivelasco** [comment]
There is some stuff to consider when you are theming a component. First of all you have to understand that what we are doing passing a custom theme object is to *append* custom classNames to the ones defined internally.

Custom classNames should implement a higher priority than the default ones to successfully override them. Also you have to take into account that internal classes may not have the minimal priority though. 

In your example you are passing a `subtitle` class in the theme object. The style has the minimal possible priority. If you look at the default style definition you would see [this](https://github.com/react-toolbox/react-toolbox/blob/dev/components/card/theme.scss#L68-L70). The priority of this rule is `.cardTitle.subtitle { ... }` so to override it you can do two things:

- Write a selector with the same priority and make sure that your custom CSS is placed **after** the default one.
- Boost priority adding a custom className.

I'd suggest the second one since it's more controlled. You would have to give a className to your card `myThemedCard` and then write a selector like `.myThemedCard cardTitle.subtitle { ... }`. That would work for sure.

I know is a pain in the ass to override priority sometimes. We should migrate to the lowest possible priority every selector and try to keep them as the minimal to make theming easier. Sometimes we need className modifiers that can't hold the minimal priority though so we can't cover every case anyway.

**Comment by alexanderharm** [comment]
Sorry, am a total noob regarding this. If I follow your advice how do I pass in my class? Passing it in via `className` does of course not work, since the nested elements receive a custom class, e. g. `theme__title__xxxxx`, so my styling not applied.

Can you provide a working example that styles nested elements?

**Comment by alexanderharm** [comment]
It works if I set `className="authCardTitle"` of `CardTitle` and have in my `CSS`:

    @import "~react-toolbox/lib/colors";

    .authCardTitle {

      background-color: $palette-deep-purple-500;

      div {

        h5 {
          color: $palette-grey-50 !important;
        }

        p {
          color: $palette-grey-200 !important;
        }
      }
    }

But it doesn't feel right... but then I am kind of clueless :-)

**Comment by javivelasco** [comment]
You can theme a `Card` component to hold a pink subtitle like this:

```scss
// theme.scss
.themedCardTitle.cardTitle {
  .subtitle {
    color: pink;
  }
}
```

In the original styles we use a selector to set the color like `.cardTitle .subtitle`. Your custom should boost priority so in the example we are adding an extra class for the themed title. Then you can use it like:

```js
// TestTheme.js
import React from 'react';
import { Card, CardTitle, CardText } from 'react-toolbox/lib/card';
import theme from './theme.scss';

const TestTheme = () => (
  <Card>
    <CardTitle
      className={theme.themedCardTitle}
      title="Normal title"
      subtitle="I should look pink"
      theme={theme}
    />
    <CardText>Some text</CardText>
  </Card>
);

export default TestTheme;
```

The `className` is provided to the `CardTitle` and then the theme is passed down in the `CardTitle`. This way we are adding a new subtitle class we can target as a child of `themedCardTitle` class.

I've tested in the example repository and works perfectly.

**Comment by alexanderharm** [comment]
YEAH, thanks a million and keep up the good work!

**Comment by javivelasco** [comment]
No problem! Thanks :)

**Comment by resagit** [comment]
Most programming languages, frameworks tools etc have a simple hello world kind of an intro into their own world. I find that missing with react-toolbox. Right after npm'ing the toolbox module I realized there were a few other tiny details that I needed to take care of separately. All of which are important but not discussed properly on their website. Instead, these details are discussed in various other places. After wasting much of the day collecting these responses I was lucky to run my first layout only to see black circles. I had already worked on Material-UI without much problems earlier. All of the styling requirements were handled well with radium. I was exploring a newer framework that had layouts and so exploring react-toolbox. I am running against a deadline and so gonna look else where maybe react-mdl.
  
Also the responses from the developers themselves are a bit strange. Instead of an elaborate verbose response a few simple examples would suffice most queries. Maybe they mean well but most developers work against deadlines. They need code to be working and are not interested in knowing elaborate details ...

For instance "enble css modules webpack" and to handle """Module build failed: Error: composition is only allowed when selector is single :local class name not in ".raised", ".raised" is weird """ you must have these lines for a loader in webpack config..

{
  test: /\.css$/,
  loader: 'style!css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]' 
}

or 

for webpack 2

{
    loader:'css-loader',
    options:{
                modules:true,
                importLoaders:1,
                localIdentName:'[name]__[local]___[hash:base64:5]'
            }
}

and this must be mentioned on the react toolbox webpage because apparently otherwise you cannot run your first hello world. This gives you a nice page with black circles for a ripple.

**Comment by javivelasco** [comment]
@resagit actually there are example repositories and you don't even need to use webpack at all. The documentation itself is an example about how to use react-toolbox but it is very difficult to take care of responses in technical configuration issues, fixing bugs, releasing, updating changelogs, thinking about the future of the library... etc. Plus, you said *developers*, actually is *developer* and plenty of awesome sporadic contributors.

**Comment by aayushis12** [comment]
@javivelasco If not using scss, how to achieve styling a subtitle of a card using plain css?

**Comment by javivelasco** [comment]
@aayushis12 you'd have to use CSS Modules or to build manually an object with the Card theme shape corresponding to the classNames you want to use.

**Comment by aayushis12** [comment]
Hi @javivelasco , I have a component like this
```
<ThemeProvider theme={theme}>
					<Card style={{width:'350px'}}>
						<CardMedia aspectRatio="wide" image=""/>
						<CardTitle title="Avatear here" className={theme.card-title}/>
					</Card>
				</ThemeProvider>
```
I have imported my scss and react-toolbox components like this-
```
import theme from './assets/theme/theme';
import './assets/theme/theme.css';
import ThemeProvider from 'react-toolbox/lib/ThemeProvider';
import {Card,CardTitle,CardMedia} from 'react-toolbox/lib/card';
```
In my App.scss file, I have-
```
.card-title.cardTitle{
  .title{
    color: red
  }
}
```
But by doing this, I get this error that

> 'title' is not defined  no-undef

Please suggest what should be done here!Thanks

**Comment by rubenmoya** [comment]
Please, next time open a new issue with your problem, this issue was closed a while ago!

Your problem is probably because `theme.card-title` this is an invalid syntax. Try to add the theme property to the `<Card />` component and override from there

**Comment by aayushis12** [comment]
Hi @rubenmoya, sorry to bother you. 
But with this too-
```
<div> 
				<Header/>
					<Card style={{width:'350px'}}>
						<CardMedia aspectRatio="wide" image=""/>
						<CardTitle title="Avatear here" className={theme.card-title} theme={theme}/>
					</Card>
					</div>
				
``` 
I get the same error as

> 'title' is not defined  no-undef

I am not sure why. If you could please help, that would be great.

**Comment by rubenmoya** [comment]
You have to add the `theme` prop to the `Card` component:

```
<div> 
  <Header/>
  <Card style={{width:'350px'}} theme={theme}>
    <CardMedia aspectRatio="wide" image=""/>
    <CardTitle title="Avatear here" />
  </Card>
</div>
```

and then look how the title is styled through [the css](https://github.com/react-toolbox/react-toolbox/blob/dev/components/card/theme.css) and try to override it :)

**Comment by aayushis12** [comment]
Did that too! doesn't work @rubenmoya

**Comment by rubenmoya** [comment]
Are you overriding the correct styles?

**Comment by aayushis12** [comment]
I think so. This is present there ```
.cardTitle {
  align-items: center;
  display: flex;

  & [data-react-toolbox='avatar'] {
    margin-right: calc(1.3 * var(--unit));
  }

  & .title {
    font-size: calc(2 * var(--unit));
    font-weight: 500;
    letter-spacing: 0.02em;
    line-height: 1;
    margin: 0;
    padding: 0;
  }

```
in the [link ](https://github.com/react-toolbox/react-toolbox/blob/dev/components/card/theme.css)that you have sent me  @rubenmoya

**Comment by aayushis12** [comment]
Am I supposed to import something in my scss file? @rubenmoya

**Comment by rubenmoya** [comment]
You are importing the `theme` from `import theme from './assets/theme/theme';`, are the styles there? I think you're trying to override them in `App.css`, but you're passing `theme.css` to the `Card`

**Comment by aayushis12** [comment]
the file is app.scss, for importing theme.scss what should I do? @rubenmoya
