### ISSUE TITLE
Difference in using react-toolbox and Material-UI

### ISSUE THREAD

**Issue by lxibarra** [react-toolbox/react-toolbox#690]
Hello i was checking out this repo and saw that it was very similar to this one http://www.material-ui.com/#/ that also can be used directly with react. 

Is there any difference between the two and why would i want to use one over the other.

Regards

**Comment by javivelasco** [comment]
Hi @lxibarra! 

Yeah, both projects consists of an implementation of Material Design components, then main difference is how we handle styling and customization.

Material-UI is a great project covered by a large community and with tons of components. They use inline styles to style the component's so the setup is pretty straightforward, you just need to require Javascript. The problem with this is that customization is more complicated because overriding styles is not simple business. Theming sounds a bit painful for most people, but it's not a problem with the project itself but with the opinionated style implementation. Also, when your page holds hundreds of components it may feel heavy.

React Toolbox is an implementation of MD components that uses [CSS Modules](https://github.com/css-modules/css-modules) instead of inline styles. We try to be as close as possible to the spec with an special focus on making easier customization and theming. Most of the advantages of RT come from the usage of CSS. You can write themes with the current version creating a SASS variables stylesheet. You can also import raw components to write your own themes based on a classNames API each component expose. The only caveat is that configuration is more difficult because your module bundler should be able to require CSS but we provide examples to help you set up. Also we are a smaller community and we still need to create more components. Be aware also that the next major will move styles to PostCSS making customization easier, stay tuned.

[Here](https://www.reddit.com/r/reactjs/comments/4fd4ro/materialui_vs_reacttoolbox_and_why/) is a Reddit thread about the differences between both libraries.

**Comment by lxibarra** [comment]
Thank you very much for the quick reply.

Regards

**Comment by oliviertassinari** [comment]
That's such a great summary of the difference between the two libraries 👍.
One year after, isn't react-toolbox moving toward *styled-components* while Material-UI toward *jss*?

**Comment by javivelasco** [comment]
@oliviertassinari it is! but under the covers there is a much more ambitious project: https://twitter.com/javivelasco/status/909483452831031298

Theming with styled components is very easy and customization can be really powerful with a good API too so... yeah, we move the material implementation to styled-components. Good news is that we both converged to CSS-in-JS which means there probably is the way to go!

**Comment by oliviertassinari** [comment]
@javivelasco Happy to see it :). I have been underestimated the customization importance with v0.x of Material-UI. It's only later on, when needing to implement a non-material UI spec for the office, that I realized it. I'm glad v1.x [allowed us to do so](https://material-ui-1dab0.firebaseapp.com/customization/overrides/) 💅.
I'm confident it will be the same story with styled-components.

**Comment by javivelasco** [comment]
It is pretty similar but still different! I hope to release a first version very soon :)
