### ISSUE TITLE
Make react-toolbox compatible with create-react-app?

### ISSUE THREAD

**Issue by sidot3291** [react-toolbox/react-toolbox#707]
Is this a possibility for react-toolbox?  There's no SASS/LESS/CSS Modules support.  But I do understand there's an upcoming switch to PostCSS.  Will that work with create-react-app?

**Comment by javivelasco** [comment]
I think it should be possible and it would be great to get quickly started. I'll give a try so maybe it can be ready for the next release

**Comment by sidot3291** [comment]
That sounds great.  Not sure if this helps at all: https://github.com/facebookincubator/create-react-app/issues/425#issuecomment-239618958

**Comment by sidot3291** [comment]
Took a stab today by adding the following dependency:
`"react-toolbox": "git@github.com:react-toolbox/react-toolbox.git#css-next"`

The app is compiling but components are rendering unstyled.  I'll keep digging.

**Comment by sidot3291** [comment]
Unfortunately haven't been able to get this working.  Can't tell you if it's my inexperience or if something is inherently incompatible.

**Comment by wtgtybhertgeghgtwtg** [comment]
SASS or PostCSS, `react-toolbox` still uses CSS Modules, which `create-react-app` doesn't support.  I think it's just inherently incompatible.

**Comment by javivelasco** [comment]
I honestly did not check yet `create-react-app` but IMO there should be a way to export a configuration module or something to override defaults and add css-modules support. I'm not saying its possible but if it's not right now, it should be in the future.

**Comment by javivelasco** [comment]
Ok so I've been reading about it and I understand the reasons. We can still offer an integration injecting a precompiled theme. We will see when the new playground is ready

**Comment by zac156** [comment]
I'm having the same issue. I've actually run 'npm run eject' which allowed me to add scss file compiling to my webpack config. I don't get any errors anymore but components are still rendering unstyled. @sidot3291 did you figure out why?

**Comment by JetFault** [comment]
Did anyone figure out how to do this?

**Comment by javivelasco** [comment]
Yeah please. Contributions on this would be great. I'm not having time enough to accomplish everything I want to do for react-toolbox!

**Comment by gaearon** [comment]
>I honestly did not check yet create-react-app but IMO there should be a way to export a configuration module or something to override defaults and add css-modules support.

It’s neither possible right now nor planned.

My position is that libraries shouldn’t dictate JS or CSS transforms. This is very fragile because different libraries in one project might depend on different versions of, e.g. CSS modules. Additionally, a dependency like this “infects” any dependent libraries. I can’t release a component using `react-toolbox` without also telling people to enable CSS modules. This breaks encapsulation.

An ideal solution to this would be for `react-toolbox` to compile its assets. In my opinion, the fact that it relies on CSS modules should be an implementation detail. Let’s use lingua franca for published components: JS and (if you’d like), vanilla CSS. This gives consumers most freedom and prevents all the issues with messing with configuration.

**Comment by javivelasco** [comment]
It's great to see you around @gaearon!

I'm sure you already know most of the reasons why react toolbox is built like this, but let me explain these decisions a little bit, just in case. First of all, note I totally agree with you and I would love to get to that point without losing flexibility. Also, note that there is an ongoing migration from SASS to PostCSS #666 where we need to rethink a little how the lib is distributed, so it's a good moment to do something about it. 

The main reason why you need to install opinionated build tools to use react-toolbox is because of configuration and theming. The style configuration is now implemented as a set of variables that are imported and reused all along the library. To accomplish this we are using [postcss-custom-variables](https://github.com/postcss/postcss-custom-properties).  Bundling up the final css at publish time means setting final values for those variables so you can't modify global style settings when you import components/styles. In the future, when custom properties are supported in every browser, it will be possible though but for now we need a way for the user to specify style settings when she uses the library.

Anything else can be overcome. For example we can build a [react-css-themr](http://github.com/javivelasco/react-css-themr) context along with a independent css file for each component that you can require yourself however you want. But the main issue is the CSS variables. I don't want to force anybody to use css modules but you need to process css -> require css -> you can require with modules.

Summarizing, we need to allow the user specify style configuration without messing with her setup. I've been thinking on two different things:
- To distribute a CLI so you can generate react-toolbox style builds without polluting your configuration.
- To include a new page in the documentation where you can get your custom distribution selecting components and settings you want.

Also we can even get rid of CSS as it is building with style loader but it causes an annoying FOUC at rendering time. What do you think?? Thanks for your comment!

**Comment by gaearon** [comment]
>we need to allow the user specify style configuration without messing with her setup. 

Have you considered any CSS-in-JS solutions?

>Also we can even get rid of CSS as it is building with style loader but it causes an annoying FOUC at rendering time.

Curious why? If styles are inserted at component definition time I don’t see why this would be happening.

**Comment by javivelasco** [comment]
What makes the difference between react toolbox and material ui is the way we handle styles and theming. We are betting on css over inline because of the downsides it causes so I would consider a css in js only if it's straightforward to extract the css. I did not explore too much but it seems like you'd have to deal with the same issue: either installing dependencies to extract styles, or doing it programatically somehow.

The issue with style loader is that the css should be added using an style tag with javascript so the content will be present before it is styled on a first render. It is fine for development  but not for production IMO. Specially annoying if you style svg. Maybe I'm missing something?

I really would live to find a way or reducing boilerplate and configuration without a huge technology switch. That hypothetical CLI is the only way I can think right now but still... its not the best experience :(

**Comment by stereobooster** [comment]
It is possible to do with [custom-react-scripts](https://github.com/kitze/create-react-app). Almost done switching example https://github.com/react-toolbox/react-toolbox-example/pull/35. One pending PR in custom-react-scripts prevents from finishing (https://github.com/kitze/create-react-app/pull/23).

But I just figured out that 2.0.0 version want to switch from SASS to PostCSS, so I suppose it should work with 2.0.0 version even without pending PR.

**Comment by maitriyogin** [comment]
Hi,
I'm wondering if this is any closer?
I'v created an issue here
https://github.com/kitze/create-react-app/issues/31

I was hoping by using custom-react-scripts I could just enable the relevant flags and everything would magically work.

Any ideas would be greatly appreciated.
/Stephen.

**Comment by gaearon** [comment]
Maybe I misunderstand but isn't it possible to just compile `react-toolbox` with any customizations into a separate package and then use that? One does not have to use Webpack for everything. Your app would also build faster with that step separated.

Here is [an example walkthrough of doing this for Bootstrap](https://medium.com/@tacomanator/customizing-create-react-app-aa9ffb88165). Can users or `react-toolbox` do something similar?

**Comment by javivelasco** [comment]
In fact @gaearon that's very close to what I'm working on for the #666 branch. Basically in consists on shipping a builder that can be run with npm allowing you to generate a CSS build. It's pretty much what it's done in the link you gave but without linking npm and stuff like that. @maitriyogin this is the only thing really blocking #666, I don't want to release it without it.

**Comment by maitriyogin** [comment]
Hi Dan,
many thanks for the link.
After ejecting and updating our webpack config I did kind of feel dirty ..  It works but really feels like the wrong thing todo.
I'll setup a watch on sass.
Cheers,
Stephen

**Comment by maitriyogin** [comment]
Cheers @javivelasco I'll keep an eye on #666
/Stephen.

**Comment by just-boris** [comment]
Hi all, 

Recently, I encountered the same problem while I was woking in internal UI library for my company. I also wanted to use CSS-modules, but make it easy to include in any technology stack without extra setup.

I have published an example of such project structure on Github: https://github.com/just-boris/kinda-ui-lib

In my approach, I generate standalone bundle for each component. Bundler also extracts CSS into a separate file, that can be picked up later and included into big CSS file for your app. JS file keeps the mapping from original class names to processed, and everything work as expected.

However, my setup uses Rollup for smaller bundle size, there you may find [webpack config](https://github.com/just-boris/kinda-ui-lib/blob/a3742841f33507a5f5fb37b0ba4812075cfaabac/webpack.config.js) that was used before. Actually, such setup allows you to use any technologies inside, but still as the result here will be only files, consumable by a lot of bundling tools without extra setup.

**Comment by javivelasco** [comment]
Now integration with create-react-app is possible: 

![react-toolbox-themr](https://cloud.githubusercontent.com/assets/1634922/21305836/285a092a-c5ce-11e6-8ad4-7b170dc97d1b.gif)

Check [react-toolbox-themr](https://github.com/react-toolbox/react-toolbox-themr). For now it works from 2.0.0-beta.4

**Comment by just-boris** [comment]
Even though I really appreciate your efforts, @javivelasco, your solution doesn't seem like something, that I expected.

You are still making users to do some special setup in their projects. This is something that Create-react-app encourages you to avoid. Ideally, users should be able to include anything with simple `npm install react-toolbox` and then it will be ready to import as it is.

Could you run `react-toolbox-themr` as a pre-publish step and include resulting files in the npm package?

**Comment by javivelasco** [comment]
@just-boris as mentioned in a comment above, using css-modules forces a setup step in the consumer. It's the only way to get customized CSS and still keep getting benefits from using just CSS. It's possible to precompile some themes and ship them with react-toolbox but if you want to set custom colors or to change some aspect controlled with custom variables, you have to process the css with those. I'm going to add a default theme that allows to skip editing the package and running the build command, but again, to set custom properties you have to configure it a bit.

To skip this build step we can only remove the build-step totally by using css-in-js. I plan to publish a Roadmap with some thoughts on this. I have an approach that would help switching from CSS Modules to Styled Components without effort but until we go there, you have some sort of processing.

**Comment by just-boris** [comment]
@javivelasco you point is pretty fair, people want customization sometimes. But as long as you want custom stuff, you can run `eject` and change everything.

From another point it seems overwhelming, when *dependency* asks you to *build* it using *its special* tool. Imagine, [that](https://github.com/oliviertassinari/react-swipeable-views) [any](https://github.com/JedWatson/react-select) [other](https://github.com/igorprado/react-notification-system) [dependency](https://github.com/facebook/fixed-data-table) of your app, would also require you to run an command before get started. Very soon your `prepublish` script will become very long.

If anybody else is watching for this thread, correct me if I am wrong.

**Comment by javivelasco** [comment]
I get your point too :) And I agree the best would be to remove the setup completely. As I said I'm going to publish a roadmap that will hopefully drive us there. Also you have to take into account that react-toolbox is not like *any other* dependency on your app, it's the ui kit!! But yes, I guess you're right.

Can't see a way of getting rid of everything keeping customization. What do you think of including a couple of pre-transformed themes?

**Comment by wtgtybhertgeghgtwtg** [comment]
`react-toolbox` is in a tricky spot as far as UI kits go, mostly because it's inevitably compared to `material-ui`.  And while `react-toolbox` is faster, better tested, and all around better written, it's hard to compete with the simplicity `material-ui` offers.

**Comment by gaearon** [comment]
FWIW I think this approach is very reasonable.
I don’t agree it goes against CRA goals.

My main objection to requirements like “add this to Webpack config” is that we were leaking dependency implementation details into the project.

This used to mean that:

* RT depends on a specific CSS Modules implementation. Imagine CSS Modules spec gets a major bump and Webpack implements support for the new incompatible version in `css-loader@next`. Then imagine both RT and some other library require you to compile their CSS using CSS Modules. Now they're competing for a shared loader. There are of course solutions to this but this makes long term maintenance harder.

* It is not very likely that you constantly change the base widget color scheme as you work on the app. However you're spending CPU cycles at compiling dependencies that require post-processed CSS every time. This is suboptimal as you add more dependencies.

* The associated configuration is the cruft you have to maintain. For example imagine Webpack 7.0 comes out with a feature you badly want but CSS Modules support is not ready yet. You have to stay on Webpack 6.0 until CSS Modules is implemented because a requires it even though you might not be using CSS Modules directly yourself. As more dependencies depend on obscure tools (that might die in a few years) it’s going to be increasingly painful.

Contrast this with the "separate build" approach:

* It does not depend on specific versions of postprocessors—if web still runs on CSS and JS you can keep using your compiled bundle forever. At the very least it does not limit your app: you could always compile your app with "CSS Modules 2.0" while compiling RT with whatever it requires.

* It’s only recompiled when necessary.

* You can always migrate your project to the newest build tools without having to wait for RT to support them. You can also reuse compiled builds across projects. And third-party libraries can depend on compiled builds without instructing their users to copy and paste lines in their configs.

To be honest I do think that separate isolated predictable `build-${toolkit}` scripts that don't assume anything about your configuration are a nicer alternative to “copy and paste these lines into your Webpack config”.

**Comment by oliviertassinari** [comment]
> What makes the difference between react toolbox and material ui is the way we handle styles and theming.

I don't think that the styling is the only difference here. We are trying to achieve the same thing but using different tradeoffs. The more paths we experiment, the more we gonna learn from it and the better our projects will become.

> I have an approach that would help switching from CSS Modules to Styled Components 

If that can help, I have been giving a presentation around the ongoing migration of material-ui from inline-style to CSS-in-JS started months ago by @nathanmarks https://github.com/oliviertassinari/a-journey-toward-better-style. I'm expositing what we have learned and the challenges.

**Comment by samkit** [comment]
@javivelasco Great work with react-toolbox!

I followed your post above and was able to setup RT with create-react-app. I got into a hole when I started using AppBar and had IconMenu based overflow menu, in which AppBar's text comes in white but IconMenu's 'more_vert' come in black color and I am lost on how to change its color to white. It will be great if you can please point to some example.

And when is RT 2 playground going to be live? :smile:

**Comment by javivelasco** [comment]
Thank for your kind words @samkit !

Make sure that your are including the components you're using / every component in the build. Check out the output to make it sure and compare the className with the one generated by the library. Customization is handled by passing classNames as with any other component, but notice you might need to boost priority in some cases. I plan to write more docs and tutorials but first I need to finish the Roadmap and planning to be transparent about the direction in which react-toolbox should go in my opinion. About the new playground, I have it implemented and there is a redesign coming... but there are other priorities that should be solve before implementing the new design and integrate the playground.

I promise it will be worthy!

**Comment by ivanzusko** [comment]
@javivelasko
First of all thanx for such an interesting tool.
But I'd like to ask something:

I'm using your approach (displayed in your gif) in my CRA app, but faced with a problem of customization of RT components.

"Customization is handled by passing classNames as with any other component, but notice you might need to boost priority in some cases."

The only way which is working for me is setting `!impotant` to the rules of my passed classNames. But it's definitely BAD solution... 
Is there any way to make it in more civilized way?

Thanks in advance !

**Comment by javivelasco** [comment]
Sure thing! I'm currently refactoring the css to have plain classnames and solve this issue but I'm afraid that for now you have to go to the devtools or the source to check the priority of the selector and write the same plus a discriminator for your customization. 

I'm publishing soon the POC with the new approach, for now you need to see the priority to write the same priority +1. Fortunately it's not always the case, some components hold plane selectors

**Comment by ivanzusko** [comment]
@javivelasco , yeah... for now it's okay. Thanks one more time!

**Comment by yarnball** [comment]
What's the current situation with this? I tried using react-toolbox-themr but it only partially works. EG icons WITHIN an element don't display (EG DatePicker chevrons). Any ideas?

**Comment by stereobooster** [comment]
@yarnball you need to add icons yourself, you have different options, one of them is to add `<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">` to `index.html`

**Comment by yarnball** [comment]
Thanks- that has worked for the icons. But still AutoComplete looks totally wrong- it is missing lots of parts. Any ideas?
