### ISSUE TITLE
Need option to mount tabs that are not active

### ISSUE THREAD

**Issue by abhirao** [react-toolbox/react-toolbox#709]
I have a use case where it would be more convenient if hidden tabs were mounted (but still hidden). Some of the tabs we're showing make AJAX calls to fetch data and it's expected that users will be switching between the tabs. So having the tabs mounted and hidden makes the UX better as the user can immediately see what they are expecting when they click on a tab. 

I feel the default should be the current behavior. If there is agreement on this feature and it's config I can put together a pull request.

I think it should be configured on `Tabs` and not an individual `Tab`. I can think of two ways to configure this:

1. `hideMode: PropTypes.oneOf(["display", "unmounted"])`. default: "unmounted"
1. `mountHidden: PropTypes.bool`. default: false

What do you think?

**Comment by javivelasco** [comment]
In my opinion having the choice is (almost) always better. But I think that what you want to do is perfectly doable from outside the tabs component. You can have a container wrapping the Tabs that perform that operation for you and saves the state into an external component. I would love more opinions on this because the same issue may happen for other components since in most cases we are trying to move from hidden to unmounted...

**Comment by abhirao** [comment]
@javivelasco I too would have preferred if unmounted worked for my case. But we have at least one case that would still feel slow: An IFrame in a tab. Am I right in thinking that since it's removed from DOM it feel be another request...

In addition it feels like a high bar to make all components that should be rendered in a tab stateless (i.e. state is managed by the container that wraps the Tabs). We would have to refactor a lot of components that "just work" otherwise.

**Comment by javivelasco** [comment]
This relates to #739 There are some components that are totally stateless and forces you to create wrappers. The `Input` with label is an example. I think it's a better approach to wrap them with an HOC like recompose does to add state that get's synchronized with the props. This allows to make handling the state totally optional.

This work should be taken in both directions: making components that are stateless optionally stateful and viceversa. In any case if adding a prop to switch unmounted/mounted works for you I'd have no problem accepting a PR so feel free to do so

**Comment by acornejo** [comment]
Just saw this issue. I think that if we separate the actual tabs from the content that should be rendered when the tabs are active this issue is gone, since everyone can handle the tab content as they see fit depending on their particular use case.

Adding more options to the existing tab component only makes it more complicated, where I would like to see us move in the opposite direction (make the tab component simpler and more flexible by separating concerns). Please comment in #739 if you have thoughts on the matter (either against or in favor of such a refactor).
