### ISSUE TITLE
Discussion: Automatic padding-top when AppBar fixed

### ISSUE THREAD

**Issue by PolGuixe** [react-toolbox/react-toolbox#715]
I think it would be useful, that the `Panel`, the `Drawer` and the `SideBar` should have a padding-top equal to the AppBar height by default when it is defined as _fixed_.  

What do you think?

**Comment by vmsoftware** [comment]
@PolGuixe I agree,  but I'm no sure what is the best option...  Margin or padding

**Comment by javivelasco** [comment]
I agree too!

**Comment by javivelasco** [comment]
What I'm not sure is if we should try to use `Drawer` inside `Layout`. Now using `theme` property it should be very easy to target from the `Panel` component. I'm quite busy with other things but we should consider it because some people confuse the `NavDrawer` and `Drawer` and it's perfectly understandable.

**Comment by vmsoftware** [comment]
@javivelasco, you're right... I think @PolGuixe did he mean `NavDrawer` instead `Drawer`... However `Panel` should have padding or margin top to fit correctly with `Fixed AppBar`

**Comment by PolGuixe** [comment]
Yes, sorry. I meant `NavDrawer`. I got confused as well. :)

**Comment by patrick-jones** [comment]
One thing to keep in mind is that on phones and tablet the NavDrawer and Sidebar are supposed to be [over the AppBar](https://material.google.com/layout/structure.html#structure-ui-regions). 

On desktop, the spec is less definitive.  Generally, the drawer is shown [next to the main content area](https://material.google.com/patterns/navigation-drawer.html#navigation-drawer-behavior) when in "Permanent" mode, although the "clipped under app bar" design is another option. For "temporary" NavDrawers, the drawer opens "above all other content until a section is selected". The material design site itself places temporary drawers above all other content, including the app bar.

**Comment by javivelasco** [comment]
@patrick-jones I'd really appreciate if you can go over #666 and check the implementation of the `Layout` component and subcomponents. I had a couple of issues that made me reimplement it:

1. It's really important to keep natural scrolling by default in the `Panel`. If you scroll down and refresh the page should keep the same position.
2. Reusing the `Drawer` component because it was being implemented twice.

It's still remaining to make it work in a nested component, although I think the most general use case is to keep it on top of the tree. Maybe you go over it?

**Comment by patrick-jones** [comment]
I see that's in the css-next branch, right? I'm actually using that already, so I'll update and have a look.  I agree that good scrolling behavior is probably more important than nestability.

**Comment by javivelasco** [comment]
Yes, there should be a way of making it nestable too. Its in the css next branch but not released as beta yet

**Comment by javivelasco** [comment]
This is done!

**Comment by mangalzefo** [comment]
can we create drag and drop widget using existing widgets?
