### ISSUE TITLE
gulp integration

### ISSUE THREAD

**Issue by farfromrefug** [react-toolbox/react-toolbox#716]
Hi, 

I am trying to integrate your lib within an electron app.
I am not using webpack but use gulp to prepare the build project.
Obviously right now react-toolbox is trying to require scss files which won't work.
I am not sure how to proceed in making it work with gulp. 
Do you have an integration of such a thing?
I have the gulp task to transform scss into css but then how to tell react-toolbox to require css and  not scss files?

Thanks

**Comment by javivelasco** [comment]
There is no scaffold without requiring CSS. What you can do is to pass a classname mapping using the context. React Toolbox uses [react-css-themr](http://github.com/javivelasco/react-css-themr) so you can use the `ThemeProvider` to pass an object describing the theme for each component.

If you follow this approach you will need to import components raw (without a theme injected). Check the docs for details but it's something like `import Button from 'react-toolbox/lib/button/Button.js'` instead of importing from `button` index.

I'm afraid we did not established a pattern to provide naming. Check out https://github.com/css-modules/postcss-modules. They have an API that would allow you to create a gulp task to generate modules that you can save in a theme.js file that can be required with `browserify` and a `css` file that you can include using a script. It would be something like:

1. Write a script that uses `node-sass` to turn RT scss into css.
2. Process that css (in the same or other script) to generate a theme.js with the modules matching produced by css-modules and a CSS with those classes mapped.
3. Include the css file in your index
4. Import that theme.js file and inject it into the context using `ThemeProvider` from `themr`.

It's not easy to explain without the context about how themr, css modules and react-toolbox works so read the docs and let us know how is it going. It can be a generic script 🙌

**Comment by farfromrefug** [comment]
@javivelasco Thanks for the explanation. I will take the time to look at this when i am back from holidays. I really want to test your lib in electron.
Thanks.
PS: can we keep this open may be to give more info about that "generic script" we talk about?

**Comment by javivelasco** [comment]
Of course, I think it could be a good addition to the docs or even an integration written in other repository. I'm very interested on seeing how does it fit with electron, let us know!

**Comment by javivelasco** [comment]
Now integration with tools like create-react-app is possible without any specific bundler, so react-toolbox is now usable with gulp without a trouble.

![react-toolbox-themr](https://cloud.githubusercontent.com/assets/1634922/21305836/285a092a-c5ce-11e6-8ad4-7b170dc97d1b.gif)

Check [react-toolbox-themr](https://github.com/react-toolbox/react-toolbox-themr). For now it works from 2.0.0-beta.4

**Comment by farfromrefug** [comment]
@javivelasco amazing news! I have to test react-toolbox now. Thanks!
