### ISSUE TITLE
Multiple dropdown components issue

### ISSUE THREAD

**Issue by aqumus** [react-toolbox/react-toolbox#718]
When clicked on one of the Dropdown and directly clicked on other dropdown in the same form or same page , earlier dropdown doesn't get closed.

(Below image shows both dropdown are active @ the same time)

![imageedit__8891626108](https://cloud.githubusercontent.com/assets/10741508/17809236/c665f4f4-6632-11e6-99aa-3587339d26db.jpg)

**Comment by javivelasco** [comment]
It's a bug, thanks for reporting. In any case, this Dropdown is going to be rewritten for the next big release. I already have a working version way better than this.

**Comment by javivelasco** [comment]
Any fix meanwhile is welcome of course!

**Comment by aqumus** [comment]
Where could I find the working version, any links ?

**Comment by javivelasco** [comment]
It's not done in the repository yet. It will be included in the next version of RT but there still pending work to do. Keep track on it on #666 

The new Dropdown has to wait because I think it's not worthy to implement it in both branches and then release it in a patched version and then later in the official 2.0. As I said, a fix meanwhile is appreciated. I'll try to get some time to look at it during the weekend thought

**Comment by javivelasco** [comment]
Closed in favor of #1169
