### ISSUE TITLE
Please a better documentation for WebPack usage is nedded!

### ISSUE THREAD

**Issue by mcianc** [react-toolbox/react-toolbox#725]
after 2 day of hard work finally i was able to emit css bundle with webpack, .
React is still a wild west , webpack have enough ugly documentation too , was enought hard use it with react-toolbox, what you wrote in
- toolbox-loader 
- react-toolbox
- react-toolbox-example 

is different anytime from example. I was able to let work all using react-toolbox-example after fix missing modules there too.
Anyway there is a big confusion to how better integrate into webpack

**Comment by javivelasco** [comment]
I'd rather won't be too exhaustive documenting a webpack configuration. Giving an example should be enough but it's true that we not looking too much on it. The main reason is that we are trying to make react-toolbox friendly for non-webpack users. It's going to be fully possible in the near future. With the upcoming release, the documentation is going to be updated too and hopefully with a better configuration section. Glad you make it work!

**Comment by Knacktus** [comment]
I'd like to emphasize this. I was not lucky and after a day trial and error I have to use a different library even though I think react-toolbox is better designed.

Most boilerplates use webpack. I've tried react-slingshot, the new CLI (create-react-app) and https://github.com/mxstbr/react-boilerplate.

**Comment by javivelasco** [comment]
Hi @Knacktus ! So sorry to read that. Did you try our example repository??

**Comment by douglasjunior** [comment]
I created a boilerplate project that works fine with most recent version of React + Webpack + React-toolbox.

https://github.com/douglasjunior/learning-react/tree/master/ReactWebpackCssModulesReactToolbox

Is included a minimum configuration to work with dev and production modes.

**Comment by javivelasco** [comment]
Thanks great! Thank you @douglasjunior

**Comment by mcianc** [comment]
I love boilerplate too, but have a detailed page where explained as well how configure each parameter is the best.

**Comment by douglasjunior** [comment]
One of the great problems of boilerplate creation is the variety of tools and libraries that you need to choose and configure. For each there are many, many parameters and complicated configurations. It is exponential.

I started working with frontend a month ago. And then I studied the part of each item I needed.

1. Node and npm: configurations, parameters, possibilities, etc.
2. Webpack: development vs production, loaders, plugins, live reload, babel, file-loader, url-loader, css-loader, **sass-loader**, **css-modules**, etc. (If you choose Webpack)
3. React: Using router or not, flux or not, redux or not, etc. (Many options)
4. Finally **react-toolbox** and yours parameters.

I say this because I tried several other options before the **react-toolbox** and all of them creating the project are difficult. The variety of options is very big.

In my list, if you replace Webpack for other, the process changes completely.

**Comment by casteezy** [comment]
This article got me up and running with react-toolbox and after ejecting my create-react-app.. app:
[CSS Modules with React, Scss, and Webpack](https://ihavemind.com/css-modules-with-react-scss-and-webpack-53fb584d88f0#.2etsso3cn)

Like @Knacktus I had basically given up on using react-toolbox, it took me two days to finally figure it out and what to google up on. (I couldn't get react-toolbox-example working, even from a git clone. I don't know much about webpack, but my guess was that it's related to me running on a Windows machine? react-toolbox-themr doesn't work for that reason as well.)

**Comment by chrisrink** [comment]
Got this working in webpack 2 syntax. Here are the modifications you'll need:

modules: 
```
{
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract({
          fallbackLoader: "style-loader",
          loader: 'css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss-loader!sass-loader'
        })
      }
```

plugins:
```
    new ExtractTextPlugin({filename:'bundle.css',  allChunks: true })

```

**Comment by javivelasco** [comment]
BTW. There is no need to use webpack anymore. All you need is github.com/react-toolbox/react-toolbox-themr

It's still usable eith webpack though, and the new docs will include a section with detailed information on how to integrate.
