### ISSUE TITLE
Input tipo file renderiza estilo predeterminado del navegador

### ISSUE THREAD

**Issue by miguelzh93** [react-toolbox/react-toolbox#732]
Buen día, me parece genial tu contribucion con este proyecto.

Estoy tratando de colocar un input de tipo file, pero al cargar la pagina toma los estilos predeterminados del navegador en vez de mostrar un estilo acorde a Material Design. No se si realmente es un error o me falta agregar algo

`<Input 
                type='file' 
		name='txtFoto' 
		label='Fotografia' 
		value={this.state.foto} 
		onChange={this.handleChange.bind(this, 'foto')} 
/>`
Adjunto imagen de como se renderiza.
![input file](https://cloud.githubusercontent.com/assets/18130621/17917285/777704ae-6980-11e6-8887-4d19d3fd10e4.png)

`

Gracias cualquier ayuda sera apreciada.

**Comment by javivelasco** [comment]
Hola, muchas gracias!

Pues lo cierto es que no había tenido en cuenta el caso de un input tipo file. Es que es un poco complicado trabajar con ello así que para mantener el componente más limpio mi sugerencia es gestionarlo "fuera" de react-toolbox. Por ejemplo, puedes tener un componente input nativo que esté oculto y enlazar las acciones con un `Button` de react toolbox. Por supuesto imagino que puede ser que necesites controlar el estado de la subida si quieres subir in-situ así que tendrás que trabajar en un componente de todos modos. En mi opinión, no debería ser necesario controlar los casos de input tipo file porque tendrá un aspecto y funcionamiento muy diferente. Qué opinas??

-- 

Hi and thank you!!

The truth is that I never considered a file input case. It's a bit fucked up to work with file upload inputs so in order to keep the component as clean as possible I'd suggest you to create a component out of react-toolbox. For example you can have a native input component hidden and link actions with a `Button` component from RT. Of course I image you may want to control the state of the upload in case you want to upload the file right away so you would need to work on that anyway. IMO, it shouldn't be necessary to control input file cases from the component since it should look very different. What do you think?

**Comment by javivelasco** [comment]
Please if anybody thinks we should do something with input of type file, reopen. Otherwise I think it's better just use a hidden input type file and to add a button linking the click behavior. Styling that kind of input is close to impossible

**Comment by sanfilippopablo** [comment]
Hi Javi. I always did that (hide a input type file and trigger with click() on response to some other 'Choose file' button). But while I agree with you on that it's almost imposible to style input type file, I think this is something that react-toolbox could do and we (users of react-toolbox) would be very happy.

I'm thinking of creating a <FileInput /> that implements this hidden file input and bound button automatically and could be a drop-in replacement for <input type="file" />. What do you think?

**Comment by sanfilippopablo** [comment]
I know that the last thing you are thinking about right now is about adding new components, but I thought about this and found this issue and am now raising the question.

**Comment by vmsoftware** [comment]
Hi @sanfilipopaplo,  currently in RT there is a component to handle input type='file' in the same way as described here. This component is called <BrowseButton /> and you can import from 'react-toolbox/lib/button'. 

I think it is a good option for now.

 Hope it helps!

**Comment by sanfilippopablo** [comment]
Ooh, I didn't see that. Thanks!
