### ISSUE TITLE
Prepare components as reusable lib for npm

### ISSUE THREAD

**Issue by ipselon** [react-toolbox/react-toolbox#74]
Hi, first of all, thanks for a great set of components!

There is one issue with lib, I agree to include in my webpack config sass loaders, but I don't agree to include unnecessary deps in my project (react-transform-catch-errors, etc.). 
It would be nice if you prepare components as a really reusable lib.

**Comment by ipselon** [comment]
I need to elaborate on this issue. If you don't mind I would like to include React Toolbox components into one of boilerplates here http://helmetrex.com But the tool which is used there has its own webpack and webpack middleware environment configuration. So, I could not build components at all.

**Comment by javivelasco** [comment]
Hi @ipselon thanks for your words :) 

There are no such dependencies. React Toolbox only depends on React (with ReactDOM and css-transition-group) and normalize. The only *limitation* of React Toolbox is that you need to include CSS Modules in your workflow. To be able to customize colors and components in an easy way we can't include in the package the css already compiled, that's why you need sass loader... but that's all you need.

There is no need for other packages. Let me know if you can't get it working!
Thanks!

**Comment by ipselon** [comment]
@javivelasco a couple hours ago I install react-toolbox from npm and my webpack threw exception about missing modules. When I looked into the source code of (for example) ```node_modules/react-toolbox/lib/list/item.js``` I found the following:
```
'use strict';
var _reactTransformHmr2 = require('react-transform-hmr');
var _reactTransformHmr3 = _interopRequireDefault(_reactTransformHmr2);
var _react = require('react');
var _reactTransformCatchErrors2 = require('react-transform-catch-errors');
var _reactTransformCatchErrors3 = _interopRequireDefault(_reactTransformCatchErrors2);
var _redboxReact = require('redbox-react');
```

**Comment by javivelasco** [comment]
You are right, I've created the last build without the `production` env specified and the lib is including development babel settings. Sorry about that, fixing.

Thanks for reporting!

**Comment by javivelasco** [comment]
It should be fixed now. We are not still making semantic releases, just hot patches. During this week we will plan the roadmap to get a final version of React Toolbox and start with tagged released.
Closing!
