### ISSUE TITLE
Appbar icons rfc

### ISSUE THREAD

**Issue by acornejo** [react-toolbox/react-toolbox#743]
The most common use case of the appbar component is to have a left icon, a right icon and a title.

Unfortunately react-toolbox does not provide props for any of these, and instead the user must style it's own content in order to place the icons and title in the right place.

I would like to add these props, they will reduce the boilerplate for 80% of the uses of appbar, and the remaining 20% can keep styling children props manually.

I wanted to ask if this makes sense before I do a PR.

PS: I'm starting a new hobby project and have decided to use react toolbox (again), so as a first step I plan to contribute PRs to fix issues I care about and add a few missing components. @javi: do you want me to base these PRs on the dev branch or on your postcss branch?

**Comment by javivelasco** [comment]
Yeah, PR it, the `AppBar` component is quite poor atm. I think I've mentioned in another issue but a change I want to make soon in the postcss branch is to communicate the Layout component with AppBar and Drawer instead of having their "subcomponents".

It's great you choose react toolbox and of course any contribution is very welcome. If the PR involves tons of style changes I'd rather want it in the PostCSS branch. If not you can do it in the dev branch since merging would be easy.
