### ISSUE TITLE
MenuItem href prop

### ISSUE THREAD

**Issue by PolGuixe** [react-toolbox/react-toolbox#750]
Should the `MenuItem` component accept an `href` prop? 

Modifying  the route through the `onClick` event doesn't feels right 😞

**Comment by javivelasco** [comment]
There is *a lot* of stuff I want to change regarding the API. Although what you propose is kind of a nice workaround, the root of the problem is deeper than that. The `MenuItem` is a `li` so the link semantically should be placed inside, as an inner element. That means modifying the style for the inner elements and that should not be done now because its better to wait for the PostCSS migration.

In fact, what I think it's best is to modify `List` and `ListItem` so a `Menu` would be just a positioner. `MenuItem` would no longer exists and if you want to create this kind of menu what you'd do is to create a `List` with `ListItem` inside whose children you can customize as you want:

```
<Menu>
  <List>
    <ListItem><a href="">Your item</a><ListItem>
    <ListItem><a href="">Your item</a><ListItem>
    <ListItem><a href="">Your item</a><ListItem>
  </List>
</Menu>
```

What do you think?

**Comment by PolGuixe** [comment]
@javivelasco I think using a `List` inside a `Menu` is a good solution. I won't have any problem using it. 👍

**Comment by mendlik** [comment]
Hi first of all thanks for react-toolbox :)

Using `List` and `ListItem` in a `Menu` breaks styling. Same happens in `Navigation` where I want to use components from [`react-toolbox-plus-router`](https://github.com/borela/react-toolbox-plus-router).

Try:

```
const MenuTest = () => (
  <Menu menuRipple>
    <MenuItem>MenuItem</MenuItem>
    <List>
      <ListItem to="/abc" caption="ListItem" />
      <ListItem><a href="">Link in a ListItem</a></ListItem>
    </List>
  </Menu>
);

return <MenuTest />;
```

I know I can style it by myself but It would be nice to have it normalized.

**Comment by javivelasco** [comment]
We need to refactor it because the `List` component generates a lot of stuff under the covers to automatically position everything for you. In the next version we will refactor it to make it simpler but for now the only way I see is to wrap the `ListItem` itself. I've added some code to style the anchors on hover but it's un ugly workaround that should be fixed with a refactoring.
