### ISSUE TITLE
feature request for specify icon position for button

### ISSUE THREAD

**Issue by neekey** [react-toolbox/react-toolbox#757]
The Button component, for the moment, icon is always at the left.

There is user case that you want to show an icon at the right, like a menu button( which is quite conventional to put the arrow on the right ):

![image](https://cloud.githubusercontent.com/assets/499870/18157180/23b1399e-705f-11e6-87e3-1436800d3150.png)

So I want to request a new prop for Button component named `iconPosition`, the value can be `left` or `right`, and default to be `left`.

**Comment by javivelasco** [comment]
Not sure if this is really useful because the `icon` property is there just for convenience in common situations. I think you can get this working just using theme and passing the icon as children. It would render the same. For example:

```
<Button raised primary>
  Menu Button
  <FontIcon style={{ marginRight: -8 }} value="keyboard_arrow_down" />
</Button>
```

Will render:

![button](https://cloud.githubusercontent.com/assets/1634922/18224776/ec715e9a-71e0-11e6-985b-801f4c7049dd.png)

I want to push react-toolbox in this direction. Customization feels more difficult when it's done via props that when you just customize the content. This kind of property is there to help you going faster but you should be able to use a component as a wrapper almost in any situation.
