### ISSUE TITLE
Components seem too big

### ISSUE THREAD

**Issue by douglasjunior** [react-toolbox/react-toolbox#759]
I'm starting with react-toolbox, is a awesome library, thanks for that.

One thing that I can't understand, is that the size of components are so big in my project.

See comparison with the showcase components.

![captura de tela 2016-09-01 as 10 36 18](https://cloud.githubusercontent.com/assets/1512341/18169326/08cdea7a-7030-11e6-8700-8628f9ddc3cd.png)

My sample project is [here](https://github.com/douglasjunior/learning-react/tree/master/ReactWebpackCssModulesReactToolbox).

What I'm doing wrong?

**Comment by douglasjunior** [comment]
Sorry, just adding `import 'react-toolbox/lib/commons.scss';` soved my problem.

**Comment by godd9170** [comment]
Is there a way to fix the sizing without including `commons.scss`? I don't want to interfere with the font size of the rest of my app.

**Comment by javivelasco** [comment]
Yes, you can se the default unit to 10px. It should work for the most recent versions. Anyway I encourage you to use the latest beta which gets rid of `commons.scss` so it doesn't mess with your setup at all.

**Comment by godd9170** [comment]
Awesome!

Thanks for the prompt reply @javivelasco, will try out the beta.

**Comment by godd9170** [comment]
@javivelasco I can't be bothered to figure out the changes to my webpack right now to move to the beta. To your first point, how does one set the default unit?

**Comment by javivelasco** [comment]
Sorry for this 3 days response @godd9170. The builds now are produced with all css transformed except for the `postcss-variables` plugin which also included in `css-next`. What you need to change is the CSS loader. Now instead of using SASS loader + Postcss you just need postcss with one single plugin. To get yourself oriented you can check the webpack configuration in the package (it is used to display a showcase for development purposes). You may need less config, only css-next is required indeed.

Also you may want to try out [react-toolbox-themr](https://github.com/react-toolbox/react-toolbox-themr) which allows you to forget about messy setups. The default unit is 10px by default now so we don't mess with rems. You can still set it to 1rem if your body size is 16px as it was with `commons.scss`.
