### ISSUE TITLE
Layout Panel Scrolling

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [react-toolbox/react-toolbox#761]
In order to scroll with the arrow keys in a `Panel` of a `Layout`, the `Panel` first has to be clicked.  Clicking on an element outside the `Panel`, such as an `AppBar` will also prevent `Panel` from scrolling.  An example of this would be in [the documents](http://react-toolbox.com/#/components/layout).
Could there be an option to allow scrolling with having to click `Panel`?

**Comment by javivelasco** [comment]
Mmmm I don't know if it's possible, I'd have to try it. I think I've mentioned in other issues but I'm going to write it here too. `Layout` should be changed. I think it's creating duplication with `Drawer` and `AppBar` components and it can better communicate with those two so depending on whether they are wrapped in a `Layout` or not they can behave differently.

In that case, blocking the scroll should work the same as we do now with the `Overlay`. This allows to scroll naturally over the body when you use the layout instead of with an overflow scroll. Changing that will allow you to scroll naturally with the keyboard and also to keep the scroll where you left it after a reload. This should come after PostCSS

**Comment by javivelasco** [comment]
This is solved in the current `dev` branch
