### ISSUE TITLE
Unknown props in Tooltip

### ISSUE THREAD

**Issue by kencana-voilaah** [react-toolbox/react-toolbox#769]
Encountering unknown props warning when wrapping a component like FontIcon with Tooltip

**Comment by rrott** [comment]
Was able to reproduce:
 `Unknown prop 'theme' on <span> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop`

<img width="849" alt="screen shot 2016-10-08 at 00 17 29" src="https://cloud.githubusercontent.com/assets/746383/19205719/d2c76c2e-8cec-11e6-926a-3e7209b72104.png">

**Comment by javivelasco** [comment]
This is not *really* an issue but a side effect of how Tooltip is implemented. It happens the same with Ripple. In order to be able to pass just one theme to a component which is decorated with Tooltip or Ripple, we need to reuse the theme object. This way any component implementing a tooltip can be customized including tooltip theme properties in the top passed theme.

The only way to make this work is to always pass down the theme so if you spread the given props in a `div` elemenet you'll get the warning. The best way to deal with this is to wrap your div in a component that swallows the theme prop and spread the rest.
