### ISSUE TITLE
NODE_ENV prefix throws error in Windows

### ISSUE THREAD

**Issue by EnzoMartin** [react-toolbox/react-toolbox#78]
```
> react-toolbox@0.11.5 build E:\GitHub\react-toolbox
> NODE_ENV=production npm run babel && npm run sass

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.2.2
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! react-toolbox@0.11.5 build: `NODE_ENV=production npm run babel && npm run sass`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-toolbox@0.11.5 build script 'NODE_ENV=production npm run babel && npm run sass'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-toolbox package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production npm run babel && npm run sass
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-toolbox
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\GitHub\react-toolbox\npm-debug.log
```

Seems prefixing the environment variable when invoking an NPM script doesn't work in Windows when checking out the project source and running `npm install` (**Note:** Getting from NPM as a dependency still works fine)

**Comment by NogsMPLS** [comment]
Yeah, setting NODE_ENV in npm scripts is known to be brittle.

To make it not error out on Windows you have to use the set keyword and escape some quotes, like this:

```"SET \"NODE_ENV=production\" && npm run babel && npm run sass"```

Ideally the project wouldn't be setting env variable in npm scripts, but somewhere else when tasks run.

I'll also note that even with this fix in place, the repo seems to have issues on Windows in general, because running ```npm run start``` has an issue with webpack bundle never finishing.

**Comment by NogsMPLS** [comment]
I would like to suggest using this inside react-toolbox to ensure cross platform node_env compatibility:

https://github.com/kentcdodds/argv-set-env

@javivelasco @soyjavi i can create a pull request with this if you'd like.

**Comment by javivelasco** [comment]
I think we need a cross platform way to set the env variables we need in order to compile sass. While the `node-sass` issue is active we should use something like that. Since it's just a developing thing if you feel likely to create a PR I'll be happy to accept it :) Pretty sure @soyjavi too 

Thanks @NogsMPLS

**Comment by NogsMPLS** [comment]
after some more digging, It looks like UV_THREADPOOL_SIZE must be set as well, which is out of the scope of the ```argv-set-env``` project. Because UV_THREADPOOL_SIZE *must* be set right before the command (in this case `webpack`), we must look at a different solution.

One solution I know works is to use:https://www.npmjs.com/package/better-npm-run

You can see a working example of what it looks like in use here: https://github.com/erikras/react-redux-universal-hot-example/blob/master/package.json

It is a little more complicated than I like, but it will ensure cross platform usage. I'll make a PR with it here soon for you to check.

**Comment by EnzoMartin** [comment]
A simpler solution is to just use a JS file that is run and sets the variables accordingly, no need for additional modules and dependencies

**Comment by NogsMPLS** [comment]
@EnzoMartin I know that'll work with NODE_ENV, but I'm not sure that works with UV_THREADPOOL_SIZE, which is needed in the ```docs``` directory. I'll dig some more.

**Comment by NogsMPLS** [comment]
From what I understand, unlike NODE_ENV which can be changed during a process, UV_THREADPOOL_SIZE must be set before a command is executed. So it must be defined before you called ```webpack config ./webpack.config.production```

see: https://www.future-processing.pl/blog/on-problems-with-threads-in-node-js/

>You can also change this programmatically, from your node application, by writing to process.env.UV_THREADPOOL_SIZE variable. Keep in mind that this is very limited, though. You cannot affect the size of the thread pool once it is created, which is once the first work request is submitted.

**Comment by EnzoMartin** [comment]
Could make use of child_process: https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

Has the ability to receive env variables directly as well. Downside is that it does add a bit of complexity and it's not super elegant but it doesn't require additional dependencies and is cross-platform

**Comment by NogsMPLS** [comment]
looked into ```child_process.spawn``` and found there were some issues with APPDATA for Windows being retained in child processes. Ended up updating  https://github.com/kentcdodds/cross-env to use https://github.com/IndigoUnited/node-cross-spawn-async.

End result is cleaner than ```better-npm-run``` and 1 added dependency. I think it is worth it for ease of use and readability..
