### ISSUE TITLE
 rem size  bug in chrome

### ISSUE THREAD

**Issue by yiluxin** [react-toolbox/react-toolbox#786]
Because chrome restrictions on the smallest font, html in the font-size = 65%, the chrome actually not equal to 10px, but equal to 12px, so the actual display size chrome and other browsers are not the same
<img width="657" alt="2016-09-10 04 01 15" src="https://cloud.githubusercontent.com/assets/10407739/18401066/429a70c0-770b-11e6-99cd-2ceaa2da5882.png">

<img width="461" alt="2016-09-10 03 59 37" src="https://cloud.githubusercontent.com/assets/10407739/18401054/2d5967e8-770b-11e6-87a6-96e7940d4a89.png">

**Comment by javivelasco** [comment]
I don't see the issue as reported. In the screenshot you're attaching the padding is set to 12px but the size is rems is properly configured to `1.2rem`. Also, `Button` component has the right size `36px`, since in configuration is specified as `$button-height: $unit * 3.6 !default;`.

Maybe I'm missing something?
