### ISSUE TITLE
Ripple throws Unknown prop `theme`

### ISSUE THREAD

**Issue by gpresland** [react-toolbox/react-toolbox#790]
Following the code from http://react-toolbox.com/#/components/ripple

Using:

```
"react": "^15.3.1",
"react-toolbox": "^1.2.1",
```

```
import Ripple from 'react-toolbox/lib/ripple';
import theme from 'react-toolbox/lib/ripple/theme';

...

    render() {

        const CustomLink = (props) => (
          <a {...props} style={{position: 'relative'}}>
            {props.children}
          </a>
        );

        const RippleLink = Ripple({spread: 3})(CustomLink);
        const RippleTest = () => <RippleLink>Test</RippleLink>;

        return <RippleTest />;
    }
```

The console throws the following error:

```
Warning: Unknown prop `theme` on <a> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in a (created by CustomLink)
    in CustomLink (created by RippledComponent)
    in RippledComponent (created by Themed RippledComponent)
    in Themed RippledComponent (created by RippleTest)
```

Is there something I am missing?

**Comment by rubenmoya** [comment]
The last line in the wiki: `const RippleTest = () => <RippleLink href='#' theme={theme}>Test</RippleLink>;`

**Comment by gpresland** [comment]
I've tried with and without adding the `theme={theme}` code above since the ripple page example uses it, but the playground example doesn't. The problem persists with and without it.

**Comment by javivelasco** [comment]
This is expected behavior. The ripple HOC should always pass down a theme property because if you decorate a component that implements a ripple, the top theme should be received by the component itself. Also, it should be possible to receive the theme property in the ripple for customization purposes.

The way to avoid this is to extract the `theme` prop as a known prop passed by the ripple before spreading every given prop to the anchor. Consider using something like:

```jsx
const CustomLink = ({ theme, ...other }) => (
  <a {...other} style={{position: 'relative'}}>
    {props.children}
  </a>
);

const RippleLink = Ripple({spread: 3})(CustomLink);
const RippleTest = () => <RippleLink>Test</RippleLink>;
```

I'm afraid the is no immediate solution from the lib without side effects.
