### ISSUE TITLE
anyone using this with redux-from? 

### ISSUE THREAD

**Issue by jasan-s** [react-toolbox/react-toolbox#801]
I can get the input component to work with redux-from but the date-picker and time-component I cannot. 
Time picker simply throws an error:  

> d.getHours is not a function.  

and the DatePIcker renders but can't get it to register a focus event or change events without redux form

**Comment by javivelasco** [comment]
I've never tried but it shouldn't be a problem. There is nothing special with the component indeed. I'll try to set up an example to help you out

**Comment by synchu** [comment]
There's slight quirk with redux-form. See below:
That is your field definition:
```
<Field name='email' component={renderField}
            type='email'
            label='Email address' required
            icon='email' />
```
That is the renderField function:
```
export const renderField = ({ input, label, type, icon, meta: { touched, error } }) => (
  <div>
    <Input {...input} label={label} type={type} icon={icon} error={touched ? error : ''} />
  </div>
)
```
Besides the obvious custom paramaters the important part is `{...input}` that links 'value' prop from Input to redux-form field.
Took me a while to piece it together from the docs.

**Comment by javivelasco** [comment]
Yeah, you have to pass the value to input explicitly either spreading props or passing it directly.

**Comment by tomsowerby** [comment]
I realise that this is closed, but I had a similar issue when trying to use both datepicker and timepicker with one datetime object.
The issue was that the value kept getting set back to a string while editing it, but then returned to being an object when clicking OK. So it worked, but threw exceptions and broke React in the process.
I solved it by hijacking the onChange function and name so that they didn't link back to redux form, but having the original onChange called during onChange so that redux is updated. An example hopefully explains that better:

    const onChange = (value) => input.onChange(value);
    <DatePicker name={input.name+'DatePicker'} onChange={onChange} label={label} type={type} icon={icon} error={touched ? error : ''} />
    <TimePicker name={input.name+'TimePicker'} onChange={onChange} label={label} type={type} icon={icon} error={touched ? error : ''} />

I have these two inputs in different files with different labels, but this should work for an example.
Just wanted to share in case others find this thread as I did.

**Comment by gustavohenke** [comment]
@tomsowerby, you should definitely take a look at [`parse`/`normalize`/`format` props](http://redux-form.com/6.6.0/docs/api/Field.md/).

**Comment by tomsowerby** [comment]
@gustavohenke Thanks, I did consider trying to switch types on the way through, but as I wanted to use the same store property for both Date and Time pickers I ran into issues. There were just too many type switches going on.
From what I saw in the logs, as soon as I hit the arrows or clicked anything on calendar it swapped the field value to a string, as it was all linked to redux form it rerendered, which then caused errors on the timepicker because it only accepts dates.
When using parse / normalise I could check and convert the type, but it started getting messy very quickly, sometimes resetting the date field when selecting times and things like that. I found wrapping the inputs in the non-connected ones a bit simpler to follow, but I'd happily look over other solutions if anybody has them? It does feel like a hack so I welcome the suggestions :smile: 
It looks like the datepicker was adjusted to work with both Date or string types https://github.com/react-toolbox/react-toolbox/pull/474 but the TimePicker was not.
