### ISSUE TITLE
How to overwrite theme .scss styles locally and globally for each component? 

### ISSUE THREAD

**Issue by jasan-s** [react-toolbox/react-toolbox#803]
I can't seem to figure this out. No matter what styles i set using imported css stylesheet on my components , the styles are always overwritten with the theme.scss.  I don't want to just import the raw component either and style everything from scratch. I just want to overwrite some styles for react-toolbox components.

**Comment by javivelasco** [comment]
Hi @jasan-s 

There are some examples and explanations about how the theming approach works in both [theming section](http://react-toolbox.com/#/install) and [react-css-themr](https://github.com/javivelasco/react-css-themr) documentation.

First of all consider you can import components in two ways: styled (if you import from the `index.js` of each component folder) or unstyled (import the component file straight or the exposed factory). The difference between both is that the former will be bundled with styles and classnames attached while the latter will only define the API of classnames without any CSS. Then, you can provide styles in three different ways:

- Setting up an object mapping the classnames for each component from a `ThemeProvider` component. This is useful for theming and overriding styles in every component in the lib.
- Passing down a theme object implementing the classname API. The theme will be merged with the internal one if it already exists, so it's your responsibility to give a higher priority to your custom selectors than the default ones. This happens because the theming approach had happened *after* the initial implementation so some selectors are not completely flat.

In an scenario where you want to create a specific version of a component with special styles you can create a wrapper injecting overrides. Take a look at the example in react toolbox example repository. We create a SuccessButton theming a `Button` component.

If you want to change every component the best approach is to import raw components and define their styles using the context. Then your overrides can be defined in the context and they will affect every component of a given type.

We want to develop better and more detailed examples and I'm working on an small project to allow defining examples. Still need some work so feel free to ask if you still can't make it work.
