### ISSUE TITLE
React-Boilerplate issues - AppBar & Add Docs?

### ISSUE THREAD

**Issue by apinnecke** [react-toolbox/react-toolbox#829]
Hey all,

I have some serious issues with react-toolbox in combination with react-boilerplate.

1) The main problem is, that none of the projects contain an exact tutorial how to integrate into each other, what is definitely understandable. Since a lot of people are using react-boilerplate nowadays, maybe you folks could add another example add where you're integrating both of them and link that one from the docs?

2) There is a guide in the issues which describes how to integrate rect-toolbox into react-boilerplate here: https://github.com/react-toolbox/react-toolbox/issues/527#issuecomment-226996477 . Unfortunately this does not work for AppBar as described here: https://github.com/mxstbr/react-boilerplate/issues/474#issuecomment-249431952 Could you please have a closer look onto this?

Thanks and greetings from Germany!
Alex

cc @schubidu, @inyigo
References: https://github.com/react-toolbox/react-toolbox/issues/527 https://github.com/react-toolbox/react-toolbox/issues/753  https://github.com/mxstbr/react-boilerplate/issues/474 https://github.com/react-toolbox/react-toolbox/issues/725

**Comment by javivelasco** [comment]
I know about a guide but it's not published yet. @rubenmoya can help you out I think!

**Comment by rubenmoya** [comment]
Yes, I wrote a small guide when I was trying to integrate it myself, there you go: [Using React Toolbox with React Boilerplate](https://medium.com/@rubenmoya_/using-react-toolbox-with-react-boilerplate-7bbb0cc3ade0#.7obs8ptsz)

**Comment by stephengfriend** [comment]
@rubenmoya That article is very helpful, however, when I try to create a `theme.css` with the following contents:

```
@import '~react-toolbox/lib/colors';

$color-primary: $palette-red-500;
$color-primary-dark: $palette-red-700;
```

I'm getting `ModuleNotFoundError: Module not found: Error: Can't resolve '~react-toolbox/lib/colors'`.

I mostly had react-toolbox working, already, but there were a few oddities which your guide fixed. If I can figure out how to import the colors for a theme.css, that would be perfect.

**Comment by javivelasco** [comment]
I think you don't need the ~. Postcss imports works nicely with your node modules

**Comment by stephengfriend** [comment]
@javivelasco That works, but it doesn't actually set the theme values. Even if I include `@import '../../theme/_theme.css';` to the `styles.css`of the app container, or any container.

**Comment by rubenmoya** [comment]
@stephengfriend I guess that's because you're using sass variables, I don't really know how to override the css-next variables, but you can change the color overriding the class instead:

```
@import 'react-toolbox/lib/colors';

.appBar {
  background: var(--palette-red-500);
}
```

**Comment by stephengfriend** [comment]
@rubenmoya I was able to change the background, using your example. I was really hoping to be able to set a global theme and then override where necessary. Similar to the examples in the react-toolbox Readme. If you happen to figure this out, I would love to know. I will continue to work on it and if I figure it out, I will report back.

**Comment by anthonyvialleton** [comment]
@rubenmoya your fork repository is not working and I got : `TypeError: Element from loaders list should have one of the fields 'loader' or 'loaders'` error.

I know your position about Sass but this result on manual css override and on slow devices the default themes css appears in first place after being replaced by custom changes...

**Comment by anthonyvialleton** [comment]
Damn, yesterday the sass integration of react-toolbox with react-boilerplate worked. 

I was able to override the default theme variables for the app_bar component and make the post-css and sass loader cohabit. This was very helpful to erase flashing color on the element load.
 
But, the production build of react-boilerplate failed just after having generated the final resources. And I think this was because of the double sources type of assets managed in the application. 

So I struggled with the webpack production config to pass the production build without errors and this didn't worked. 
And now, the solution I found (crawling the entire issues about the subject) doesn't work anymore...

@rubenmoya, when I checkout your fork project I got a webpack loader error : 

`TypeError: Element from loaders list should have one of the fields 'loader' or 'loaders'`

What a pain... 
Working on a dev branch to use postcss integration (that doesn't integrate correctly with react-boilerplate) and being unable to override variables is not satisfaying at all.

Lack of good documentation there.

**Comment by rubenmoya** [comment]
Hi @anthonyvialleton, I pushed a change in the repo to fix that error, check it out!

**Comment by javivelasco** [comment]
There is no need for a complex Webpack setup. This covers every case so this issue can be closed.

![react-toolbox-themr](https://cloud.githubusercontent.com/assets/1634922/21305836/285a092a-c5ce-11e6-8ad4-7b170dc97d1b.gif)

Check [react-toolbox-themr](https://github.com/react-toolbox/react-toolbox-themr). For now it works from 2.0.0-beta.4
