### ISSUE TITLE
How to add in current project

### ISSUE THREAD

**Issue by tnikola** [react-toolbox/react-toolbox#854]
Hi guys, 

Nice job to you all! Great tool!

 I am quite new to the whole react/redux world and confused using webpack. I want to add into the below git project :
https://github.com/JonPSmith/AspNetReactSamples --> ReactWebPack.CoreRC2

the react-toolbox but cant seem to achieve this. Can i get help on this matter. Didnt find anywhere how to add toolbox to existing project using one predefined theme for all component controls.

Is there a tutorial other than the one at the main git page or some helpful guide to achieve this??? 

thanks alot

**Comment by javivelasco** [comment]
You can follow the configuration in the [react-toolbox-example](https://github.com/react-toolbox/react-toolbox-example) repository. There you can find a working webpack example. Anyway it's going to be easier with PostCSS coming in the next major.

I don't know about other guides apart from the documentation itself and the example but the documentation in the next major will be bigger. If you have any troubles there is activity in stackoverflow too!

**Comment by tnikola** [comment]
ok thanks! When is the next major coming?

**Comment by javivelasco** [comment]
@tnikola it's like that because usually you want to style components so the most common practice (if you're not using some css-in-js solution) is to create a stylesheet with the same component name. In react-toolbox case, if you want to customize a component you have to create a style module for it, and you'll be importing the module and passing it using the `theme` property.

I cannot ensure a release date for the 2.0.0 because I work on it on my spare time, but hopefully in a month or so it should be ready with a new documentation.

Happy to help!
