### ISSUE TITLE
Cannot use date/time picker in a dialog

### ISSUE THREAD

**Issue by alltom** [react-toolbox/react-toolbox#86]
It looks like date and time pickers try to display their own dialog, but fail to take over the whole screen:

![image](https://cloud.githubusercontent.com/assets/1678/11065737/d8dc3afa-8779-11e5-8131-60e7ac36ce8a.png)

**Comment by javivelasco** [comment]
Yes, this is quite tricky. You get it by adding a picker inside a dialog, right? That's an important one, working on it.

**Comment by javivelasco** [comment]
Initially we thought about the dialogs as fixed positioned components taking the whole screen. The problem is that there is a known issue when a parent uses `translate` and then renders on of those components with overlay. In those cases it looks like the dialog takes the root coordinates from the parent's translated position instead of the root.

To fix this I think we would need change the render of this kind of component to a placeholder at the root level or something similar. As I said it's important, I'll try to check on it ASAP.

**Comment by javivelasco** [comment]
Related to #94
