### ISSUE TITLE
May 1st missing

### ISSUE THREAD

**Issue by k0r8i** [react-toolbox/react-toolbox#870]
Hi there!
Did anyone encounter May 1st not showing up in languages different to English?
I can reach the date by using cursors though it's not visible.
(Screenshot taken from react-toolbox.com attached)

Cheers
Korbi
![maymissing](https://cloud.githubusercontent.com/assets/17675159/19391659/e1b0a872-922d-11e6-85f1-ecde40b39c41.png)

**Comment by rrott** [comment]
The problem is in calculating correct position for the first day of the first month's week.
In this particular May the very first day starts on Sunday and for countries where weeks start on Sunday, it's the first day of the first May's week while for others it's the last day of the first May's week. 

I am adding PR that fixes this issue.
