### ISSUE TITLE
Question: Does anyone use this library without the default theme?

### ISSUE THREAD

**Issue by cvle** [react-toolbox/react-toolbox#874]
I hope it is appropriate to put this question here. 

As I plan to open source a similar project, I am torn, whether or not I should expose the components without a default style. Most libraries always include a default theme whereas this project has chosen to expose both unstyled and styled components. 

Given the additional complexity, did it pay off for this project to support unstyled components? Is anyone using it without the default theme?

**Comment by javivelasco** [comment]
Hi @cvle ! That's an interesting question and I would like to know more about the usage too. In any case, the real issue here is that styled components are requiring the CSS Module for you which means that you need to configure CSS Modules in your project no matter what.

This is a real limitation and should be optional so I'm working now in a version with some pre-transformed CSS and another one that left only custom css properties to reduce the amount of configuration needed. You can pass the themes to each component using `ThemeContext`.

So my answer in this regard is that apparently is not really useful but that because most people is forced to use CSS Modules and without alternative it is true that you don't need to import unstyled.

**Comment by cvle** [comment]
> So my answer in this regard is that apparently is not really useful but that because most people is forced to use CSS Modules and without alternative it is true that you don't need to import unstyled.

Sorry, I didn't fully get your answer. Are you saying that you think it is not really useful to have both styled and unstyled component, but in the case of this project it is justified because otherwise it would force everyone to use CSS Modules without alternatives?

**Comment by anri-asaturov** [comment]
I'm not sure why is it true that themr or css modules make possible for components to ship unstyled... 
1. With themr and css-modules components still count on specific classes to be used, exactly as with plain old css. 
2. Without themr and css-modules you can just ignore shipped css(as long as there are no inline style) and write your own.

I think the whole thing is just about css-in-css or css-in-js, there are equal styling benefits, but css-in-css makes library easier to use for wider population.

**Comment by javivelasco** [comment]
@cvle I mean it would be an easier approach to ship **just** unstyled components and tell people how can you use `ThemeProvider` to pass styles. This allows more flexibility because you are free to choose the way you communicate the css module to each component. But also it is more complex and dummy because you need to be aware of the components you are using to choose what CSS should be imported.

Anyway there are a lot of people using CSS Modules, and it is more handy for them if we expose styled components too (components that have that `require('./theme.css')` on top). This way, if you are using css-modules you can forget about how style is required or passed or whatever. You just import the component and webpack will do the rest. I think it's important to keep this. Also, in previous versions, this was the only way to use react-toolbox so it's backwards compatible.

The benefits of unstyled components are pretty important too. With some pre-processed css builds you'll be able to use react-toolbox with react-create-app for example. This is just not possible if we only expose styled components because you can't configure css-modules to work with react-create-app without ejecting.

So more or less yeah. I think it's kind of a mess to have both styled and unstyled components but both have their own benefits and cutting off one of them reduces flexibility. I don't want to force people to use CSS Modules but still want to keep the goodies for people using them. If you had to select one approach over another, what would be your choice?

**Comment by javivelasco** [comment]
Agree @anri-asaturov css-in-css is less controversial and flexible. Also it makes theming and overriding styles way easier, but still we can't push everybody to use CSS Modules. I mean, you don't really need to use it but you have to be aware of it because of the needed configuration.

In an ideal world, I'd ship components without styles and a prebuilt CSS stylesheet where you include wherever you need and make theming possible using native css custom properties. Any inline style should work with positioning and stuff like that so you won't need to customize it.

Regarding having both options, what would be your choice? Id I had to pick one I'd provide always unstyled components being your responsibility to include the appropriated CSS.

**Comment by anri-asaturov** [comment]
> but still we can't push everybody to use CSS Modules.
@javivelasco wait, by 'css-in-css' i mean *no* css-modules. I think css-modules _might_ be useful for your own components, but from library you might want it if it's too large and you use too little from it (not a case for react-toolbox, it's small).

So if you ask me, I'd pick shipping components with a choice of compileable or prebuilt css, one per component, so someone who really cares can ignore component css and create it from scratch instead of overriding. I really fail to see any benefit of css-modules in component library when you can do the same with plain css.

**Comment by javivelasco** [comment]
Sorry I get you wrong @anri-asaturov! Probably unstyled is not the best word to describe what I mean. One benefit you'll be losing is the ability to generate your build just with the CSS you really need by requiring it. Also, customization passing a partial theme object may be more handy that actual overrides straight in the CSS. Please feel free to ping me both through Discord to discuss what would be the best API for the next version. I'm currently working on it!

Please feel free to ping through discord to discuss ideas on what would be the best API

**Comment by anri-asaturov** [comment]
@javivelasco discord handle?

**Comment by javivelasco** [comment]
@Javi

**Comment by anri-asaturov** [comment]
It needs code
anri#9929

**Comment by cvle** [comment]
I tend to get away from pure CSS overwrites, that violates component encapsulation. Partial theme object works, even with code splitting, which I'm currently using in one of my projects. Still nothing comes close to the level of convenience of having default styles included using require and let webpack handle the rest. 

I think 99.9% of all users will use the default styles and add customization on top. I wanted to reach out to see if I'm wrong and if we can find users of this library who actually wants to strips out the default styles. What do you think about my assumption?

Doing styles completely from scratch is not easy either. The default styles has evolved over time to deal with browser differences and are often rather complex to support all features of the component.

If rarely anyone wants to removes the default styles, why support it. The remaining few could just cancel out the default styles by overwriting them.

I know there are benefits in exposing unstyled components, but will those outweigh the disadvantage of having a more complicated API and code base, given that it is rarely used?

This is up for discussion, thanks for the awesome input!

P. S. I'd rather keep conversation here, so other people can join in the conversation.

**Comment by cvle** [comment]
I've been thinking these past hours and it finally starts to sink in. I understand now what you mean, @javivelasco. The value in exposing unstyled components lies in not forcing the user to use a certain technology for styling, thus providing interoperability. I'm convinced.

Though for convenience there should be a version where default styles are included. This has been interesting to read: https://github.com/nikgraf/future-react-ui.

At this point I found answers to my original question, thanks a lot!

@javivelasco I might ping you later to exchange some more thoughts about how to implement this. Right now, I'll try out a few ideas I got from this conversation! :-)

**Comment by javivelasco** [comment]
Really glad to hear @cvle !! Feel free to ping me whenever you want, I think there is a lot to share and discuss about styling. That resource is very inspiring, in fact, it is mentioned in [react-css-themr](http://github.com/javivelasco/react-css-themr)!
