### ISSUE TITLE
not meeting npm decencies on installation

### ISSUE THREAD

**Issue by packetstracer** [react-toolbox/react-toolbox#875]
Trying to use It on a fresh create-react-app structure, but I get 2 errors when installing the package via npm. This is what I get:

**├── UNMET PEER DEPENDENCY immutability-helper@~2.0.0
├── UNMET PEER DEPENDENCY react-addons-css-transition-group@~0.14.0 || ~15.3.0**
├─┬ react-scripts@0.4.3
│ └─┬ babel-runtime@6.11.6
│   └── core-js@2.4.1 
└─┬ react-toolbox@1.2.3 
  ├── classnames@2.2.5 
  ├── core-js@2.4.1 
  ├── normalize.css@5.0.0 
  └── react-css-themr@1.4.1 

Anyone knows how to solve this? Thanks in advance.

**Comment by anri-asaturov** [comment]
Peer dependency is something you should have in direct dependencies of your project.
So do this:
```npm i -S immutability-helper react-addons-css-transition-group```
It will install dependencies and save them in your package.json for future installs.

**Comment by packetstracer** [comment]
Solved, thanks for the instant reply @anri-asaturov !

**Comment by apaatsio** [comment]
What is the reason that these are peer dependencies instead of normal dependencies?

**Comment by javivelasco** [comment]
You may use them in your project too so the idea is to add just one dependency that can be used by both react toolbox and your project. :)

**Comment by apaatsio** [comment]
@javivelasco, npm already handles this. If two packages have the same dependency it is installed only once. 

How I see is that this can be split in two use cases:

- projects who would include immutability-helper and react-addons-css-transition-group regardless of react-toolbox
- projects who include immutability-helper and react-addons-css-transition-group only because they are required by react-toolbox

Having them as peer dependencies is not helping either use case.

**Comment by javivelasco** [comment]
Ok we can move them then. Happy to get a pr :)
