### ISSUE TITLE
IconMenu validateDOMNesting

### ISSUE THREAD

**Issue by dhassaine** [react-toolbox/react-toolbox#879]
I updated from version 1.2.1 to 1.2.3 and my IconMenu's have stopped working -- clicking on them causes a ripple effect but nothing else. In the console I get a bunch of warnings of the following format: warning.js:36Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>. See MainAppBar > ThemedAppBar > AppBar > ThemedThemed > ThemedRippledComponent > RippledComponent > IconButton > button > ... > ThemedThemed > ThemedRippledComponent > RippledComponent > IconButton > button.

Any ideas?

Thanks a lot for all the great work.

**Comment by javivelasco** [comment]
Yeah, this is probably happening because that release modifies the `AppBar`. Left and Right icons now are `IconButtons` so if you are passing an `IconButton` as `leftIcon` for example, it's going to nest two `IconButtons` generating invalid markup (a button inside another button). You can fix it passing just the icon name and click handler. If you need to pass more props just pass the icon as a child for the `AppBar` instead of `leftIcon`.

**Comment by dhassaine** [comment]
Thanks. Moving the icons to children of the AppBar fixes the issue as suggested. For anyone who needs to do the same thing but is struggling with positioning the left icon -- you can wrap it in a div and give it the following style: { order: -1 } to force it to the left of the AppBar title.
