### ISSUE TITLE
Why using the label of the selected item instead of the valu ein DropDown? Seems like a bug.

### ISSUE THREAD

**Issue by hossein761** [react-toolbox/react-toolbox#892]
Hi,

I am wondering why in the render method of --> [Dropdown.js](https://github.com/react-toolbox/react-toolbox/blob/dev/components/dropdown/Dropdown.js#L173) (line 173)the item's label is used to fill in the value in the input field instead of the item's value?

``` javascript
return (
        <div data-react-toolbox='dropdown' className={className}>
          <Input
            {...others}
            className={theme.value}
            onClick={this.handleClick}
            required={this.props.required}
            readOnly
            type={template && selected ? 'hidden' : null}
            **value={selected && selected.label ? selected.label : ''}**
          />
        {template && selected ? this.renderTemplateValue(selected) : null}
          <ul className={theme.values} ref='values'>
            {source.map(this.renderValue)}
          </ul>
        </div>
      );
```

**Comment by rubenmoya** [comment]
I guess is because you want to see in the input the text of the item you selected, for example `Spain` instead of an id, or "es-ES" or something like that. But yeah, if you submit the form it will have the wrong data, right?

**Comment by L-u-k-e** [comment]
I'm running into exactly this problem today. Wrong data when I submit the form

**Comment by javivelasco** [comment]
@hossein761 this is done because the look and feel of the `Dropdown` is exactly the same as the `Input`. It makes sense to reuse the component but what we want to display is the `label` so that's what is passed down as `value` to `Input`. The most correct approach would be to remove the actual `Input` and make the `Dropdown` content look exactly the same by reusing styles. This is not that easy work and should be fixed with a next release, I have a reimplementation of the Dropdown that looks way better but it's not ready to be published yet
