### ISSUE TITLE
dialog size

### ISSUE THREAD

**Issue by jakehm** [react-toolbox/react-toolbox#894]
I have a dropdown in a dialog box.  When the drop down is activated, it's cut off because the dialog box isn't big enough.

I tried putting a div with height:100% as a container inside my dialog box.  Didn't work.
I tried styling the dialog box directly with height:100%.  Didn't work.

```
            <Dialog
                actions={this.actions}
                active={this.props.active}
                onEscKeyDown={this.props.onToggle}
                onOverlayClick={this.props.onToggle}
                title='Edit Task' 
                type='fullscreen'
                <p>placeholder</p>
                <Dropdown
                    auto
                    source = {this.dropDownSource}
                    value = {this.state.dropDownValue}
                    onChange = {this.handleDropDownChange}
                />
            </Dialog>

```

**Comment by lucaas** [comment]
I encountered a similar issue recently and worked around the issue by ensuring the Dialog body has a sufficiently large height to render the require elements.

Something like:
```
<Dialog ... >
    <div style={{ minHeight: '300px' }}>
         <Dropdown ... />
    </div>
</Dialog> 
```

However, it would be nice to have the option to allow children to overflow the dialog if possible.

**Comment by lucaas** [comment]
Just upgraded to a newer version and I am not sure if the fix in 00da4dd was a good solution. The dialog will now cut off the body if it does not fit within the elements.

You can test this in the sandbox by adding some height to the body. For example, add a style tag to the <p> element with the following contents: `style={{ paddingTop: '100vh', background: 'red' }}`. After the change in 00da4dd you will no longer be able to scroll to see the contents.

While I can add overflow scroll to the dialog by providing a css class, the behaviour is not the same as before (must scroll to reach action buttons)

**Comment by javivelasco** [comment]
Gonna leave it open to remember checking it out!

**Comment by patilparesh** [comment]
i want to make `class="theme__overlay___2KTgD theme__active___21JE3"` width and height 100%
i am added external sass in page and in dialog tag i added `theme={MultipleProdTheme} className={MultipleProdTheme.overlay}` but this class not work on overlay div.. how to change width and height overlay div

**Comment by zjaml** [comment]
I also had problems with one of my dialogs content simply larger than the phone screen size.
Would be really nice if the dialog content have overflow support.

**Comment by zjaml** [comment]
Thanks for the fix! @2sComplement @javivelasco

**Comment by jacargentina** [comment]
@javivelasco Javier, there is some planning on making the dropdown/autocomplete components to be able to overflow on dialogs? I'm not very convinced on having to make my dialog full height because, sometimes, my dropdown list _could_ be very large: when the source list is small, the dialog is super big and its a little ugly.

Maybe there is some other way around this and i simply cant see it? Cheers!

**Comment by kiwipxl** [comment]
Agreed with @jacargentina 
I'm getting this when using Card. I ended up just not using Card because I didn't have the time to look try and fix it within react toolbox. An ideal solution might be to easily disable overflow through props to Card or maybe have the props reside on Dropbox for example.

Not sure, I might be mistaken with all this.

**Comment by VinodLouis** [comment]
I did a workaround css using 

div[data-react-toolbox=dialog] > section{
  overflow: auto;
}
