### ISSUE TITLE
Instructions for use with create-react-app

### ISSUE THREAD

**Issue by arosenb2** [react-toolbox/react-toolbox#896]
It'd be really good to include simple instructions for making this work with `create-react-app`. I've gotten it to finally compile, it's not pulling in any type of default theme for me.

**Comment by rubenmoya** [comment]
If I'm not mistaken, the only thing you have to do is run eject, and then configure postcss in the `webpack.config.dev.js` file, mine looks like this:

```
postcss: function(webpackInstance) {
    return [
      require('postcss-import')({
        addDependencyTo: webpackInstance
      }),
      require('postcss-mixins')(),
      require('postcss-each')(),
      require('postcss-cssnext')(),
      require('postcss-reporter')({ clearMessages: true })
    ];
  },```

**Comment by javivelasco** [comment]
I can't write down now instructions because I never tried out react-toolbox with react create app but I'm aware of the issues that CSS modules generates in that project. I'm preparing an approach to avoid the need of CSS Modules at all and also some builders to generate your customized css without configuration.

Still work needs to be done and docs are going to change so I encourage everybody familiar with the setup to write some instructions in the current documentation :) Anyway what @rubenmoya said should be enough so I'm closing here

**Comment by wtgtybhertgeghgtwtg** [comment]
> I'm preparing an approach to avoid the need of CSS Modules at all and also some builders to generate your customized css without configuration.

Is there an overview of this approach?

**Comment by javivelasco** [comment]
Not yet @wtgtybhertgeghgtwtg I have it locally with other stuff but I'm doing my best to publish it asap. That build system and the documentation update is the only thing remaining to merge the PostCSS branch
