### ISSUE TITLE
Ripple effect on raw RadioButton.js is not visible but remains in the DOM

### ISSUE THREAD

**Issue by alexhisen** [react-toolbox/react-toolbox#946]
We are using a raw/unthemed RadioButton and taps on it result in the following HTML added inside the div data-react-toolbox="radio":
```
<span data-react-toolbox="ripple"><span role="ripple" class="MyComponent__ripple___3FBAJ" style="width: 271.416px; height: 271.416px; transform: translate3d(-135.708px, -135.708px, 0px) scale(1);"></span></span>
```

No ripple effect is actually visible and this span doesn't ever go away from the DOM!

Our relevant CSS is pretty much like in the default theme:
```
.input {
  position: absolute;
  width: 0;
  height: 0;
  padding: 0;
  margin: 0;
  border: 0;
  opacity: 0;
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
}
.ripple {
  background-color: #00adee;
  opacity: .3;
  transition-duration: 650ms;
}

```
Each radio label tag is about a 100px x 83px box.

**Comment by javivelasco** [comment]
The ripple assumes that you are setting a transition on the opacity, being this the last animated property. This way, a listener is set on transition ends to check when the animation finished. This allows to modify the transition duration via CSS without touching the Javascript. If you feel like this should be changed, please reopen!

**Comment by alexhisen** [comment]
I am afraid you lost me. :-(
I am using the same .riple CSS as the styled component as indicated above. What do I need to do when using the raw RadioButton to a) have a ripple effect similar to the styled one; b) not have the HTML for the ripple remain in the DOM when the ripple animation completes?
Thanks.

**Comment by javivelasco** [comment]
The most important part of the ripple styling is [here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/ripple/theme.scss#L27-L42). Those classnames control the ripple lifecycle and when the element gets created, an event listener is added listening for the transition finish events. As you see in that snippet when the ripple gets active it has a `transition-property` set to transform and an `opacity` different from `0`. This means while kept like that the size change will be animated but keeping the opacity. When the ripple covers the whole surface the `active` is removed so now transition affects to both `opacity` and `transform` changing the opacity to `0`. This makes the ripple disappear. Then, if you check [here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/ripple/Ripple.js#L82-L91) you will see that there is an event listener for when the opacity transition finishes. Your ripple is not getting removed because that never happen.

To obtain a similar ripple you can either import from `ripple/index.js`, like with the rest of components, of you can import the `CSS` module from the top and pass it down. Just like any other component. Or, of course, you can just copy the style and pass a css module built manually :)

**Comment by alexhisen** [comment]
Ok, so if I understand correctly, my problem is that when I do this:
import RadioButton from 'react-toolbox/lib/radio/RadioButton';
that RadioButton is in turn importing the raw Ripple.js instead of the themed Ripple. So, how can I change that?

**Comment by javivelasco** [comment]
Exactly. Importing components from their definition does not require the css for you. This is done to make optional configuring CSS modules because this way you can use a `ThemeProvider` to pass the theme modules.

You might want to import raw what you want to fully customize and with style what you don't. For example, if you want to fully customize a `RadioButton` so the ripple covers the whole thing you should inject a `identity` decorator to the `Radio` (because it expects it) and then decorate the `RadioButton` with a ripple. You can see [here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/radio/index.js) more or less how it works. It should be something like this (not sure if it works).

```jsx
import { themr } from 'react-css-themr';
import { RADIO } from '../identifiers.js';
import themedRippleFactory from '../ripple';
import radioFactory from './Radio.js';
import { radioButtonFactory } from './RadioButton.js';
import { radioGroupFactory } from './RadioGroup.js';
import theme from './theme.scss';

const identity = Component => Component;
const Radio = radioFactory(identity);
const rippleDecorator = themedRippleFactory({ spread: 2.6 });
const RadioButton = rippleDecorator(radioButtonFactory(Radio));
const ThemedRadioButton = themr(RADIO, theme)(RadioButton);
const ThemedRadioGroup = themr(RADIO, theme)(radioGroupFactory(ThemedRadioButton));

export default ThemedRadioButton;
export { ThemedRadioButton as RadioButton };
export { ThemedRadioGroup as RadioGroup };
```

Didn't try it but more or less that's the idea. While we provide two ways of importing (with/without css) DI is crucial.
