### ISSUE TITLE
[Question] What is the point of calling themr twice on a single component?

### ISSUE THREAD

**Issue by 3amprogrammer** [react-toolbox/react-toolbox#947]
During reading through source code to find some interesting patterns and good practices I have found that you `themr` is called twice. First only with identifier and only in `index` file with additional default theme. I have read `themr` docs already but I can't figure out the point of this. 

Would you please enlighten me on this topic?

**Comment by javivelasco** [comment]
Actually it is not applied twice but only once. In component definition file we write a `factory` that is called with the identifier and without styles. The purpose is to be able to import the component/factory without any css requires. It is intended for people that want to mock CSS modules or just avoid them.

In the index file we do require the CSS file and call themr providing the module by default but it should be called over a `factory` invoke. The returning value of a factory should be a component without `themr`, otherwise it's a bug. 

With this approach you can import from the component if you don't want to use CSS modules directly or even import the factory to inject custom dependencies. If you are using CSS modules maybe it's more convenient to import from index and to forget about anything else. :)
