### ISSUE TITLE
Sidebar scrollbar?

### ISSUE THREAD

**Issue by jakehm** [react-toolbox/react-toolbox#948]
http://react-toolbox.com/#/components

How are you supposed to scroll down the list of components?

**Comment by wtgtybhertgeghgtwtg** [comment]
Focus on it, then use the arrow keys, or drag it.  But, yeah, there should probably be a scrollbar there.

**Comment by rubenmoya** [comment]
Just place the mouse on the list and scroll with the mouse, it works for me

**Comment by jharrowmortelliti** [comment]
It's fine on mobile.  It's ok with mouse equipped with a middle button.  But it is very bad ux on a touchpad.
It's not just the sidebar, either.  Every frame has that issue.  Especially the playground where the arrow key option doesn't work as well because it will just move the cursor in the text editing environment.
My solution has been to hold down selection and move up and down that way.  But sometimes that clicks a link on the sidebar, and it's harder with the playground text editor.

Great website

**Comment by jharrowmortelliti** [comment]
Clicked a wrong button lol..
Anyway great website but this is a big ux issue for touchpad.

**Comment by rubenmoya** [comment]
I'm using a macbook pro, and I don't have that issue with the touchpad, maybe it's browser related since there was another person with a similar problem.

**Comment by jakehm** [comment]
I don't think it's browser related.
How are you scrolling on the sidebar rubenmoya?  I'm guessing macbooks have some double touch scroll feature?
Macbook pros have awesome touch pads.  On lower end laptops touch pad scroll feels bad or is non existent.

**Comment by stovmascript** [comment]
I think most non-MacBook laptops have a touchpad on which a scrolling gesture is nearly impossible, if not just straight up impossible, so people automatically resort to grabbing a scrollbar. It's a big UX issue. I didn't even realize it until a report I got today because I mainly use MacBook myself nowadays.

**Comment by jakehm** [comment]
https://github.com/react-toolbox/react-toolbox/blob/dev/docs/app/components/layout/main/components/navigation.js

Looks like that sidebar is created with an aside element. Why not use a NavDrawer and enable scrollY?

**Comment by javivelasco** [comment]
@jakehm The docs are quite outdated. There were no `Layout` component at that moment :) It doesn't worth to change it either because there is a new implementation of the Layout in #666

Also we have a new design pending to be implemented. I guess this can be closed, reopen otherwise!
