### ISSUE TITLE
if we choose locale like "pt" or "fr" in date picker component, can we change the label of "ok" and "cancel" actions

### ISSUE THREAD

**Issue by raymondyan** [react-toolbox/react-toolbox#962]
Consider it carefully, when we need to change the locale of  datetime in date picker component, we may also want the label of ACTIONS like "cancel" and "ok" in the same languages.

For now i haven't found the properties which can change the actions in date picker (like dialog)

Hope you can add it 👍

**Comment by javivelasco** [comment]
In my opinion this shouldn't be react-toolbox responsibility. You have properties to customize the content of both buttons and since you are changing the language from outside the component you can also change the context. It is ok to change the name of the month and stuff like that from inside the library but I think it's not the same for the button labels.

As I always say, maybe I'm mistaken. If somebody else feels the same please reopen!
