### ISSUE TITLE
How to increase the z-index of a snackbar?

### ISSUE THREAD

**Issue by jakehm** [react-toolbox/react-toolbox#976]
I am trying to have a snackbar appear over a full-sized leaflet map.
I tried using a theme with .snackbar's z-index at 999999999 but it's not working.

I can put other html elements like a button above the map but not the snackbar.

**Comment by javivelasco** [comment]
The issue here is that the `Snackbar` is rendered outside the current tree so we can allow to define it deep inside and still keep it out of transformations. Probably what you need is to add the `z-index` to a `Portal` but there is no suck property now in the `dev` branch. Just added it to the `css-next` which is refactored. I encourage you to move to it!
