### ISSUE TITLE
Import behaviour themed vs raw

### ISSUE THREAD

**Issue by borela** [react-toolbox/react-toolbox#977]
Just a suggestion and should be easy to change.

```Javascript
import Button from 'react-toolbox/lib/button';
// Button has the default theme...
````

```Javascript
import {Button} from 'react-toolbox/lib/button';
// Raw button without theme...
````

**Comment by javivelasco** [comment]
This might be even more confusing. The issue is that there are subcomponents grouped under a folder sometimes. For example, you can import both `Button` and `IconButton` from `/button/index.js`. You can export by default the `Button` with css and `{ Button }` without css but... what about `IconButton`?

Thanks for the suggestion but I don't really see it possible without an full reorganization :(

**Comment by borela** [comment]
I noticed that exact problem yesterday when I needed to integrate with react router :/.
